# Generated by Django 6.1.1 on 2026-09-25 02:25

import apps.shared.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import append_only_trigger_operations, rls_operations

"""collab 0001 (chunk 10, COL-01, COL-02): comments, the people they mention, the text an
edit replaced, notifications and the proof that a mail went out. All five are tenant
tables: `tenant_id` on every row, row-level security enabled and forced, and the one
`tenant_isolation` policy, so cw_app reads and writes nothing of another bank's and cannot
bypass it (NFR-01, ADR 0022). None is mixed: nothing here is a library row.

`comment_revision` also takes the append-only trigger, so the text an edit replaced cannot
be rewritten or deleted away (CHUNK10_TASKS ruling 10).

The composite keys below are the database's refusal of a row that names a person who is
not a member of the row's bank, or another bank's comment. A foreign-key check does not
pass through row-level security, so a single-column key would find the other bank's row
and accept it; the composite key must find it in the row's own bank (D-18). They are
written in SQL because Django declares a foreign key on one column only, and they are not
deferrable, so the refusal comes at the insert that makes it. `membership` already carries
`UNIQUE (tenant_id, user_id)`; `comment` gains `UNIQUE (tenant_id, id)` above for the same
purpose. A nullable column (`on_behalf_of_id`, `email_message.user_id`) is checked when it
is set and skipped when it is null.

Departures from `schema.sql` §8, §10 and §21, recorded in INPUT_DELTAS §1: mentions are
`comment_mention` rows rather than `comment.mentions uuid[]`; `comment_revision` is new;
`notification.kind` gains three values and `notification.on_behalf_of_id` is new;
`notification.subject_type` and `comment.subject_type` are strings checked by the subject
registry rather than the Postgres enum; `email_message` gains `sent_on` and its unique key;
`email_status` is a text column with choices."""

# (table, constraint, columns, referenced table, referenced columns)
COMPOSITE_KEYS = (
    ("comment", "comment_author_is_member", "tenant_id, author_id", "membership", "tenant_id, user_id"),
    ("comment_mention", "comment_mention_same_bank_comment", "tenant_id, comment_id", "comment", "tenant_id, id"),
    ("comment_mention", "comment_mention_user_is_member", "tenant_id, user_id", "membership", "tenant_id, user_id"),
    ("comment_revision", "comment_revision_same_bank_comment", "tenant_id, comment_id", "comment", "tenant_id, id"),
    ("comment_revision", "comment_revision_editor_is_member", "tenant_id, edited_by_id", "membership", "tenant_id, user_id"),
    ("notification", "notification_user_is_member", "tenant_id, user_id", "membership", "tenant_id, user_id"),
    ("notification", "notification_on_behalf_of_member", "tenant_id, on_behalf_of_id", "membership", "tenant_id, user_id"),
    ("email_message", "email_message_user_is_member", "tenant_id, user_id", "membership", "tenant_id, user_id"),
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("shared", "0008_library_write_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_type", models.CharField(max_length=64)),
                ("subject_id", models.UUIDField()),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "comment",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="CommentMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="collab.comment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "comment_mention",
                "ordering": ["comment", "user"],
            },
        ),
        migrations.CreateModel(
            name="CommentRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="collab.comment",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "comment_revision",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("to_email", apps.shared.fields.CIEmailField(max_length=254)),
                ("template", models.CharField(max_length=64)),
                ("subject", models.TextField()),
                (
                    "subject_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("subject_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("sent", "sent"),
                            ("delivered", "delivered"),
                            ("bounced", "bounced"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_on", models.DateField()),
                ("error", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "email_message",
                "ordering": ["-queued_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("assigned", "assigned"),
                            ("mention", "mention"),
                            ("signoff_requested", "signoff_requested"),
                            ("approval_requested", "approval_requested"),
                            ("due_soon", "due_soon"),
                            ("overdue", "overdue"),
                            ("escalation", "escalation"),
                            ("proposal_waiting", "proposal_waiting"),
                            ("saved_search_hit", "saved_search_hit"),
                            ("participant_added", "participant_added"),
                            ("involved_item_changed", "involved_item_changed"),
                            ("review_due", "review_due"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subject_type", models.CharField(max_length=64)),
                ("subject_id", models.UUIDField()),
                ("title", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "on_behalf_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["tenant", "subject_type", "subject_id", "created_at"],
                name="comment_subject_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="comment_tenant_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="commentmention",
            constraint=models.UniqueConstraint(
                fields=("comment", "user"), name="comment_mention_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailmessage",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "user",
                    "template",
                    "subject_type",
                    "subject_id",
                    "sent_on",
                ),
                name="email_message_once_a_day",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("read_at__isnull", True)),
                fields=["tenant", "user", "-created_at"],
                name="notification_inbox_idx",
            ),
        ),
        *[
            migrations.RunSQL(
                sql=f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY ({columns}) REFERENCES "{target}" ({target_columns})',
                reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
            )
            for table, name, columns, target, target_columns in COMPOSITE_KEYS
        ],
        *rls_operations("comment"),
        *rls_operations("comment_mention"),
        *rls_operations("comment_revision"),
        *rls_operations("notification"),
        *rls_operations("email_message"),
        *append_only_trigger_operations("comment_revision"),
    ]
