# Generated by Django 6.1.1 on 2026-09-25 03:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import rls_operations

"""collab 0002 (chunk 8, COL-04, D-18): a person or a team taking part in a register entry
or a case. A tenant table: `tenant_id` on every row, row-level security enabled and forced,
and the one `tenant_isolation` policy (NFR-01, ADR 0022).

A foreign-key check does not pass through row-level security, so every reference is also a
composite `(tenant_id, …)` key, written in SQL because Django declares a key on one column
only: to `UNIQUE (tenant_id, id)` on `tenant_obligation`, `change_case` and `team`, and to
`membership_tenant_user_unique` for a person, which makes everyone named here a member of the
row's own bank. A nullable column is checked when it is set.

`participant_one_subject` and `participant_one_member` are the design's `num_nonnulls`
CHECKs: exactly one of the register entry and the case, exactly one of the person and the
team (MY_WORK_AND_MARKETS 3.2)."""

# (column, referenced table, referenced column)
COMPOSITE_KEYS = (
    ("tenant_obligation_id", "tenant_obligation", "id"),
    ("case_id", "change_case", "id"),
    ("team_id", "team", "id"),
    ("user_id", "membership", "user_id"),
    ("added_by_id", "membership", "user_id"),
    ("removed_by_id", "membership", "user_id"),
)

# (constraint, condition)
CHECKS = (
    ("participant_one_subject", "num_nonnulls(tenant_obligation_id, case_id) = 1"),
    ("participant_one_member", "num_nonnulls(user_id, team_id) = 1"),
)


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_evidence"),
        ("collab", "0001_comments_notifications"),
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("register", "0002_gaps_history_links"),
        ("shared", "0008_library_write_guard"),
        ("taxonomy", "0010_team_org_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cases.changecase",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.team",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "tenant_obligation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="register.tenantobligation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "participant",
                "ordering": ["added_at", "id"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=["tenant", "user"],
                        name="participant_live_user_idx",
                    ),
                    models.Index(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=["tenant", "team"],
                        name="participant_live_team_idx",
                    ),
                    models.Index(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=["tenant", "case"],
                        name="participant_live_case_idx",
                    ),
                    models.Index(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=["tenant", "tenant_obligation"],
                        name="participant_live_entry_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=("tenant_obligation", "case", "user", "team"),
                        name="participant_live_unique",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        *[
            migrations.RunSQL(
                sql=(
                    f'ALTER TABLE "participant" ADD CONSTRAINT participant_{column}_same_tenant '
                    f'FOREIGN KEY (tenant_id, {column}) REFERENCES "{target}" (tenant_id, {target_column})'
                ),
                reverse_sql=f'ALTER TABLE "participant" DROP CONSTRAINT IF EXISTS participant_{column}_same_tenant',
            )
            for column, target, target_column in COMPOSITE_KEYS
        ],
        *[
            migrations.RunSQL(
                sql=f'ALTER TABLE "participant" ADD CONSTRAINT {name} CHECK ({condition})',
                reverse_sql=f'ALTER TABLE "participant" DROP CONSTRAINT IF EXISTS {name}',
            )
            for name, condition in CHECKS
        ],
        *rls_operations("participant"),
    ]
