# Generated by Django 6.1.1 on 2026-09-20 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import rls_operations

"""cases 0001 (chunk 5, CAS-01, WAT-04, WAT-05): one bank's case for one library
change, and that bank's own decision about a suggested obligation link. Both are tenant
tables: `tenant_id` on every row, row-level security enabled and forced, and the one
`tenant_isolation` policy whose USING and WITH CHECK are the session's own tenant, so
cw_app reads and writes nothing of another bank's and cannot bypass it (NFR-01, ADR 0022).

Not `mixed=True`: neither table ever holds a library row. A change is shared and a case
is not, which is the whole reason the case is here and not in the watch zone.

R1 columns only. Triage, dismissal, the assessment, actions, evidence, sign-off and the
close arrive with chunk 9, and so does the four-eyes check constraint, because what it
guards is the sign-off (CAS-06). INPUT_DELTAS §8 records every departure from the
designed `change_case`."""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0003_mixed_tables_write_their_own_zone'),
        ('library', '0006_problem_report_writes_its_own_zone'),
        ('shared', '0005_append_only_hatch_allowlist'),
        ('taxonomy', '0004_watched_market'),
        ('watch', '0001_watch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'new'), ('assigned', 'assigned'), ('assessing', 'assessing'), ('implementing', 'implementing'), ('signoff', 'signoff'), ('closed', 'closed'), ('dismissed', 'dismissed')], default='new', max_length=16)),
                ('urgency_confirmed', models.BooleanField(default=False)),
                ('footprint_match', models.BooleanField()),
                ('so_what_text', models.TextField(blank=True)),
                ('so_what_confirmed', models.BooleanField(default=False)),
                ('so_what_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('briefing_week', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='watch.regulatorychange')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user')),
                ('so_what_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('urgency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taxonomy.urgency')),
            ],
            options={
                'db_table': 'change_case',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseObligationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('accepted', 'accepted'), ('removed', 'removed')], max_length=16)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='library.obligation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_links', to='cases.changecase')),
            ],
            options={
                'db_table': 'case_obligation_link',
                'ordering': ['-decided_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='changecase',
            index=models.Index(fields=['tenant', 'status', 'urgency'], name='change_case_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='changecase',
            index=models.Index(condition=models.Q(('status__in', ['closed', 'dismissed']), _negated=True), fields=['tenant', 'owner'], name='change_case_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='changecase',
            constraint=models.UniqueConstraint(fields=('tenant', 'change'), name='change_case_one_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='changecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('so_what_confirmed', False), ('so_what_confirmed_at__isnull', True), ('so_what_confirmed_by__isnull', True)), models.Q(('so_what_confirmed', True), ('so_what_confirmed_at__isnull', False), ('so_what_confirmed_by__isnull', False)), _connector='OR'), name='change_case_so_what_confirmation_names_a_person'),
        ),
        migrations.AddConstraint(
            model_name='caseobligationlink',
            constraint=models.UniqueConstraint(fields=('tenant', 'case', 'obligation'), name='case_obligation_link_one_decision'),
        ),
        *rls_operations("change_case"),
        *rls_operations("case_obligation_link"),
    ]
