# Generated by Django 6.1.1 on 2026-09-25 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import append_only_trigger_operations, rls_operations

"""cases 0002 (chunk 9, `c9-case-models`; CAS-02, CAS-03, CAS-04, CAS-06, CAS-08): the case
workflow's columns on `change_case`, its three CHECKs (a dismissal names a reason, a worked
case has an owner, and four eyes on the sign-off), and three tenant tables — the impact
assessment, actions and the append-only transition ledger — each under enabled and forced
row-level security with the one `tenant_isolation` policy.

Every reference from these tables to a person is also a composite key on
`(tenant_id, user)` into `membership`, and every child's reference to its case a composite
key on `(tenant_id, case)` into `change_case`, which gains `UNIQUE (tenant_id, id)` for it
(INPUT_DELTAS §1, D-18). PostgreSQL checks foreign keys with row-level security bypassed, so
the single-column keys Django keeps would accept another bank's case or a person who is not
a member of this one; the composite key refuses both at the database. Not deferrable, so the
refusal comes at the statement that tried.

Not built here, each named in INPUT_DELTAS §18: `impact_assessment.contributors` (the case's
team participants replace it), the action's ticket columns (`c13-tickets-export`),
`change_case.triage_due_at` (`c10-workflow-policy`) and `change_case.owner_team`
(`c9-owner-team-and-reassign`)."""


def composite_key(table: str, column: str, target: str, target_column: str) -> migrations.RunSQL:
    """`(tenant_id, column)` must name a row of the same tenant in `target`."""
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT {name}',
    )


def member(table: str, column: str) -> migrations.RunSQL:
    return composite_key(table, column, "membership", "user_id")


def of_the_case(table: str) -> migrations.RunSQL:
    return composite_key(table, "case_id", "change_case", "id")


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_cases"),
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("shared", "0008_library_write_guard"),
        ("taxonomy", "0008_set_based_footprint"),
        ("watch", "0002_curation_confirmation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("due_date", models.DateField()),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "action",
                "ordering": ["due_date", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="CaseTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "new"),
                            ("assigned", "assigned"),
                            ("assessing", "assessing"),
                            ("implementing", "implementing"),
                            ("signoff", "signoff"),
                            ("closed", "closed"),
                            ("dismissed", "dismissed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("assigned", "assigned"),
                            ("assessing", "assessing"),
                            ("implementing", "implementing"),
                            ("signoff", "signoff"),
                            ("closed", "closed"),
                            ("dismissed", "dismissed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "db_table": "case_transition",
                "ordering": ["at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ImpactAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "applies",
                    models.CharField(
                        choices=[("yes", "yes"), ("partly", "partly"), ("no", "no")],
                        default="yes",
                        max_length=16,
                    ),
                ),
                ("why", models.TextField(blank=True)),
                ("what_must_change", models.TextField(blank=True)),
                ("internal_deadline", models.DateField(blank=True, null=True)),
                ("saved", models.BooleanField(default=False)),
                ("saved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "impact_assessment",
                "ordering": ["case", "id"],
            },
        ),
        migrations.AddField(
            model_name="changecase",
            name="close_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="taxonomy.closurereason",
            ),
        ),
        migrations.AddField(
            model_name="changecase",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changecase",
            name="closed_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="changecase",
            name="dismissed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changecase",
            name="dismissed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="changecase",
            name="dismissed_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="taxonomy.dismissalreason",
            ),
        ),
        migrations.AddField(
            model_name="changecase",
            name="signed_off_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="changecase",
            name="signoff_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changecase",
            name="signoff_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="changecase",
            name="sub_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="taxonomy.casesubstatus",
            ),
        ),
        migrations.AddField(
            model_name="changecase",
            name="triaged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changecase",
            name="triaged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="changecase",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="changecase",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="change_case_tenant_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="changecase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "dismissed"), _negated=True),
                    ("dismissed_reason__isnull", False),
                    _connector="OR",
                ),
                name="change_case_dismissal_needs_a_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="changecase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "status__in",
                            ["assigned", "assessing", "implementing", "signoff"],
                        ),
                        _negated=True,
                    ),
                    ("owner__isnull", False),
                    _connector="OR",
                ),
                name="change_case_worked_case_has_an_owner",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actions",
                to="cases.changecase",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="done_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="shared.tenant",
            ),
        ),
        migrations.AddField(
            model_name="casetransition",
            name="by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="casetransition",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cases.changecase",
            ),
        ),
        migrations.AddField(
            model_name="casetransition",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="shared.tenant",
            ),
        ),
        migrations.AddField(
            model_name="impactassessment",
            name="case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessment",
                to="cases.changecase",
            ),
        ),
        migrations.AddField(
            model_name="impactassessment",
            name="effort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="taxonomy.effortsize",
            ),
        ),
        migrations.AddField(
            model_name="impactassessment",
            name="saved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="impactassessment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="shared.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                condition=models.Q(
                    ("done_at__isnull", True), ("removed_at__isnull", True)
                ),
                fields=["tenant", "due_date"],
                name="action_open_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True),
                name="action_has_a_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("done_at__isnull", True), ("done_by__isnull", True)),
                    models.Q(("done_at__isnull", False), ("done_by__isnull", False)),
                    _connector="OR",
                ),
                name="action_done_names_a_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("removed_at__isnull", True), ("removed_by__isnull", True)
                    ),
                    models.Q(
                        ("removed_at__isnull", False), ("removed_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="action_removal_names_a_person",
            ),
        ),
        migrations.AddIndex(
            model_name="casetransition",
            index=models.Index(fields=["case", "at"], name="case_transition_idx"),
        ),
        migrations.AddConstraint(
            model_name="impactassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("saved", False),
                    models.Q(("why", ""), _negated=True),
                    _connector="OR",
                ),
                name="impact_assessment_saved_says_why",
            ),
        ),
        migrations.AddConstraint(
            model_name="impactassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("saved", False),
                        ("saved_at__isnull", True),
                        ("saved_by__isnull", True),
                    ),
                    models.Q(
                        ("saved", True),
                        ("saved_at__isnull", False),
                        ("saved_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="impact_assessment_saved_names_a_person",
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE change_case ADD CONSTRAINT change_case_four_eyes CHECK (signed_off_by_id IS NULL "
                "OR (signoff_requested_by_id IS NOT NULL AND signed_off_by_id <> signoff_requested_by_id))"
            ),
            reverse_sql="ALTER TABLE change_case DROP CONSTRAINT change_case_four_eyes",
        ),
        *rls_operations("impact_assessment"),
        *rls_operations("action"),
        *rls_operations("case_transition"),
        *append_only_trigger_operations("case_transition"),
        *[
            member("change_case", column)
            for column in (
                "owner_id",
                "so_what_confirmed_by_id",
                "triaged_by_id",
                "dismissed_by_id",
                "signoff_requested_by_id",
                "signed_off_by_id",
            )
        ],
        of_the_case("case_obligation_link"),
        member("case_obligation_link", "decided_by_id"),
        of_the_case("impact_assessment"),
        member("impact_assessment", "saved_by_id"),
        of_the_case("action"),
        *[member("action", column) for column in ("owner_id", "done_by_id", "created_by_id", "removed_by_id")],
        of_the_case("case_transition"),
        member("case_transition", "by_user_id"),
    ]
