# Generated by Django 6.1.1 on 2026-09-25 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import rls_operations

"""cases 0003 (chunk 9, `c9-case-models`; CAS-05): the evidence table, a tenant table under
enabled and forced row-level security. Its case and its uploader are composite keys on
`(tenant_id, …)`, as in cases 0002, so another bank's case or a non-member is refused at the
database. The case is required: evidence on a register entry is not built (INPUT_DELTAS §18).
A CHECK per kind means only a stored, hashed file carries a storage key, and a new row is
`pending` until the scan answers, so nothing unscanned is ever served."""


def composite_key(table: str, column: str, target: str, target_column: str) -> migrations.RunSQL:
    """`(tenant_id, column)` must name a row of the same tenant in `target`."""
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT {name}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_case_workflow"),
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("shared", "0008_library_write_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("file", "file"),
                            ("link", "link"),
                            ("reference", "reference"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.TextField()),
                ("storage_key", models.TextField(blank=True)),
                ("url", models.TextField(blank=True)),
                ("content_hash", models.CharField(blank=True, max_length=128)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scan_state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("clean", "clean"),
                            ("infected", "infected"),
                            ("error", "error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="cases.changecase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "evidence",
                "ordering": ["-uploaded_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="evidence_has_a_name",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "file"), _negated=True),
                            models.Q(
                                models.Q(("storage_key", ""), _negated=True),
                                models.Q(("content_hash", ""), _negated=True),
                                ("size_bytes__isnull", False),
                                models.Q(("mime_type", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="evidence_file_is_stored_and_hashed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "link"), _negated=True),
                            models.Q(
                                models.Q(("url", ""), _negated=True),
                                ("storage_key", ""),
                            ),
                            _connector="OR",
                        ),
                        name="evidence_link_has_a_url",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "reference"), _negated=True),
                            ("storage_key", ""),
                            _connector="OR",
                        ),
                        name="evidence_reference_has_no_file",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("scan_state", "pending"),
                            ("scanned_at__isnull", False),
                            _connector="OR",
                        ),
                        name="evidence_scan_names_a_time",
                    ),
                ],
            },
        ),
        *rls_operations("evidence"),
        composite_key("evidence", "case_id", "change_case", "id"),
        composite_key("evidence", "uploaded_by_id", "membership", "user_id"),
    ]
