# Generated by Django 6.1.1 on 2026-09-19 03:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


"""proposals 0001 (chunk 2, PRO-01, PRO-02): the proposal table with its queue index and
the four-eyes check constraint (reviewed_by <> proposed_by_user). A library-zone table:
no tenant column, so no policy."""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('vocabulary_create', 'vocabulary_create'), ('vocabulary_relabel', 'vocabulary_relabel'), ('vocabulary_retire', 'vocabulary_retire'), ('vocabulary_merge', 'vocabulary_merge'), ('vocabulary_restore', 'vocabulary_restore'), ('term_create', 'term_create'), ('term_update', 'term_update')], max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('change_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('field_sources', models.JSONField(blank=True, default=dict)),
                ('source_label', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('agent', 'agent'), ('user', 'user')], max_length=16)),
                ('agent_run_id', models.UUIDField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('approved', 'approved'), ('rejected', 'rejected'), ('superseded', 'superseded')], default='open', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_code', models.CharField(blank=True, max_length=64)),
                ('review_note', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_by_api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.apikey')),
                ('proposed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user')),
            ],
            options={
                'db_table': 'proposal',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='proposal_queue_idx')],
            },
        ),
        # Four eyes (PRO-02, AC-PRO2): the proposer never approves. Stated in SQL because
        # Django spells "not equal" as NOT (a = b AND a IS NOT NULL), and the four-eyes guard
        # reads the definition back from pg_constraint (apps/shared/tests_four_eyes.py).
        # An agent's proposal has no proposing user, so any reviewer may decide it.
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "proposal" ADD CONSTRAINT proposal_four_eyes CHECK ('
                "reviewed_by_id IS NULL OR proposed_by_user_id IS NULL OR reviewed_by_id <> proposed_by_user_id)"
            ),
            reverse_sql='ALTER TABLE "proposal" DROP CONSTRAINT IF EXISTS proposal_four_eyes',
        ),
    ]
