# Generated by Django 6.1.1 on 2026-09-19 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


"""proposals 0002 (chunk 4, PRO-01, PRO-02, PRO-03): the obligation proposal kind
`new_obligation_version`, the reviewer's corrected payload beside the proposed one, and
the tenant half of a proposal.

`proposal` stays a library-zone table with no tenant column: `proposed_in_tenant` is a
boolean saying only that a tenant member made it, and the tenant itself lives in
`proposal_tenant`, a tenant table with RLS enabled and forced like every other."""

from apps.shared.migration_helpers import rls_operations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("proposals", "0001_initial"),
        ("shared", "0002_tenant_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="corrected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="corrected_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="proposed_in_tenant",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="kind",
            field=models.CharField(
                choices=[
                    ("vocabulary_create", "vocabulary_create"),
                    ("vocabulary_relabel", "vocabulary_relabel"),
                    ("vocabulary_retire", "vocabulary_retire"),
                    ("vocabulary_merge", "vocabulary_merge"),
                    ("vocabulary_restore", "vocabulary_restore"),
                    ("term_create", "term_create"),
                    ("term_update", "term_update"),
                    ("new_obligation_version", "new_obligation_version"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="ProposalTenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_links",
                        to="proposals.proposal",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "proposal_tenant",
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("proposal", "tenant"), name="proposal_tenant_unique"
                    )
                ],
            },
        ),
        # Tenant table: RLS enabled and forced, tenant policy (playbook 14).
        *rls_operations("proposal_tenant"),
    ]
