# Generated by Django 6.1.1 on 2026-09-22

import django.db.models.deletion
from django.db import migrations, models


"""proposals 0003 (chunk4-T25, PRO-01, PRO-02, AC-PRO2, D-62, ADR 0054): the second
principal a proposal's reviewer may be is an independent agent, not only a person.

Adds `proposed_by_agent`, `reviewed_by_api_key` and `reviewed_by_agent`, copied from the
acting API key at the one write path because a check constraint cannot dereference a key,
and replaces `proposal_four_eyes` with a wider constraint refusing a row whose user, key
OR agent repeats on both sides, and a reviewing key that names no agent (two unbound
platform keys would otherwise both carry a NULL agent, and NULL <> NULL is unknown in
SQL, so the agent clause would pass on a missing value rather than on independence)."""


OLD_CONSTRAINT = (
    'ALTER TABLE "proposal" ADD CONSTRAINT proposal_four_eyes CHECK ('
    "reviewed_by_id IS NULL OR proposed_by_user_id IS NULL OR reviewed_by_id <> proposed_by_user_id)"
)
NEW_CONSTRAINT = (
    'ALTER TABLE "proposal" ADD CONSTRAINT proposal_four_eyes CHECK ('
    "(reviewed_by_id IS NULL OR proposed_by_user_id IS NULL OR reviewed_by_id <> proposed_by_user_id) "
    "AND (reviewed_by_api_key_id IS NULL OR proposed_by_api_key_id IS NULL OR reviewed_by_api_key_id <> proposed_by_api_key_id) "
    "AND (reviewed_by_agent_id IS NULL OR proposed_by_agent_id IS NULL OR reviewed_by_agent_id <> proposed_by_agent_id) "
    "AND (reviewed_by_api_key_id IS NULL OR reviewed_by_agent_id IS NOT NULL))"
)
DROP_CONSTRAINT = 'ALTER TABLE "proposal" DROP CONSTRAINT IF EXISTS proposal_four_eyes'


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0002_obligation_proposals"),
        ("identity", "0001_initial"),
        ("agents", "0002_library_rows_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="proposed_by_agent",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="agents.agent"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="reviewed_by_api_key",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="identity.apikey"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="reviewed_by_agent",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="agents.agent"),
        ),
        migrations.RunSQL(sql=DROP_CONSTRAINT, reverse_sql=OLD_CONSTRAINT),
        migrations.RunSQL(sql=NEW_CONSTRAINT, reverse_sql=DROP_CONSTRAINT),
    ]
