# Generated by Django 6.1.1 on 2026-09-23 16:11

from django.db import migrations, models


"""proposals 0004 (PRO-01, INV-01, INV-03): the kinds `new_instrument` and `new_obligation`,
which bring a new record into the library through the same door as every other change.
Only the column's choices move; no row changes."""


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0003_agent_reviewer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="kind",
            field=models.CharField(
                choices=[
                    ("vocabulary_create", "vocabulary_create"),
                    ("vocabulary_relabel", "vocabulary_relabel"),
                    ("vocabulary_retire", "vocabulary_retire"),
                    ("vocabulary_merge", "vocabulary_merge"),
                    ("vocabulary_restore", "vocabulary_restore"),
                    ("term_create", "term_create"),
                    ("term_update", "term_update"),
                    ("new_obligation_version", "new_obligation_version"),
                    ("new_instrument", "new_instrument"),
                    ("new_obligation", "new_obligation"),
                ],
                max_length=40,
            ),
        ),
    ]
