# Generated by Django 6.1.1 on 2026-09-23 21:42

from django.db import migrations, models


"""proposals 0006 (PRO-01, playbook 4.3, security-review-c4): a proposal's retry key is its
proposer's own, unique per person and per API key rather than across every caller, so
another bank or the platform's agent sending the same value files a proposal of its own and
is never answered, nor blocked by, someone else's. No row changes."""


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_agent_kind_review"),
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("proposals", "0005_provision_kinds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("idempotency_key__isnull", False),
                    ("proposed_by_user__isnull", False),
                ),
                fields=("proposed_by_user", "idempotency_key"),
                name="proposal_idempotency_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("idempotency_key__isnull", False),
                    ("proposed_by_api_key__isnull", False),
                ),
                fields=("proposed_by_api_key", "idempotency_key"),
                name="proposal_idempotency_per_key",
            ),
        ),
    ]
