# Generated by Django 6.1.1 on 2026-09-25 04:22

"""proposals 0010 (REG-07, PRO-01): the `new_recurring_duty` kind, a recurring duty's only
door into the library (library 0010). The choices change and nothing else: no column, no
row and no constraint moves."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0009_proposal_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="kind",
            field=models.CharField(
                choices=[
                    ("vocabulary_create", "vocabulary_create"),
                    ("vocabulary_relabel", "vocabulary_relabel"),
                    ("vocabulary_retire", "vocabulary_retire"),
                    ("vocabulary_merge", "vocabulary_merge"),
                    ("vocabulary_restore", "vocabulary_restore"),
                    ("term_create", "term_create"),
                    ("term_update", "term_update"),
                    ("new_obligation_version", "new_obligation_version"),
                    ("new_instrument", "new_instrument"),
                    ("new_obligation", "new_obligation"),
                    ("new_provision", "new_provision"),
                    ("new_provision_version", "new_provision_version"),
                    ("obligation_scope", "obligation_scope"),
                    ("new_recurring_duty", "new_recurring_duty"),
                ],
                max_length=40,
            ),
        ),
    ]
