# Generated by Django 6.1.1 on 2026-09-27 06:00

"""proposals 0011 (OWN-05, REG-05, D-99): the `new_control` kind, a control of a bank's own
obligation that its approval adds as a linked internal item of the control kind, in the
bank's zone. The choices change and nothing else: no column, no row and no constraint
moves."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0010_recurring_duty_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="kind",
            field=models.CharField(
                choices=[
                    ("vocabulary_create", "vocabulary_create"),
                    ("vocabulary_relabel", "vocabulary_relabel"),
                    ("vocabulary_retire", "vocabulary_retire"),
                    ("vocabulary_merge", "vocabulary_merge"),
                    ("vocabulary_restore", "vocabulary_restore"),
                    ("term_create", "term_create"),
                    ("term_update", "term_update"),
                    ("new_obligation_version", "new_obligation_version"),
                    ("new_instrument", "new_instrument"),
                    ("new_obligation", "new_obligation"),
                    ("new_provision", "new_provision"),
                    ("new_provision_version", "new_provision_version"),
                    ("obligation_scope", "obligation_scope"),
                    ("new_recurring_duty", "new_recurring_duty"),
                    ("new_control", "new_control"),
                ],
                max_length=40,
            ),
        ),
    ]
