#!/usr/bin/env python
"""Generate the fixed E2E passkeys once (playbook 8.3): one deterministic P-256 key pair
per seeded login with a passkey, derived from a fixed seed string so a re-run reproduces
the committed output byte for byte.

Writes:
- backend/apps/shared/e2e_passkeys.py: credential id and COSE public key (base64url) per
  login, which seed_e2e stores as the user's `webauthn_credential` row.
- frontend/tests/e2e/support/e2e-passkeys.generated.ts: the same credential id, the user
  handle (the user's id bytes) and the PKCS#8 private key plus SPKI public key, base64url
  DER as Playwright's `browserContext.credentials.create()` takes them.

Prints the gitleaks allowlist entries for the private keys (test fixtures, allowlisted by
exact literal with the reason "E2E virtual authenticator test keys, playbook 8.3").

Run from backend/: `./run.sh run python scripts/generate_e2e_passkeys.py`. Needs no
database. The private keys protect nothing: seed_e2e refuses to run on a deployed
environment and the public keys exist only in databases it filled.
"""

from __future__ import annotations

import base64
import hashlib
import sys
from pathlib import Path

import cbor2
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

BACKEND = Path(__file__).resolve().parent.parent
ROOT = BACKEND.parent
sys.path.insert(0, str(BACKEND))

from apps.shared.e2e_logins import SEED_LOGINS  # noqa: E402

PY_OUT = BACKEND / "apps" / "shared" / "e2e_passkeys.py"
TS_OUT = ROOT / "frontend" / "tests" / "e2e" / "support" / "e2e-passkeys.generated.ts"
SEED_STRING = "compliance-watch e2e passkey v1"
P256_ORDER = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551
E2E_AAGUID = "00000000-0000-0000-0000-00000000e2e0"


def b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def derive(email: str) -> ec.EllipticCurvePrivateKey:
    digest = hashlib.sha256(f"{SEED_STRING}:{email}".encode()).digest()
    scalar = int.from_bytes(digest, "big") % (P256_ORDER - 1) + 1
    return ec.derive_private_key(scalar, ec.SECP256R1())


def cose_public_key(key: ec.EllipticCurvePrivateKey) -> bytes:
    numbers = key.public_key().public_numbers()
    # COSE_Key: kty EC2 (1: 2), alg ES256 (3: -7), crv P-256 (-1: 1), x (-2), y (-3).
    return cbor2.dumps({1: 2, 3: -7, -1: 1, -2: numbers.x.to_bytes(32, "big"), -3: numbers.y.to_bytes(32, "big")})


def credential_id(email: str) -> bytes:
    return hashlib.sha256(f"{SEED_STRING} credential:{email}".encode()).digest()[:16]


def main() -> int:
    py_lines = [
        '"""Generated by backend/scripts/generate_e2e_passkeys.py. Do not edit: re-run the script.',
        "",
        "The COSE public keys (base64url) of the fixed E2E passkeys, one per seeded login that",
        "holds one (playbook 8.3). The matching private keys live in",
        "frontend/tests/e2e/support/e2e-passkeys.generated.ts and are allowlisted by exact literal",
        'in .gitleaks.toml."""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class E2EPasskey:",
        "    credential_id: str  # base64url",
        "    public_key_cose: str  # base64url COSE_Key",
        "    aaguid: str",
        "",
        "",
        f'E2E_AAGUID = "{E2E_AAGUID}"',
        "",
        "E2E_PASSKEYS: dict[str, E2EPasskey] = {",
    ]
    ts_lines = [
        "// Generated by backend/scripts/generate_e2e_passkeys.py. Do not edit: re-run the script.",
        "//",
        "// The fixed E2E passkeys (playbook 8.3): base64url PKCS#8 private keys and SPKI public",
        "// keys as Playwright's browserContext.credentials.create() takes them, keyed by login.",
        "// The backend seed stores the matching COSE public keys (apps/shared/e2e_passkeys.py).",
        "// Test fixtures only: seed_e2e refuses to run when deployed. Each private key is",
        "// allowlisted by exact literal in .gitleaks.toml.",
        "import type { SeededPasskey } from './passkeys';",
        "",
        "export const E2E_PASSKEYS_GENERATED: Readonly<Record<string, SeededPasskey>> = {",
    ]
    gitleaks: list[str] = []
    for login in SEED_LOGINS:
        if not login.has_passkey:
            continue
        key = derive(login.email)
        cred_id = b64url(credential_id(login.email))
        cose = b64url(cose_public_key(key))
        private_der = key.private_bytes(
            serialization.Encoding.DER, serialization.PrivateFormat.PKCS8, serialization.NoEncryption()
        )
        public_der = key.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
        private_b64 = b64url(private_der)
        public_b64 = b64url(public_der)
        user_handle = b64url(login.id.bytes)
        py_lines.append(f'    "{login.email}": E2EPasskey(credential_id="{cred_id}", public_key_cose="{cose}", aaguid=E2E_AAGUID),')
        ts_lines.append(f"  '{login.email}': {{")
        ts_lines.append(f"    id: '{cred_id}',")
        ts_lines.append(f"    userHandle: '{user_handle}',")
        ts_lines.append(f"    privateKey: '{private_b64}',")
        ts_lines.append(f"    publicKey: '{public_b64}',")
        ts_lines.append("  },")
        gitleaks.append(
            "\n".join(
                [
                    "[[allowlists]]",
                    f'description = "E2E passkey private key for the seeded user {login.email}: E2E virtual authenticator test keys, playbook 8.3. Test fixture only: its public key is written by seed_e2e, which refuses to run when deployed, and Playwright\'s virtual authenticator is the only consumer."',
                    'condition = "AND"',
                    f"regexes = ['''^{private_b64}$''']",
                    "paths = ['''^frontend/tests/e2e/support/e2e-passkeys\\.generated\\.ts$''']",
                ]
            )
        )
    py_lines.append("}")
    ts_lines.append("};")
    PY_OUT.write_text("\n".join(py_lines) + "\n", encoding="utf-8")
    TS_OUT.write_text("\n".join(ts_lines) + "\n", encoding="utf-8")
    print(f"wrote {PY_OUT.relative_to(ROOT).as_posix()} and {TS_OUT.relative_to(ROOT).as_posix()}")
    print("\n# .gitleaks.toml entries:\n")
    print("\n\n".join(gitleaks))
    return 0


if __name__ == "__main__":
    sys.exit(main())
