# Generated by Django 6.1.1 on 2026-09-19 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import POLICY_NAME, TENANT_EXPRESSION

"""agents 0001 (chunk 5, AGT-01, AGT-03): the agent definitions the reference seed loads
and the run rows everything an agent writes points at. `agent` is a library table with no
tenant_id, and its key never changes. `agent_run` is mixed: a platform run for the shared
library (tenant_id NULL) is visible to every tenant and a tenant's own run only to that
tenant.

Not `rls_operations("agent_run", mixed=True)`: its one FOR ALL policy checks writes with
the read rule, so a tenant could write, move and delete library runs and push its own run,
error text and all, into every other tenant's view. Here `tenant_isolation` lets a session
write only rows of its own zone (its tenant, or the library when no tenant is active), on a
key of that same zone, and `library_runs_visible` adds reading the library's runs.
Permissive policies OR together per command, so reads are mixed and writes are not.
"""

OWN_ZONE = f"agent_run.tenant_id IS NOT DISTINCT FROM {TENANT_EXPRESSION}"
# Foreign keys ignore row-level security, so without this a run could name another
# tenant's key. The key lookup itself runs under api_key's policy.
KEY_OF_THE_SAME_ZONE = (
    "EXISTS (SELECT 1 FROM api_key k WHERE k.id = agent_run.api_key_id "
    "AND k.tenant_id IS NOT DISTINCT FROM agent_run.tenant_id)"
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("shared", "0002_tenant_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=80, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("research", "research"),
                            ("backfill", "backfill"),
                            ("reverify", "reverify"),
                            ("watch", "watch"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=False)),
                ("current_version", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "agent",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("model", models.CharField(max_length=120)),
                ("pipeline_version", models.CharField(max_length=40)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("output_ref", models.CharField(blank=True, max_length=500)),
                ("error", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=200)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="agents.agent",
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_runs",
                        to="identity.apikey",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agent_run",
                "ordering": ["started_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-started_at"], name="agent_run_tenant_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key", ""), _negated=True),
                        fields=("api_key", "idempotency_key"),
                        name="agent_run_idempotency_unique",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "agent_run" ENABLE ROW LEVEL SECURITY',
            reverse_sql='ALTER TABLE "agent_run" DISABLE ROW LEVEL SECURITY',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "agent_run" FORCE ROW LEVEL SECURITY',
            reverse_sql='ALTER TABLE "agent_run" NO FORCE ROW LEVEL SECURITY',
        ),
        migrations.RunSQL(
            sql=(
                f'CREATE POLICY {POLICY_NAME} ON "agent_run" FOR ALL '
                f"USING ({OWN_ZONE}) WITH CHECK ({OWN_ZONE} AND {KEY_OF_THE_SAME_ZONE})"
            ),
            reverse_sql=f'DROP POLICY IF EXISTS {POLICY_NAME} ON "agent_run"',
        ),
        migrations.RunSQL(
            sql='CREATE POLICY library_runs_visible ON "agent_run" FOR SELECT USING (tenant_id IS NULL)',
            reverse_sql='DROP POLICY IF EXISTS library_runs_visible ON "agent_run"',
        ),
        # Stable keys never change (playbook 4.3); Agent.save says so first.
        migrations.RunSQL(
            sql="""
CREATE FUNCTION cw_agent_key_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.key IS DISTINCT FROM OLD.key THEN
        RAISE EXCEPTION 'agent.key never changes: % refused', NEW.key USING ERRCODE = 'raise_exception';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER agent_key_immutable BEFORE UPDATE ON "agent" FOR EACH ROW EXECUTE FUNCTION cw_agent_key_guard();
""",
            reverse_sql='DROP TRIGGER IF EXISTS agent_key_immutable ON "agent"; DROP FUNCTION IF EXISTS cw_agent_key_guard();',
        ),
    ]
