# Generated by Django 6.1.1 on 2026-09-23 06:51

"""agents 0003 (AGT-01, PRO-02, D-62, D-80): the agent kind `review`.

A definition of this kind proposes nothing and decides what another definition proposed,
as the independent second principal on the library's queue. The first is
`backend/agents/library-confirmer/v1/`, which the reference seed loads beside the sweeper.
The column's choices change and nothing else: `kind` is a tier-one kind in code
(apps/shared/kinds.py), so there is no database constraint to widen."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_library_rows_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='kind',
            field=models.CharField(choices=[('research', 'research'), ('backfill', 'backfill'), ('reverify', 'reverify'), ('watch', 'watch'), ('review', 'review')], max_length=16),
        ),
    ]
