# Generated by Django 6.1.1 on 2026-09-25 02:26

"""agents 0004 (chunk 11, AGT-03, AGT-06, ruling 1, D-54): published versions of bleqq's
agents, the columns that tell a platform agent from one a bank may add, and the run's
chunk 11 columns.

`agent_version` is a library table behind the inventory's doors (shared 0008), and
append-only: a run points at the version it opened with, so nothing of a published version
changes except `retired_at`, once. Written as its own function rather than the ledgers'
`cw_append_only_guard`, which refuses every update; the schema owner's maintenance hatch is
the same one (shared 0005).

`agent` gains `scope`, `tenant_configurable`, `runtime`, `default_cadence`, `writes_to` and
the two platform settings, and two CHECKs start the platform fence in the database: a
platform row is never tenant-configurable, and a tenant row carries no platform setting and
writes only its bank's zone (ADR 0053). agents 0001's key guard now refuses a changed scope
as well, so the fence of agents 0005 cannot be walked around by re-scoping a definition.

`agent_run` gains the version, the trigger, the requester, the runner's session, the
budget, the scope copy, the interrupt and the cost and token columns. A run the worker
opens has no key, so `api_key_id` becomes nullable under a CHECK (a key, or a trigger that
is not `api`), and the write policy is rewritten to ask for a key of the run's own zone only
when there is a key. The own-zone rule is unchanged: a keyless run still lands only in the
session's zone. `agent_version_id` is written when the run opens and a trigger refuses
changing it afterwards.
"""

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import (
    INVENTORY_DOORS,
    MAINTENANCE_SETTING,
    MIGRATOR_ROLE,
    POLICY_NAME,
    TENANT_EXPRESSION,
    append_only_trigger_operations,
    library_door_trigger_operations,
)

OWN_ZONE = f"agent_run.tenant_id IS NOT DISTINCT FROM {TENANT_EXPRESSION}"
# As agents 0001 wrote it: foreign keys ignore row-level security, so a run could otherwise
# name another zone's key. The lookup runs under api_key's own policy.
KEY_OF_THE_SAME_ZONE = (
    "EXISTS (SELECT 1 FROM api_key k WHERE k.id = agent_run.api_key_id "
    "AND k.tenant_id IS NOT DISTINCT FROM agent_run.tenant_id)"
)
KEYED_WRITE_RULE = f"({OWN_ZONE} AND {KEY_OF_THE_SAME_ZONE})"
# A keyless run is the worker's; it still writes only the session's own zone.
WRITE_RULE = f"({OWN_ZONE} AND (agent_run.api_key_id IS NULL OR {KEY_OF_THE_SAME_ZONE}))"
MAINTENANCE = f"current_setting('{MAINTENANCE_SETTING}', true) = 'on' AND session_user = '{MIGRATOR_ROLE}'"

VERSION_GUARD_SQL = f"""
CREATE FUNCTION cw_agent_version_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF {MAINTENANCE} THEN
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'agent_version is append-only: DELETE refused' USING ERRCODE = 'raise_exception';
    END IF;
    IF OLD.retired_at IS NOT NULL OR to_jsonb(NEW) - 'retired_at' IS DISTINCT FROM to_jsonb(OLD) - 'retired_at' THEN
        RAISE EXCEPTION 'agent_version is append-only: only retiring a version, once, is allowed'
            USING ERRCODE = 'raise_exception';
    END IF;
    RETURN NEW;
END;
$$;
"""

# agents 0001's guard, now also refusing a changed scope: one of bleqq's agents never becomes
# a bank's, and a bank's never becomes one of bleqq's under the rows that steer it.
AGENT_GUARD_SQL = """
CREATE OR REPLACE FUNCTION cw_agent_key_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.key IS DISTINCT FROM OLD.key THEN
        RAISE EXCEPTION 'agent.key never changes: % refused', NEW.key USING ERRCODE = 'raise_exception';
    END IF;
    IF NEW.scope IS DISTINCT FROM OLD.scope THEN
        RAISE EXCEPTION 'agent.scope never changes: % refused', NEW.key USING ERRCODE = 'raise_exception';
    END IF;
    RETURN NEW;
END;
$$;
"""
AGENT_GUARD_REVERSE_SQL = """
CREATE OR REPLACE FUNCTION cw_agent_key_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.key IS DISTINCT FROM OLD.key THEN
        RAISE EXCEPTION 'agent.key never changes: % refused', NEW.key USING ERRCODE = 'raise_exception';
    END IF;
    RETURN NEW;
END;
$$;
"""

RUN_VERSION_GUARD_SQL = """
CREATE FUNCTION cw_agent_run_version_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.agent_version_id IS DISTINCT FROM OLD.agent_version_id THEN
        RAISE EXCEPTION 'agent_run.agent_version_id is written when the run opens and never changes'
            USING ERRCODE = 'raise_exception';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER agent_run_version_written_once BEFORE UPDATE ON "agent_run"
    FOR EACH ROW EXECUTE FUNCTION cw_agent_run_version_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_agent_kind_review"),
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("shared", "0008_library_write_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_no", models.PositiveIntegerField()),
                ("model", models.CharField(max_length=120)),
                ("prompt_path", models.CharField(max_length=300)),
                ("tools", models.JSONField(blank=True, default=list)),
                ("change_note", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "agent_version",
                "ordering": ["agent", "-version_no"],
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="default_cadence",
            field=models.CharField(
                choices=[
                    ("daily", "daily"),
                    ("weekly", "weekly"),
                    ("monthly", "monthly"),
                    ("manual", "manual"),
                ],
                default="weekly",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="platform_monthly_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="platform_scope",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="runtime",
            field=models.CharField(
                choices=[
                    ("agent_sdk", "agent_sdk"),
                    ("managed_agents", "managed_agents"),
                    ("routine", "routine"),
                ],
                default="agent_sdk",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="scope",
            field=models.CharField(
                choices=[("platform", "platform"), ("tenant", "tenant")],
                default="platform",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="tenant_configurable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agent",
            name="writes_to",
            field=models.CharField(
                choices=[("library", "library"), ("tenant", "tenant")],
                default="library",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="budget_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="external_session_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="interrupted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="interrupted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="scope",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="tokens_in",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="tokens_out",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("schedule", "schedule"),
                    ("manual", "manual"),
                    ("request", "request"),
                    ("api", "api"),
                ],
                default="api",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="api_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agent_runs",
                to="identity.apikey",
            ),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scope", "platform"), ("tenant_configurable", True), _negated=True
                ),
                name="agent_platform_not_tenant_configurable",
            ),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "tenant"), _negated=True),
                    models.Q(
                        ("platform_monthly_budget__isnull", True),
                        ("platform_scope__isnull", True),
                        ("writes_to", "tenant"),
                    ),
                    _connector="OR",
                ),
                name="agent_tenant_carries_no_platform_settings",
            ),
        ),
        migrations.AddField(
            model_name="agentversion",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="agentversion",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="agent_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="agents.agentversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("api_key__isnull", False),
                    models.Q(("trigger", "api"), _negated=True),
                    _connector="OR",
                ),
                name="agent_run_api_run_has_a_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentversion",
            constraint=models.UniqueConstraint(
                fields=("agent", "version_no"), name="agent_version_unique"
            ),
        ),
        *library_door_trigger_operations("agent_version", INVENTORY_DOORS),
        migrations.RunSQL(sql=AGENT_GUARD_SQL, reverse_sql=AGENT_GUARD_REVERSE_SQL),
        migrations.RunSQL(sql=VERSION_GUARD_SQL, reverse_sql="DROP FUNCTION IF EXISTS cw_agent_version_guard();"),
        *append_only_trigger_operations("agent_version", function="cw_agent_version_guard"),
        migrations.RunSQL(
            sql=RUN_VERSION_GUARD_SQL,
            reverse_sql=(
                'DROP TRIGGER IF EXISTS agent_run_version_written_once ON "agent_run"; '
                "DROP FUNCTION IF EXISTS cw_agent_run_version_guard();"
            ),
        ),
        migrations.RunSQL(
            sql=f'ALTER POLICY {POLICY_NAME} ON "agent_run" USING ({OWN_ZONE}) WITH CHECK {WRITE_RULE}',
            reverse_sql=f'ALTER POLICY {POLICY_NAME} ON "agent_run" USING ({OWN_ZONE}) WITH CHECK {KEYED_WRITE_RULE}',
        ),
    ]
