# Generated by Django 6.1.1 on 2026-09-25 02:26

"""agents 0005 (chunk 11, AGT-04, AGT-05, rulings 1 and 3, ADR 0053): a bank's own agents,
its research requests and its one monthly cap, and the run's links to the first two.

`tenant_agent` and `tenant_agent_budget` hold one bank's rows and nothing else, under
forced row-level security. `research_request` is mixed like agent_run: a bank's request
lives in its zone, the console's `retag` (no tenant) in the library's, and each zone writes
only its own rows while a bank reads the library's too.

The fence a bank never crosses is in the database before any route: the trigger below
refuses a `tenant_agent` on a definition that is one of bleqq's (`scope = platform`) or
that is not tenant-configurable, whoever writes it or moves it to another definition, and
refuses a delete, because an agent
a bank stops is paused and never deleted. A definition's scope never changes (agents 0004), so a
row once admitted never ends up steering one of bleqq's agents. A definition the platform
stops offering (`tenant_configurable` false) keeps its rows, which a bank can still pause
or switch off; the scheduler reads the definition before it starts a run.
The schema owner's maintenance hatch lets a conscious fix, and tenant exit, through (shared
0005).

A foreign key ignores row-level security, so a bank's request or run could otherwise name
another bank's agent by its id. Both reach `tenant_agent` through a second foreign key on
(tenant_id, tenant_agent_id) as well, which holds wherever the row has a tenant; a CHECK on
each table already refuses a tenant agent on a row without one.
"""

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import MAINTENANCE_SETTING, MIGRATOR_ROLE, rls_operations

MAINTENANCE = f"current_setting('{MAINTENANCE_SETTING}', true) = 'on' AND session_user = '{MIGRATOR_ROLE}'"

SAME_TENANT_SQL = """
ALTER TABLE tenant_agent ADD CONSTRAINT tenant_agent_tenant_id_id_unique UNIQUE (tenant_id, id);
ALTER TABLE research_request ADD CONSTRAINT research_request_tenant_agent_same_tenant
    FOREIGN KEY (tenant_id, tenant_agent_id) REFERENCES tenant_agent (tenant_id, id);
ALTER TABLE agent_run ADD CONSTRAINT agent_run_tenant_agent_same_tenant
    FOREIGN KEY (tenant_id, tenant_agent_id) REFERENCES tenant_agent (tenant_id, id);
"""
SAME_TENANT_REVERSE_SQL = """
ALTER TABLE agent_run DROP CONSTRAINT IF EXISTS agent_run_tenant_agent_same_tenant;
ALTER TABLE research_request DROP CONSTRAINT IF EXISTS research_request_tenant_agent_same_tenant;
ALTER TABLE tenant_agent DROP CONSTRAINT IF EXISTS tenant_agent_tenant_id_id_unique;
"""

TENANT_AGENT_FENCE_SQL = f"""
CREATE FUNCTION cw_tenant_agent_fence() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF {MAINTENANCE} THEN RETURN OLD; END IF;
        RAISE EXCEPTION 'tenant_agent is paused, never deleted: DELETE refused' USING ERRCODE = 'raise_exception';
    END IF;
    IF (TG_OP = 'INSERT' OR NEW.agent_id IS DISTINCT FROM OLD.agent_id) AND NOT EXISTS (
        SELECT 1 FROM agent a WHERE a.id = NEW.agent_id AND a.scope = 'tenant' AND a.tenant_configurable
    ) THEN
        RAISE EXCEPTION 'tenant_agent refused: agent % is one of bleqq''s agents or not tenant-configurable (ADR 0053)',
            NEW.agent_id USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER tenant_agent_fence BEFORE INSERT OR UPDATE OR DELETE ON "tenant_agent"
    FOR EACH ROW EXECUTE FUNCTION cw_tenant_agent_fence();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_agent_versions"),
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("shared", "0008_library_write_guard"),
        ("watch", "0002_curation_confirmation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAgentBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("monthly_cap", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenant_agent_budget",
                "ordering": ["tenant"],
            },
        ),
        migrations.CreateModel(
            name="ResearchRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("run_now", "run_now"),
                            ("check_source", "check_source"),
                            ("check_url", "check_url"),
                            ("research_topic", "research_topic"),
                            ("retag", "retag"),
                        ],
                        max_length=16,
                    ),
                ),
                ("topic", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("done", "done"),
                            ("failed", "failed"),
                            ("rejected", "rejected"),
                            ("cancelled", "cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("result_summary", models.TextField(blank=True)),
                ("batch_proposal_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="watch.source",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "research_request",
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="agentrun",
            name="research_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="agents.researchrequest",
            ),
        ),
        migrations.CreateModel(
            name="TenantAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                            ("manual", "manual"),
                        ],
                        default="weekly",
                        max_length=16,
                    ),
                ),
                (
                    "run_weekday",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("run_hour", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.JSONField(blank=True, default=dict)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("pause_reason", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_agents",
                        to="agents.agent",
                    ),
                ),
                (
                    "paused_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_agent",
                "ordering": ["tenant", "agent"],
            },
        ),
        migrations.AddField(
            model_name="researchrequest",
            name="tenant_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="research_requests",
                to="agents.tenantagent",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="tenant_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="agents.tenantagent",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tenant_agent__isnull", True),
                    ("tenant__isnull", False),
                    _connector="OR",
                ),
                name="agent_run_tenant_agent_run_is_a_tenant_run",
            ),
        ),
        migrations.AddField(
            model_name="tenantagentbudget",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="shared.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantagentbudget",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantagent",
            index=models.Index(
                condition=models.Q(("enabled", True), ("paused_at__isnull", True)),
                fields=["next_run_at"],
                name="tenant_agent_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantagent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "agent"), name="tenant_agent_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantagent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("run_weekday__isnull", True),
                    models.Q(("run_weekday__gte", 1), ("run_weekday__lte", 7)),
                    _connector="OR",
                ),
                name="tenant_agent_run_weekday_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantagent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("run_hour__isnull", True), ("run_hour__lte", 23), _connector="OR"
                ),
                name="tenant_agent_run_hour_range",
            ),
        ),
        migrations.AddIndex(
            model_name="researchrequest",
            index=models.Index(
                fields=["tenant", "-created_at"], name="research_request_tenant_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "retag"),
                        ("tenant__isnull", True),
                        ("tenant_agent__isnull", True),
                    ),
                    models.Q(
                        models.Q(("kind", "retag"), _negated=True),
                        ("tenant__isnull", False),
                        ("tenant_agent__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="research_request_zone",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantagentbudget",
            constraint=models.UniqueConstraint(
                fields=("tenant",), name="tenant_agent_budget_one_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantagentbudget",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_cap__gte", 0)),
                name="tenant_agent_budget_not_negative",
            ),
        ),
        *rls_operations("tenant_agent"),
        *rls_operations("tenant_agent_budget"),
        *rls_operations("research_request", mixed=True),
        migrations.RunSQL(sql=SAME_TENANT_SQL, reverse_sql=SAME_TENANT_REVERSE_SQL),
        migrations.RunSQL(
            sql=TENANT_AGENT_FENCE_SQL,
            reverse_sql=(
                'DROP TRIGGER IF EXISTS tenant_agent_fence ON "tenant_agent"; '
                "DROP FUNCTION IF EXISTS cw_tenant_agent_fence();"
            ),
        ),
    ]
