# Generated by Django 6.1.1 on 2026-09-25 02:59

import django.db.models.deletion
import uuid
from django.db import migrations, models

"""agents 0006 (acc-foundation; ACC-01, ACC-02, D-70, ADR 0055): the agents a bank runs on
its own infrastructure, each registered as an agent access entry with the departments and
products that narrow it. Every table is under forced row-level security.

PostgreSQL checks a foreign key without row-level security, so every reference to a tenant
row is also a composite `(tenant_id, …)` key, as in tenants 0002: an entry's owning team,
its departments and products, and the people who created or revoked it (a key into
`membership (tenant_id, user_id)`) are always its own bank's. `agent_access` gains
`UNIQUE (tenant_id, id)` so its joins, and `api_key` in identity 0007, can point at it the
same way."""

from apps.shared.migration_helpers import rls_operations

TABLES = ("agent_access", "agent_access_department", "agent_access_product")

# (table, column, target table, target column)
COMPOSITE_KEYS = (
    ("agent_access", "owner_team_id", "team", "id"),
    ("agent_access", "created_by_id", "membership", "user_id"),
    ("agent_access", "revoked_by_id", "membership", "user_id"),
    ("agent_access_department", "agent_access_id", "agent_access", "id"),
    ("agent_access_department", "department_id", "org_unit", "id"),
    ("agent_access_product", "agent_access_id", "agent_access", "id"),
    ("agent_access_product", "product_id", "tenant_product", "id"),
)


def composite_key(table, column, target, target_column):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_tenant_agents"),
        ("identity", "0006_retire_applicability_request"),
        ("shared", "0008_library_write_guard"),
        ("taxonomy", "0009_register_lists"),
        ("tenants", "0002_organisation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("purpose", models.TextField()),
                ("tenant_reach", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "owner_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.team",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agent_access",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="AgentAccessDepartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="agents.agentaccess",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.orgunit",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agent_access_department",
                "ordering": ["agent_access", "department"],
            },
        ),
        migrations.CreateModel(
            name="AgentAccessProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="agents.agentaccess",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.tenantproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agent_access_product",
                "ordering": ["agent_access", "product"],
            },
        ),
        migrations.AddConstraint(
            model_name="agentaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("active", True),
                        ("revoked_at__isnull", True),
                        ("revoked_by__isnull", True),
                    ),
                    models.Q(("active", False), ("revoked_at__isnull", False)),
                    _connector="OR",
                ),
                name="agent_access_revoked_is_inactive",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentaccessdepartment",
            constraint=models.UniqueConstraint(
                fields=("agent_access", "department"),
                name="agent_access_department_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentaccessproduct",
            constraint=models.UniqueConstraint(
                fields=("agent_access", "product"), name="agent_access_product_unique"
            ),
        ),
        *[operation for table in TABLES for operation in rls_operations(table)],
        migrations.RunSQL(
            sql="ALTER TABLE agent_access ADD CONSTRAINT agent_access_tenant_id_id_unique UNIQUE (tenant_id, id)",
            reverse_sql="ALTER TABLE agent_access DROP CONSTRAINT IF EXISTS agent_access_tenant_id_id_unique",
        ),
        *[composite_key(*key) for key in COMPOSITE_KEYS],
    ]
