# Generated by Django 6.1.1 on 2026-09-25 02:59

"""agents 0006 (chunk 11, AGT-04, AGT-06, c11-runner-and-definitions): a run can end
`interrupted`, stopped from outside before it finished, as the runner seam reports it. A
choices change only: the column, its default and every stored row stay as they are.

Numbered 0006 on its own branch; the wave's integrator renumbers it behind agents 0006 and
0007 if those land first (R2_CROSS_CUTTING section b)."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_tenant_agents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "running"),
                    ("succeeded", "succeeded"),
                    ("failed", "failed"),
                    ("interrupted", "interrupted"),
                ],
                default="running",
                max_length=16,
            ),
        ),
    ]
