# Generated by Django 6.1.1 on 2026-09-27 05:36

"""agents 0008 (chunk 11, AGT-05, AGT-07, c11-research-requests): a research request keeps
what a `check_url` fetched, as text that is never rendered or followed, and the content
screen's flags on that text or on the topic. Two columns with empty defaults; every stored
row stays as it is."""

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_run_status_interrupted"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchrequest",
            name="fetched_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="researchrequest",
            name="risk_flags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=40), blank=True, default=list
            ),
        ),
    ]
