# Generated by Django 6.1.1 on 2026-09-27 06:41

"""agents 0009 (d89-agent-research; OWN-02, AGT-05, D-89, D-91, ADR 0059): an approved scope
item opens a research request of the new kind `scope_item` for the bank's own
scope-researcher. The request names its item, which is always the request's own bank's (a
composite `(tenant_id, scope_item_id)` key, as every tenant reference is), and an item is
researched once: a redelivered `scope_item.added` event opens nothing twice. Every stored
row is another kind with no item, so the checks hold for it as it is."""

import django.db.models.deletion
from django.db import migrations, models

SAME_TENANT_SQL = """
ALTER TABLE research_request ADD CONSTRAINT research_request_scope_item_same_tenant
    FOREIGN KEY (tenant_id, scope_item_id) REFERENCES scope_item (tenant_id, id);
"""
SAME_TENANT_REVERSE_SQL = "ALTER TABLE research_request DROP CONSTRAINT IF EXISTS research_request_scope_item_same_tenant;"


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_research_request_fetched"),
        ("identity", "0007_credential_kinds"),
        ("shared", "0010_jurisdiction_proposal_door"),
        ("taxonomy", "0012_scope_items"),
        ("watch", "0002_curation_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchrequest",
            name="scope_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="taxonomy.scopeitem",
            ),
        ),
        migrations.AlterField(
            model_name="researchrequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("run_now", "run_now"),
                    ("check_source", "check_source"),
                    ("check_url", "check_url"),
                    ("research_topic", "research_topic"),
                    ("retag", "retag"),
                    ("scope_item", "scope_item"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="researchrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "scope_item"), ("scope_item__isnull", False)),
                    models.Q(
                        models.Q(("kind", "scope_item"), _negated=True),
                        ("scope_item__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="research_request_scope_item_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_item__isnull", False)),
                fields=("scope_item",),
                name="research_request_one_per_scope_item",
            ),
        ),
        migrations.RunSQL(sql=SAME_TENANT_SQL, reverse_sql=SAME_TENANT_REVERSE_SQL),
    ]
