# Generated by Django 6.1.1 on 2026-09-21 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import rls_operations

"""governance 0001 (chunk 5, AUD-02, NFR-01, NFR-04): the log of what a model produced.

`ai_generation` is a mixed table: a row with no tenant is the library's — the "So what?"
drafted once per change — and a row with a tenant is that bank's own. `rls_operations(...,
mixed=True)` is the split shape H15 and H-C settled: one FOR ALL policy whose USING and
WITH CHECK are `tenant_id IS NOT DISTINCT FROM` the session's tenant, so a session writes
only its own zone, plus a second FOR SELECT policy on `tenant_id IS NULL` that adds the
library's rows to every bank's read. Permissive policies OR together per command, so reads
are mixed and writes are not: a bank session can read the library's draft and can neither
insert, rewrite, move nor delete one (ruling I).

Chunk 7's feedback columns are created here so chunk 7 adds no migration of its own."""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_library_rows_visible'),
        ('identity', '0004_login_event_feed_used'),
        ('shared', '0006_outboxcursor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('so_what', 'so_what'), ('change_summary', 'change_summary'), ('scope_suggestion', 'scope_suggestion'), ('link_suggestion', 'link_suggestion'), ('translation', 'translation'), ('answer', 'answer')], max_length=32)),
                ('subject_type', models.CharField(blank=True, max_length=32)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('model', models.CharField(max_length=200)),
                ('model_version', models.CharField(blank=True, max_length=120)),
                ('model_metadata_reported_by_agent', models.BooleanField(default=False)),
                ('prompt_template', models.CharField(blank=True, max_length=200)),
                ('prompt_hash', models.CharField(blank=True, max_length=128)),
                ('output', models.TextField(blank=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('confirmed', 'confirmed'), ('edited', 'edited'), ('rejected', 'rejected')], default='draft', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_minor', models.PositiveIntegerField(default=0)),
                ('feedback', models.CharField(blank=True, max_length=16)),
                ('feedback_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='agents.agentrun')),
                ('asker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'ai_generation',
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='ai_generation_subject_idx'), models.Index(fields=['tenant', '-created_at'], name='ai_generation_tenant_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True)), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='ai_generation_review_names_a_person')],
            },
        ),
        *rls_operations("ai_generation", mixed=True),
    ]
