# Generated by Django 6.1.1 on 2026-09-23 06:51

"""governance 0002 (AUD-02, PRO-02, D-80): the AI purpose `agent_review`.

A confirming agent's decision on another agent's work — approving, correcting or rejecting
a proposal, or confirming a watch item's curation — is a model call, so it is logged, and
under a purpose of its own rather than one of the drafting purposes, so the log can tell a
machine's decision from a machine's draft. Three things change:

- The column's choices. `purpose` is a tier-one kind in code (apps/shared/kinds.py), so
  there is no constraint on the value to widen and no row to rewrite.
- A check constraint: an `agent_review` row is always the agent's own report, names the
  run it was made in and names the record it decided, so no caller can log a decision
  nobody can trace.
- The library read policy. Every bank reads the rows with no tenant, and a decision is
  one of them, because the deciding agent's run is the platform's. But it is about the
  proposal queue, where a bank sees only what it filed itself, so `library_rows_visible`
  now leaves `agent_review` out. The platform still reads it through `tenant_isolation`,
  the own-zone rule of a session with no tenant. The write rule does not change."""

from django.db import migrations, models

from apps.shared.migration_helpers import LIBRARY_READ_POLICY

_TABLE = "ai_generation"
_LIBRARY_ROWS = "tenant_id IS NULL"
_LIBRARY_ROWS_BUT_DECISIONS = "tenant_id IS NULL AND purpose <> 'agent_review'"


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_ai_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigeneration',
            name='purpose',
            field=models.CharField(choices=[('so_what', 'so_what'), ('change_summary', 'change_summary'), ('scope_suggestion', 'scope_suggestion'), ('link_suggestion', 'link_suggestion'), ('translation', 'translation'), ('answer', 'answer'), ('agent_review', 'agent_review')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='aigeneration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose', 'agent_review'), _negated=True), models.Q(('agent_run__isnull', False), ('model_metadata_reported_by_agent', True), ('subject_id__isnull', False), models.Q(('subject_type', ''), _negated=True)), _connector='OR'), name='ai_generation_agent_review_names_its_run'),
        ),
        migrations.RunSQL(
            sql=f'ALTER POLICY {LIBRARY_READ_POLICY} ON "{_TABLE}" USING ({_LIBRARY_ROWS_BUT_DECISIONS})',
            reverse_sql=f'ALTER POLICY {LIBRARY_READ_POLICY} ON "{_TABLE}" USING ({_LIBRARY_ROWS})',
        ),
    ]
