# Generated by Django 6.1.1 on 2026-09-23 06:51

"""governance 0002 (AUD-02, PRO-02, D-80): the AI purpose `agent_review`.

A confirming agent's decision on another agent's work — approving, correcting or rejecting
a proposal, or confirming a watch item's curation — is a model call, so it is logged, and
under a purpose of its own rather than one of the drafting purposes, so the log can tell a
machine's decision from a machine's draft. The column's choices change and nothing else:
`purpose` is a tier-one kind in code (apps/shared/kinds.py), so there is no database
constraint to widen and no row to rewrite."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_ai_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigeneration',
            name='purpose',
            field=models.CharField(choices=[('so_what', 'so_what'), ('change_summary', 'change_summary'), ('scope_suggestion', 'scope_suggestion'), ('link_suggestion', 'link_suggestion'), ('translation', 'translation'), ('answer', 'answer'), ('agent_review', 'agent_review')], max_length=32),
        ),
    ]
