# Generated by Django 6.1.1 on 2026-09-25 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models

"""governance 0004 (acc-scope-and-reach; ACC-08, D-72, ADR 0057): tenant reach, the switch that
lets a bank's own register reach the agents it runs itself, and the requests that turn it on.
Both tables are under forced row-level security.

`tenant_reach_request_four_eyes` makes the second person the database's rule, in the words
the four-eyes guard reads back: the person deciding a request is never the one who made it.
PostgreSQL checks a foreign key without row-level security, so every reference to a person
is also a composite key into `membership (tenant_id, user_id)`, and the state row's approval
a composite key into its own bank's requests: a row can never name another bank's person or
request."""

from apps.shared.migration_helpers import rls_operations

TABLES = ("tenant_reach_request", "tenant_reach")

# (table, column, target table, target column)
COMPOSITE_KEYS = (
    ("tenant_reach_request", "requested_by_id", "membership", "user_id"),
    ("tenant_reach_request", "decided_by_id", "membership", "user_id"),
    ("tenant_reach", "changed_by_id", "membership", "user_id"),
    ("tenant_reach", "request_id", "tenant_reach_request", "id"),
)


def composite_key(table, column, target, target_column):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0003_ai_generation_stop_reason"),
        ("identity", "0007_credential_kinds"),
        ("shared", "0008_library_write_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantReachRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("withdrawn", "withdrawn"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_reach_request",
                "ordering": ["-requested_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TenantReach",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="governance.tenantreachrequest",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_reach",
                "ordering": ["tenant"],
            },
        ),
        migrations.AddConstraint(
            model_name="tenantreachrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("tenant",),
                name="tenant_reach_request_one_pending",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantreachrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("decided_at__isnull", True), ("decided_by__isnull", True)
                    ),
                    models.Q(
                        ("decided_at__isnull", False), ("decided_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="tenant_reach_request_decision_names_a_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantreach",
            constraint=models.UniqueConstraint(
                fields=("tenant",), name="tenant_reach_one_row"
            ),
        ),
        *[operation for table in TABLES for operation in rls_operations(table)],
        migrations.RunSQL(
            sql=(
                "ALTER TABLE tenant_reach_request ADD CONSTRAINT tenant_reach_request_four_eyes "
                "CHECK (decided_by_id IS NULL OR decided_by_id <> requested_by_id)"
            ),
            reverse_sql="ALTER TABLE tenant_reach_request DROP CONSTRAINT IF EXISTS tenant_reach_request_four_eyes",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE tenant_reach_request ADD CONSTRAINT tenant_reach_request_tenant_id_id_unique UNIQUE (tenant_id, id)",
            reverse_sql="ALTER TABLE tenant_reach_request DROP CONSTRAINT IF EXISTS tenant_reach_request_tenant_id_id_unique",
        ),
        *[composite_key(*key) for key in COMPOSITE_KEYS],
    ]
