# Generated by Django 6.1.1 on 2026-09-25 10:38

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models

"""governance 0005 (acc-entries-and-log; ACC-08): the access log of the agents a bank runs
itself, one row per request an agent access credential makes. A tenant table under forced
row-level security, append-only by the shared trigger, so a row is written once and never
changed; only the D-53 purge deletes one, whole, as the schema owner.

PostgreSQL checks a foreign key without row-level security, so the entry and the person are
also composite `(tenant_id, …)` keys: a row can never name another bank's entry or person.
The credential is `api_key`, a mixed table with no `UNIQUE (tenant_id, id)`; the row is
written only from the credential the request resolved, in that credential's own bank."""

from apps.shared.migration_helpers import append_only_trigger_operations, rls_operations

# (table, column, target table, target column)
COMPOSITE_KEYS = (
    ("agent_access_call", "agent_access_id", "agent_access", "id"),
    ("agent_access_call", "acting_user_id", "membership", "user_id"),
)


def composite_key(table, column, target, target_column):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_agent_access"),
        ("governance", "0004_tenant_reach"),
        ("identity", "0007_credential_kinds"),
        ("shared", "0009_tenant_workflow_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAccessCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tool", models.CharField(max_length=120)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("record_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        blank=True,
                        default=list,
                    ),
                ),
                ("scope_narrowed", models.BooleanField(default=False)),
                ("scope_terms", models.JSONField(blank=True, default=dict)),
                ("duration_ms", models.PositiveIntegerField()),
                ("status", models.PositiveSmallIntegerField()),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "acting_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "agent_access",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="agents.agentaccess",
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.apikey",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agent_access_call",
                "ordering": ["-at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "agent_access", "-at"],
                        name="agent_access_call_entry_idx",
                    )
                ],
            },
        ),
        *rls_operations("agent_access_call"),
        *append_only_trigger_operations("agent_access_call"),
        *[composite_key(*key) for key in COMPOSITE_KEYS],
    ]
