# Generated by Django 6.1.1 on 2026-09-27 05:55

"""governance 0006 (ACC-06, ACC-09): the AI purpose `what_applies`.

The summary bleqq's model drafts above what applies to a bank's own agent is a model call,
so it is logged under a purpose of its own. `purpose` is a tier-one kind in code
(apps/shared/kinds.py), so only the column's choices change: no constraint to widen, no
row to rewrite, and the read policy is untouched, because the row is the bank's own."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0005_agent_access_call"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aigeneration",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("so_what", "so_what"),
                    ("change_summary", "change_summary"),
                    ("scope_suggestion", "scope_suggestion"),
                    ("link_suggestion", "link_suggestion"),
                    ("translation", "translation"),
                    ("answer", "answer"),
                    ("agent_review", "agent_review"),
                    ("what_applies", "what_applies"),
                ],
                max_length=32,
            ),
        ),
    ]
