# Generated by Django 6.1.1 on 2026-09-25 02:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

"""register 0001 (chunk 8; REG-01, REG-02, REG-04, TEN-03): the register entry, its scope rows
per legal entity and the append-only assessment history, every table under forced RLS.

PostgreSQL checks a foreign key without row-level security, so every reference to a tenant
row is also a composite `(tenant_id, …)` key: to `UNIQUE (tenant_id, id)` on the tables here
and on the two tenant lists these rows name first (`compliance_status`, `risk_rating`), and to
`membership_tenant_user_unique` for a person, which makes every person named a member of the
same bank. There is no applicability request: one person sets applicability (D-75)."""

from apps.shared.migration_helpers import append_only_trigger_operations, rls_operations

TABLES = ("tenant_obligation", "tenant_obligation_scope", "compliance_assessment")

# Targets of a composite key: this migration's own, and the two tenant lists that gain the
# pair here because a register row is their first tenant-checked reader.
TENANT_ID_UNIQUE = ("tenant_obligation", "tenant_obligation_scope", "compliance_status", "risk_rating")

# (table, column, target table, target column)
COMPOSITE_KEYS = (
    ("tenant_obligation", "applicability_decided_by_id", "membership", "user_id"),
    ("tenant_obligation", "compliance_status_id", "compliance_status", "id"),
    ("tenant_obligation", "risk_rating_id", "risk_rating", "id"),
    ("tenant_obligation", "first_line_owner_id", "membership", "user_id"),
    ("tenant_obligation", "compliance_contact_id", "membership", "user_id"),
    ("tenant_obligation", "owner_team_id", "team", "id"),
    ("tenant_obligation_scope", "tenant_obligation_id", "tenant_obligation", "id"),
    ("tenant_obligation_scope", "org_unit_id", "org_unit", "id"),
    ("tenant_obligation_scope", "product_id", "tenant_product", "id"),
    ("tenant_obligation_scope", "applicability_decided_by_id", "membership", "user_id"),
    ("tenant_obligation_scope", "compliance_status_id", "compliance_status", "id"),
    ("tenant_obligation_scope", "risk_rating_id", "risk_rating", "id"),
    ("tenant_obligation_scope", "owner_id", "membership", "user_id"),
    ("tenant_obligation_scope", "owner_team_id", "team", "id"),
    ("compliance_assessment", "tenant_obligation_id", "tenant_obligation", "id"),
    ("compliance_assessment", "scope_id", "tenant_obligation_scope", "id"),
    ("compliance_assessment", "status_id", "compliance_status", "id"),
    ("compliance_assessment", "risk_rating_id", "risk_rating", "id"),
    ("compliance_assessment", "assessed_by_id", "membership", "user_id"),
)


def tenant_id_unique(table):
    name = f"{table}_tenant_id_id_unique"
    return migrations.RunSQL(
        sql=f'ALTER TABLE "{table}" ADD CONSTRAINT {name} UNIQUE (tenant_id, id)',
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


def composite_key(table, column, target, target_column):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("library", "0009_problem_report_closure"),
        ("shared", "0008_library_write_guard"),
        ("taxonomy", "0009_register_lists"),
        ("tenants", "0002_organisation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantObligation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "applicability",
                    models.CharField(
                        choices=[
                            ("applies", "applies"),
                            ("does_not_apply", "does_not_apply"),
                            ("not_assessed", "not_assessed"),
                        ],
                        default="not_assessed",
                        max_length=16,
                    ),
                ),
                ("applicability_reason", models.TextField(blank=True)),
                (
                    "applicability_decided_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("status_note", models.TextField(blank=True)),
                ("process", models.CharField(blank=True, max_length=200)),
                ("system", models.CharField(blank=True, max_length=200)),
                ("evidence_location", models.CharField(blank=True, max_length=500)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicability_decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "compliance_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "compliance_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.compliancestatus",
                    ),
                ),
                (
                    "first_line_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="library.obligation",
                    ),
                ),
                (
                    "owner_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.team",
                    ),
                ),
                (
                    "risk_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.riskrating",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_obligation",
                "ordering": ["obligation_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="TenantObligationScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "applicability",
                    models.CharField(
                        choices=[
                            ("applies", "applies"),
                            ("does_not_apply", "does_not_apply"),
                            ("not_assessed", "not_assessed"),
                        ],
                        default="not_assessed",
                        max_length=16,
                    ),
                ),
                ("applicability_reason", models.TextField(blank=True)),
                (
                    "applicability_decided_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("status_note", models.TextField(blank=True)),
                ("process", models.CharField(blank=True, max_length=200)),
                ("system", models.CharField(blank=True, max_length=200)),
                ("evidence_location", models.CharField(blank=True, max_length=500)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicability_decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "compliance_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.compliancestatus",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.orgunit",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "owner_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.team",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.tenantproduct",
                    ),
                ),
                (
                    "risk_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.riskrating",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "tenant_obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scopes",
                        to="register.tenantobligation",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_obligation_scope",
                "ordering": ["tenant_obligation_id", "org_unit_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("self_assessment", "self_assessment"),
                            ("second_line_review", "second_line_review"),
                            ("internal_audit", "internal_audit"),
                            ("external_audit", "external_audit"),
                            ("regulator", "regulator"),
                        ],
                        default="self_assessment",
                        max_length=24,
                    ),
                ),
                ("rationale", models.TextField()),
                ("next_review_date", models.DateField(blank=True, null=True)),
                (
                    "assessed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "assessed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "risk_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.riskrating",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.compliancestatus",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "tenant_obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="register.tenantobligation",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="register.tenantobligationscope",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_assessment",
                "ordering": ["assessed_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="tenantobligation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "obligation"), name="tenant_obligation_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantobligationscope",
            constraint=models.UniqueConstraint(
                fields=("tenant_obligation", "org_unit", "product"),
                name="tenant_obligation_scope_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantobligationscope",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("owner__isnull", True),
                    ("owner_team__isnull", True),
                    _connector="OR",
                ),
                name="tenant_obligation_scope_one_owner_kind",
            ),
        ),
        *[operation for table in TABLES for operation in rls_operations(table)],
        *[tenant_id_unique(table) for table in TENANT_ID_UNIQUE],
        *[composite_key(*key) for key in COMPOSITE_KEYS],
        *append_only_trigger_operations("compliance_assessment"),
    ]
