# Generated by Django 6.1.1 on 2026-09-25 02:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

"""register 0002 (chunk 8; REG-03, REG-04, REG-05, TEN-03): gaps, how we read this rule, and
the links to the bank's internal items, every table under forced RLS and every reference to
a tenant row also a composite `(tenant_id, …)` key, as in register 0001.

Risk acceptance is behind four eyes: `gap_four_eyes` keeps the person who accepts apart from
the person who asked, and `gap_acceptance_complete` makes an acceptance name its reason and
its requester. A gap's status is the tenant's own row, whose fixed category a CHECK cannot
read, so a trigger keeps a gap out of a `risk_accepted` status until it has been accepted."""

from apps.shared.migration_helpers import rls_operations

TABLES = ("gap", "interpretation", "internal_link")

# The gap's three lists gain the pair here, as their first tenant-checked reader.
TENANT_ID_UNIQUE = ("gap_status", "gap_source", "risk_acceptance_reason")

# (table, column, target table, target column)
COMPOSITE_KEYS = (
    ("gap", "tenant_obligation_id", "tenant_obligation", "id"),
    ("gap", "org_unit_id", "org_unit", "id"),
    ("gap", "severity_id", "risk_rating", "id"),
    ("gap", "source_id", "gap_source", "id"),
    ("gap", "status_id", "gap_status", "id"),
    ("gap", "identified_by_id", "membership", "user_id"),
    ("gap", "owner_id", "membership", "user_id"),
    ("gap", "owner_team_id", "team", "id"),
    ("gap", "acceptance_reason_id", "risk_acceptance_reason", "id"),
    ("gap", "acceptance_requested_by_id", "membership", "user_id"),
    ("gap", "accepted_by_id", "membership", "user_id"),
    ("gap", "closed_by_id", "membership", "user_id"),
    ("interpretation", "tenant_obligation_id", "tenant_obligation", "id"),
    ("interpretation", "author_id", "membership", "user_id"),
    ("internal_link", "tenant_obligation_id", "tenant_obligation", "id"),
    ("internal_link", "internal_item_id", "internal_item", "id"),
    ("internal_link", "created_by_id", "membership", "user_id"),
    ("internal_link", "removed_by_id", "membership", "user_id"),
)


def tenant_id_unique(table):
    name = f"{table}_tenant_id_id_unique"
    return migrations.RunSQL(
        sql=f'ALTER TABLE "{table}" ADD CONSTRAINT {name} UNIQUE (tenant_id, id)',
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


def composite_key(table, column, target, target_column):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


FOUR_EYES_SQL = (
    'ALTER TABLE "gap" ADD CONSTRAINT gap_four_eyes '
    "CHECK (accepted_by_id IS NULL OR accepted_by_id <> acceptance_requested_by_id)"
)

ACCEPTED_GUARD_SQL = """
CREATE FUNCTION cw_gap_accepted_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.accepted_by_id IS NULL AND EXISTS (
        SELECT 1 FROM gap_status s WHERE s.id = NEW.status_id AND s.kind = 'risk_accepted'
    ) THEN
        RAISE EXCEPTION 'gap: a risk_accepted status needs an acceptance by a second person'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER gap_accepted_guard BEFORE INSERT OR UPDATE OF status_id, accepted_by_id ON gap
    FOR EACH ROW EXECUTE FUNCTION cw_gap_accepted_guard();
"""
ACCEPTED_GUARD_REVERSE_SQL = """
DROP TRIGGER IF EXISTS gap_accepted_guard ON gap;
DROP FUNCTION IF EXISTS cw_gap_accepted_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("register", "0001_register"),
        ("shared", "0008_library_write_guard"),
        ("taxonomy", "0009_register_lists"),
        ("tenants", "0002_organisation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "identified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("remediation", models.TextField(blank=True)),
                ("acceptance_note", models.TextField(blank=True)),
                (
                    "acceptance_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "acceptance_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.riskacceptancereason",
                    ),
                ),
                (
                    "acceptance_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "identified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.orgunit",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "owner_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.team",
                    ),
                ),
                (
                    "severity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.riskrating",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.gapsource",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.gapstatus",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "tenant_obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gaps",
                        to="register.tenantobligation",
                    ),
                ),
            ],
            options={
                "db_table": "gap",
                "ordering": ["identified_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("accepted_by__isnull", True),
                            models.Q(
                                ("acceptance_reason__isnull", False),
                                ("acceptance_requested_by__isnull", False),
                                ("accepted_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="gap_acceptance_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("owner__isnull", True),
                            ("owner_team__isnull", True),
                            _connector="OR",
                        ),
                        name="gap_one_owner_kind",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InternalLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("external_ref", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "internal_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.internalitem",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "tenant_obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="register.tenantobligation",
                    ),
                ),
            ],
            options={
                "db_table": "internal_link",
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=("tenant_obligation", "internal_item"),
                        name="internal_link_live_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Interpretation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "tenant_obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interpretations",
                        to="register.tenantobligation",
                    ),
                ),
            ],
            options={
                "db_table": "interpretation",
                "ordering": ["tenant_obligation_id", "version_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_obligation", "version_number"),
                        name="interpretation_version_unique",
                    )
                ],
            },
        ),
        *[operation for table in TABLES for operation in rls_operations(table)],
        *[tenant_id_unique(table) for table in TENANT_ID_UNIQUE],
        *[composite_key(*key) for key in COMPOSITE_KEYS],
        migrations.RunSQL(sql=FOUR_EYES_SQL, reverse_sql='ALTER TABLE "gap" DROP CONSTRAINT IF EXISTS gap_four_eyes'),
        migrations.RunSQL(sql=ACCEPTED_GUARD_SQL, reverse_sql=ACCEPTED_GUARD_REVERSE_SQL),
    ]
