# Generated by Django 6.1.1 on 2026-09-25 03:32

import django.db.models.deletion
import uuid
from django.db import migrations, models

"""register 0003 (chunk 8; REG-08, D-41): the Statement of Applicability's units, one row per
clause or control a legal entity lists under its conformance scope row, in the bank's own
words, and a gap's optional unit. Under forced RLS like every register table, every
reference to a tenant row also a composite `(tenant_id, …)` key, as in register 0001 and
0002. One live unit per scope row and reference; a removed unit frees its reference."""

from apps.shared.migration_helpers import rls_operations

# (table, column, target table, target column)
COMPOSITE_KEYS = (
    ("soa_unit", "scope_id", "tenant_obligation_scope", "id"),
    ("soa_unit", "applicability_decided_by_id", "membership", "user_id"),
    ("soa_unit", "compliance_status_id", "compliance_status", "id"),
    ("soa_unit", "removed_by_id", "membership", "user_id"),
    ("gap", "unit_id", "soa_unit", "id"),
)


def composite_key(table, column, target, target_column):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("register", "0002_gaps_history_links"),
        ("shared", "0008_library_write_guard"),
        ("taxonomy", "0009_register_lists"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoaUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=300)),
                (
                    "applicability",
                    models.CharField(
                        choices=[
                            ("applies", "applies"),
                            ("does_not_apply", "does_not_apply"),
                            ("not_assessed", "not_assessed"),
                        ],
                        default="not_assessed",
                        max_length=16,
                    ),
                ),
                ("applicability_reason", models.TextField(blank=True)),
                (
                    "applicability_decided_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("status_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicability_decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "compliance_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.compliancestatus",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="register.tenantobligationscope",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "soa_unit",
                "ordering": ["reference", "id"],
            },
        ),
        migrations.AddField(
            model_name="gap",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gaps",
                to="register.soaunit",
            ),
        ),
        migrations.AddConstraint(
            model_name="soaunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed_at__isnull", True)),
                fields=("scope", "reference"),
                name="soa_unit_live_reference_unique",
            ),
        ),
        *rls_operations("soa_unit"),
        migrations.RunSQL(
            sql='ALTER TABLE "soa_unit" ADD CONSTRAINT soa_unit_tenant_id_id_unique UNIQUE (tenant_id, id)',
            reverse_sql='ALTER TABLE "soa_unit" DROP CONSTRAINT IF EXISTS soa_unit_tenant_id_id_unique',
        ),
        *[composite_key(*key) for key in COMPOSITE_KEYS],
    ]
