# Generated by Django 6.1.1 on 2026-09-25 03:58

import django.db.models.deletion
import uuid
from django.db import migrations, models

"""register 0004 (chunk 8; REG-07): the dated occurrences of a library recurring duty in one
bank's calendar. Under forced RLS like every register table, every reference to a tenant row
also a composite `(tenant_id, …)` key, as in register 0001 to 0003. One row per duty, bank,
entity and due date, the bank-wide row's null entity counted as a value."""

from apps.shared.migration_helpers import rls_operations

# (table, column, target table, target column)
COMPOSITE_KEYS = (
    ("duty_occurrence", "tenant_obligation_id", "tenant_obligation", "id"),
    ("duty_occurrence", "org_unit_id", "org_unit", "id"),
    ("duty_occurrence", "owner_id", "membership", "user_id"),
    ("duty_occurrence", "owner_team_id", "team", "id"),
    ("duty_occurrence", "completed_by_id", "membership", "user_id"),
)


def composite_key(table, column, target, target_column):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0006_retire_applicability_request"),
        ("library", "0010_recurring_duty"),
        ("register", "0003_soa_unit"),
        ("shared", "0008_library_write_guard"),
        ("taxonomy", "0009_register_lists"),
        ("tenants", "0002_organisation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "upcoming"),
                            ("in_progress", "in_progress"),
                            ("done", "done"),
                            ("missed", "missed"),
                            ("not_applicable", "not_applicable"),
                        ],
                        default="upcoming",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.orgunit",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "owner_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.team",
                    ),
                ),
                (
                    "recurring_duty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="library.recurringduty",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "tenant_obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duty_occurrences",
                        to="register.tenantobligation",
                    ),
                ),
            ],
            options={
                "db_table": "duty_occurrence",
                "ordering": ["due_date", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recurring_duty", "tenant", "org_unit", "due_date"),
                        name="duty_occurrence_unique",
                        nulls_distinct=False,
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("owner__isnull", True),
                            ("owner_team__isnull", True),
                            _connector="OR",
                        ),
                        name="duty_occurrence_one_owner_kind",
                    ),
                ],
            },
        ),
        *rls_operations("duty_occurrence"),
        *[composite_key(*key) for key in COMPOSITE_KEYS],
    ]
