"""Generated by backend/scripts/generate_e2e_passkeys.py. Do not edit: re-run the script.

The COSE public keys (base64url) of the fixed E2E passkeys, one per seeded login that
holds one (playbook 8.3). The matching private keys live in
frontend/tests/e2e/support/e2e-passkeys.generated.ts and are allowlisted by exact literal
in .gitleaks.toml."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class E2EPasskey:
    credential_id: str  # base64url
    public_key_cose: str  # base64url COSE_Key
    aaguid: str


E2E_AAGUID = "00000000-0000-0000-0000-00000000e2e0"

E2E_PASSKEYS: dict[str, E2EPasskey] = {
    "admin@example-bank.test": E2EPasskey(credential_id="aoYU46mIvLGeCPfaxcWt_Q", public_key_cose="pQECAyYgASFYIFH9y-rK6MuubLVZXlDImwA-2FWWZ1qSOikfVdHKvlUjIlgg0bhI6bBEYPCiuwliKZVEta3LgqO9pVZgtKpXuJ-0Q0k", aaguid=E2E_AAGUID),
    "compliance_officer@example-bank.test": E2EPasskey(credential_id="5VALUKwRM4xyVhxMBDDM3A", public_key_cose="pQECAyYgASFYIN807qWH554uyiFUEL5z7DsWRABfFzD-EIiteyGi_tEGIlggPFwKcnYEJQyjr6y6RaeSzTIbJcfuUbGJzt86TsEWZzI", aaguid=E2E_AAGUID),
    "owner@example-bank.test": E2EPasskey(credential_id="-Pc96Z2oAMkG5syQ0Nk8LQ", public_key_cose="pQECAyYgASFYIJ26LxcAbxKqBppAe-olYo3uMmlZ_FFBJf9YCfLlYgpGIlgg2epkAuczNZWOHkdII2N6tRMZQ6A-XpEP1TMX4sxXEBw", aaguid=E2E_AAGUID),
    "approver@example-bank.test": E2EPasskey(credential_id="c1XBkdNXBEp4MLW0vnQy4A", public_key_cose="pQECAyYgASFYIARat9-i4Q9MVcZgMw0JgeG5hGfvyCmXaxs9oMKWdLNPIlggdXwqgmhBAD8Vz6n95NGdkMNYboBBLknD6fqcLmKNZE8", aaguid=E2E_AAGUID),
    "contributor@example-bank.test": E2EPasskey(credential_id="CHyt_Y_Aoq4AynRQhsx6ow", public_key_cose="pQECAyYgASFYIL1NDPWC-EavopZXtWOOwozHqE3Z6g2fftYPh1vLEXvFIlggEirt9SVn4AQyjlnzRn0N9_15HRwgucSUl7Xsj2QbdbY", aaguid=E2E_AAGUID),
    "reader@example-bank.test": E2EPasskey(credential_id="U9pvZLK2YTiPyLeaB2dX_Q", public_key_cose="pQECAyYgASFYIA6YR9kO7Dl3b5pKTM9Vw7DvZP2_AGR6YNbMHNwM94DIIlggFab0Pk5it5oM6GThT-img4afevSZ5cdjOPFtU8krwqA", aaguid=E2E_AAGUID),
    "auditor@example-bank.test": E2EPasskey(credential_id="-Tv7tW2xD0wBygtNqVDZeg", public_key_cose="pQECAyYgASFYIBQfri6uo8XTqXSa8SMmo9Tw8hh88-RGB5VEgD3MP6DQIlggfGbrlHZcXblMgvLozFM4p6VrGEeKXv44RbOareBp26M", aaguid=E2E_AAGUID),
    "admin@second-bank.test": E2EPasskey(credential_id="6ixzLJ3lCZYiFbn-3WWcXw", public_key_cose="pQECAyYgASFYIIZ7TvVS2ZT9fgYoGX1K_HiDlOMV9QWqzu80uLGsH0IQIlggvQr7lIQmJBodlnvxT9pInPtkyugG6J6uWcAdDO67aBQ", aaguid=E2E_AAGUID),
    "editor@bleqq.test": E2EPasskey(credential_id="kJMr_cyOaavja6riiD2TYg", public_key_cose="pQECAyYgASFYIIMZWg5ykm-qMw9R2qDN_GRV54zk8858wq9k9T48rpNrIlggu3OyOVPVaa5lwhPjgo0-adSG2q4DPIqiwMXpdhsfxYE", aaguid=E2E_AAGUID),
    "platform@bleqq.test": E2EPasskey(credential_id="UgJgCKWhb2hDQVUoH3sU7Q", public_key_cose="pQECAyYgASFYIAYBpYLUE31r9lYJoIlM44qR1PQcYSkJ_vI0qeaq8q46Ilgg0Oc1dN0Qf-6mzsfE1erNSKVAtjYsO63L5792ZWHLn9o", aaguid=E2E_AAGUID),
    "reissue@example-bank.test": E2EPasskey(credential_id="PVfR3rFiqBKfLK3MSSSFFQ", public_key_cose="pQECAyYgASFYIP-C8EcCKVIOyt6O4OlQMHgHNrHeSDbW4ZUfXKS_ea8YIlggUHG2grAcGgIN7F5IrO_gm2PZnkePc3gIDmC-L2MoGio", aaguid=E2E_AAGUID),
    "editor2@bleqq.test": E2EPasskey(credential_id="suqmTkUo_TtcyQzOTs0MFg", public_key_cose="pQECAyYgASFYIGnvriTFg5RjG-o-ngyFgjsrCYFqIllPLCnOkV-n7nciIlggp-_-35VGX7hrSDy6vs79WZVCvxyBf9IRekhfocljwtY", aaguid=E2E_AAGUID),
    "agent-keys@bleqq.test": E2EPasskey(credential_id="RUlGV1nowK17BmGcPQ7zbQ", public_key_cose="pQECAyYgASFYIJb6zYxQJ3MD6TPpue_LRFO5VbnqBmxsKHjfwxc9iPO6IlggYr5FqbJyanDkQqIR5EUlpSCIqEkg9l_dE2OEfQXwmWo", aaguid=E2E_AAGUID),
    "reader-sv@example-bank.test": E2EPasskey(credential_id="Z6-QX06Ma-mkrsHpz1QBQg", public_key_cose="pQECAyYgASFYIBE2OjZKXyrGd5phiNsGkwt-yXTWixWrSzvGQOGjh9P4Ilgg4BVFHfb-b7xW09RMGUnMPnzKbIevigg7M6sHgkcO1J8", aaguid=E2E_AAGUID),
}
