// Generated by backend/scripts/generate_e2e_passkeys.py. Do not edit: re-run the script.
//
// The fixed E2E passkeys (playbook 8.3): base64url PKCS#8 private keys and SPKI public
// keys as Playwright's browserContext.credentials.create() takes them, keyed by login.
// The backend seed stores the matching COSE public keys (apps/shared/e2e_passkeys.py).
// Test fixtures only: seed_e2e refuses to run when deployed. Each private key is
// allowlisted by exact literal in .gitleaks.toml.
import type { SeededPasskey } from './passkeys';

export const E2E_PASSKEYS_GENERATED: Readonly<Record<string, SeededPasskey>> = {
  'admin@example-bank.test': {
    id: 'aoYU46mIvLGeCPfaxcWt_Q',
    userHandle: 'AAAAAAAAQACAAAAAAAABAQ',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgwOXtRsOam-awksPOdixUx3mKCB-c1kNC1DV73DXgGZShRANCAARR_cvqyujLrmy1WV5QyJsAPthVlmdakjopH1XRyr5VI9G4SOmwRGDworsJYimVRLWty4KjvaVWYLSqV7iftENJ',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUf3L6sroy65stVleUMibAD7YVZZnWpI6KR9V0cq-VSPRuEjpsERg8KK7CWIplUS1rcuCo72lVmC0qle4n7RDSQ',
  },
  'compliance_officer@example-bank.test': {
    id: '5VALUKwRM4xyVhxMBDDM3A',
    userHandle: 'AAAAAAAAQACAAAAAAAABAg',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgkkdGOWECYtJ5UtwBvAmrqV7HAMCpT_HvgxhKtJ089jWhRANCAATfNO6lh-eeLsohVBC-c-w7FkQAXxcw_hCIrXshov7RBjxcCnJ2BCUMo6-sukWnks0yGyXH7lGxic7fOk7BFmcy',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3zTupYfnni7KIVQQvnPsOxZEAF8XMP4QiK17IaL-0QY8XApydgQlDKOvrLpFp5LNMhslx-5RsYnO3zpOwRZnMg',
  },
  'owner@example-bank.test': {
    id: '-Pc96Z2oAMkG5syQ0Nk8LQ',
    userHandle: 'AAAAAAAAQACAAAAAAAABAw',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg-KwLHf9aDrgqqBndJnIVFm_l1jetttFpGIF186vW0lShRANCAASdui8XAG8SqgaaQHvqJWKN7jJpWfxRQSX_WAny5WIKRtnqZALnMzWVjh5HSCNjerUTGUOgPl6RD9UzF-LMVxAc',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnbovFwBvEqoGmkB76iVije4yaVn8UUEl_1gJ8uViCkbZ6mQC5zM1lY4eR0gjY3q1ExlDoD5ekQ_VMxfizFcQHA',
  },
  'approver@example-bank.test': {
    id: 'c1XBkdNXBEp4MLW0vnQy4A',
    userHandle: 'AAAAAAAAQACAAAAAAAABBA',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgC-KOt1u05th6Oaw2y3p4VDUtxLbRC8m3cZfSBW58uz2hRANCAAQEWrffouEPTFXGYDMNCYHhuYRn78gpl2sbPaDClnSzT3V8KoJoQQA_Fc-p_eTRnZDDWG6AQS5Jw-n6nC5ijWRP',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBFq336LhD0xVxmAzDQmB4bmEZ-_IKZdrGz2gwpZ0s091fCqCaEEAPxXPqf3k0Z2Qw1hugEEuScPp-pwuYo1kTw',
  },
  'contributor@example-bank.test': {
    id: 'CHyt_Y_Aoq4AynRQhsx6ow',
    userHandle: 'AAAAAAAAQACAAAAAAAABBQ',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgp3RVKKpdnTc53TeF8praXkJGc5vAuyCqYapZeXgvxzuhRANCAAS9TQz1gvhGr6KWV7VjjsKMx6hN2eoNn37WD4dbyxF7xRIq7fUlZ-AEMo5Z80Z9Dff9eR0cILnElJe17I9kG3W2',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvU0M9YL4Rq-ille1Y47CjMeoTdnqDZ9-1g-HW8sRe8USKu31JWfgBDKOWfNGfQ33_XkdHCC5xJSXteyPZBt1tg',
  },
  'reader@example-bank.test': {
    id: 'U9pvZLK2YTiPyLeaB2dX_Q',
    userHandle: 'AAAAAAAAQACAAAAAAAABBg',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgC8TmF9-dtktw3YQ8N0-0NUSZScUJFnesYsquGbMPQRehRANCAAQOmEfZDuw5d2-aSkzPVcOw72T9vwBkemDWzBzcDPeAyBWm9D5OYreaDOhk4U_opoOGn3r0meXHYzjxbVPJK8Kg',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDphH2Q7sOXdvmkpMz1XDsO9k_b8AZHpg1swc3Az3gMgVpvQ-TmK3mgzoZOFP6KaDhp969Jnlx2M48W1TySvCoA',
  },
  'auditor@example-bank.test': {
    id: '-Tv7tW2xD0wBygtNqVDZeg',
    userHandle: 'AAAAAAAAQACAAAAAAAABBw',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg9HYaoOVGjWANtfEnVAnpBlA1R3v1J2gP7PiFguTBBYyhRANCAAQUH64urqPF06l0mvEjJqPU8PIYfPPkRgeVRIA9zD-g0Hxm65R2XF25TILy6MxTOKelaxhHil7-OEWzmq3gaduj',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFB-uLq6jxdOpdJrxIyaj1PDyGHzz5EYHlUSAPcw_oNB8ZuuUdlxduUyC8ujMUzinpWsYR4pe_jhFs5qt4Gnbow',
  },
  'admin@second-bank.test': {
    id: '6ixzLJ3lCZYiFbn-3WWcXw',
    userHandle: 'AAAAAAAAQACAAAAAAAABCQ',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgfnSWCPJYn9IR4glPGte2rmJQY-Ttp-70dWwkw0fgXNKhRANCAASGe071UtmU_X4GKBl9Svx4g5TjFfUFqs7vNLixrB9CEL0K-5SEJiQaHZZ78U_aSJz7ZMroBuierlnAHQzuu2gU',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhntO9VLZlP1-BigZfUr8eIOU4xX1BarO7zS4sawfQhC9CvuUhCYkGh2We_FP2kic-2TK6Abonq5ZwB0M7rtoFA',
  },
  'editor@bleqq.test': {
    id: 'kJMr_cyOaavja6riiD2TYg',
    userHandle: 'AAAAAAAAQACAAAAAAAABCg',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg2iMmka55U76NP_3sWuzBTv0SdbvCERSuznYxgUfwLyShRANCAASDGVoOcpJvqjMPUdqgzfxkVeeM5PPOfMKvZPU-PK6Ta7tzsjlT1WmuZcIT44KNPmnUhtquAzyKosDF6XYbH8WB',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgxlaDnKSb6ozD1HaoM38ZFXnjOTzznzCr2T1Pjyuk2u7c7I5U9VprmXCE-OCjT5p1IbargM8iqLAxel2Gx_FgQ',
  },
  'platform@bleqq.test': {
    id: 'UgJgCKWhb2hDQVUoH3sU7Q',
    userHandle: 'AAAAAAAAQACAAAAAAAABCw',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgwFqgo3UDzv12TzIMFRrjde2J172T-hOBD-7uYo-zMbahRANCAAQGAaWC1BN9a_ZWCaCJTOOKkdT0HGEpCf7yNKnmqvKuOtDnNXTdEH_ups7HxNXqzUilQLY2LDuty-e_dmVhy5_a',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBgGlgtQTfWv2VgmgiUzjipHU9BxhKQn-8jSp5qryrjrQ5zV03RB_7qbOx8TV6s1IpUC2Niw7rcvnv3ZlYcuf2g',
  },
  'reissue@example-bank.test': {
    id: 'PVfR3rFiqBKfLK3MSSSFFQ',
    userHandle: 'AAAAAAAAQACAAAAAAAABDA',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgStUqENR4fhKyntTv_MNTC_vy28Ughi8rvzaD8UpCGnChRANCAAT_gvBHAilSDsrejuDpUDB4Bzax3kg21uGVH1ykv3mvGFBxtoKwHBoCDexeSKzv4Jtj2Z5Hj3N4CA5gvi9jKBoq',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE_4LwRwIpUg7K3o7g6VAweAc2sd5INtbhlR9cpL95rxhQcbaCsBwaAg3sXkis7-CbY9meR49zeAgOYL4vYygaKg',
  },
  'editor2@bleqq.test': {
    id: 'suqmTkUo_TtcyQzOTs0MFg',
    userHandle: 'AAAAAAAAQACAAAAAAAABDQ',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg7NiZmIqngk7iNinf-X95Jzumu9zU92SgwtIRkGbO8UqhRANCAARp764kxYOUYxvqPp4MhYI7KwmBaiJZTywpzpFfp-53Iqfv_t-VRl-4a0g8ur7O_VmVQr8cgX_SEXpIX6HJY8LW',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEae-uJMWDlGMb6j6eDIWCOysJgWoiWU8sKc6RX6fudyKn7_7flUZfuGtIPLq-zv1ZlUK_HIF_0hF6SF-hyWPC1g',
  },
  'agent-keys@bleqq.test': {
    id: 'RUlGV1nowK17BmGcPQ7zbQ',
    userHandle: 'AAAAAAAAQACAAAAAAAABDg',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgwbTLS-9PzTOq23KMLT4eYl1zAntZX1i2ZGyI7dZzLBmhRANCAASW-s2MUCdzA-kz6bnvy0RTuVW56gZsbCh438MXPYjzumK-Ramycmpw5EKiEeRFJaUgiKhJIPZf3RNjhH0F8Jlq',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElvrNjFAncwPpM-m578tEU7lVueoGbGwoeN_DFz2I87pivkWpsnJqcORCohHkRSWlIIioSSD2X90TY4R9BfCZag',
  },
  'reader-sv@example-bank.test': {
    id: 'Z6-QX06Ma-mkrsHpz1QBQg',
    userHandle: 'AAAAAAAAQACAAAAAAAABDw',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgXjQWZqtyaBvdSauPw7EQXwcL7Pzux4BT7PXI5mTmUHyhRANCAAQRNjo2Sl8qxneaYYjbBpMLfsl01osVq0s7xkDho4fT-OAVRR32_m-8VtPUTBlJzD58ymyHr4oIOzOrB4JHDtSf',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEETY6NkpfKsZ3mmGI2waTC37JdNaLFatLO8ZA4aOH0_jgFUUd9v5vvFbT1EwZScw-fMpsh6-KCDszqweCRw7Unw',
  },
};
