// Generated by backend/scripts/generate_e2e_passkeys.py. Do not edit: re-run the script.
//
// The fixed E2E passkeys (playbook 8.3): base64url PKCS#8 private keys and SPKI public
// keys as Playwright's browserContext.credentials.create() takes them, keyed by login.
// The backend seed stores the matching COSE public keys (apps/shared/e2e_passkeys.py).
// Test fixtures only: seed_e2e refuses to run when deployed. Each private key is
// allowlisted by exact literal in .gitleaks.toml.
import type { SeededPasskey } from './passkeys';

export const E2E_PASSKEYS_GENERATED: Readonly<Record<string, SeededPasskey>> = {
  'admin@example-bank.test': {
    id: 'aoYU46mIvLGeCPfaxcWt_Q',
    userHandle: 'AAAAAAAAQACAAAAAAAABAQ',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgwOXtRsOam-awksPOdixUx3mKCB-c1kNC1DV73DXgGZShRANCAARR_cvqyujLrmy1WV5QyJsAPthVlmdakjopH1XRyr5VI9G4SOmwRGDworsJYimVRLWty4KjvaVWYLSqV7iftENJ',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUf3L6sroy65stVleUMibAD7YVZZnWpI6KR9V0cq-VSPRuEjpsERg8KK7CWIplUS1rcuCo72lVmC0qle4n7RDSQ',
  },
  'compliance_officer@example-bank.test': {
    id: '5VALUKwRM4xyVhxMBDDM3A',
    userHandle: 'AAAAAAAAQACAAAAAAAABAg',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgkkdGOWECYtJ5UtwBvAmrqV7HAMCpT_HvgxhKtJ089jWhRANCAATfNO6lh-eeLsohVBC-c-w7FkQAXxcw_hCIrXshov7RBjxcCnJ2BCUMo6-sukWnks0yGyXH7lGxic7fOk7BFmcy',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3zTupYfnni7KIVQQvnPsOxZEAF8XMP4QiK17IaL-0QY8XApydgQlDKOvrLpFp5LNMhslx-5RsYnO3zpOwRZnMg',
  },
  'owner@example-bank.test': {
    id: '-Pc96Z2oAMkG5syQ0Nk8LQ',
    userHandle: 'AAAAAAAAQACAAAAAAAABAw',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg-KwLHf9aDrgqqBndJnIVFm_l1jetttFpGIF186vW0lShRANCAASdui8XAG8SqgaaQHvqJWKN7jJpWfxRQSX_WAny5WIKRtnqZALnMzWVjh5HSCNjerUTGUOgPl6RD9UzF-LMVxAc',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnbovFwBvEqoGmkB76iVije4yaVn8UUEl_1gJ8uViCkbZ6mQC5zM1lY4eR0gjY3q1ExlDoD5ekQ_VMxfizFcQHA',
  },
  'approver@example-bank.test': {
    id: 'c1XBkdNXBEp4MLW0vnQy4A',
    userHandle: 'AAAAAAAAQACAAAAAAAABBA',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgC-KOt1u05th6Oaw2y3p4VDUtxLbRC8m3cZfSBW58uz2hRANCAAQEWrffouEPTFXGYDMNCYHhuYRn78gpl2sbPaDClnSzT3V8KoJoQQA_Fc-p_eTRnZDDWG6AQS5Jw-n6nC5ijWRP',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBFq336LhD0xVxmAzDQmB4bmEZ-_IKZdrGz2gwpZ0s091fCqCaEEAPxXPqf3k0Z2Qw1hugEEuScPp-pwuYo1kTw',
  },
  'contributor@example-bank.test': {
    id: 'CHyt_Y_Aoq4AynRQhsx6ow',
    userHandle: 'AAAAAAAAQACAAAAAAAABBQ',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgp3RVKKpdnTc53TeF8praXkJGc5vAuyCqYapZeXgvxzuhRANCAAS9TQz1gvhGr6KWV7VjjsKMx6hN2eoNn37WD4dbyxF7xRIq7fUlZ-AEMo5Z80Z9Dff9eR0cILnElJe17I9kG3W2',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvU0M9YL4Rq-ille1Y47CjMeoTdnqDZ9-1g-HW8sRe8USKu31JWfgBDKOWfNGfQ33_XkdHCC5xJSXteyPZBt1tg',
  },
  'reader@example-bank.test': {
    id: 'U9pvZLK2YTiPyLeaB2dX_Q',
    userHandle: 'AAAAAAAAQACAAAAAAAABBg',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgC8TmF9-dtktw3YQ8N0-0NUSZScUJFnesYsquGbMPQRehRANCAAQOmEfZDuw5d2-aSkzPVcOw72T9vwBkemDWzBzcDPeAyBWm9D5OYreaDOhk4U_opoOGn3r0meXHYzjxbVPJK8Kg',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDphH2Q7sOXdvmkpMz1XDsO9k_b8AZHpg1swc3Az3gMgVpvQ-TmK3mgzoZOFP6KaDhp969Jnlx2M48W1TySvCoA',
  },
  'auditor@example-bank.test': {
    id: '-Tv7tW2xD0wBygtNqVDZeg',
    userHandle: 'AAAAAAAAQACAAAAAAAABBw',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg9HYaoOVGjWANtfEnVAnpBlA1R3v1J2gP7PiFguTBBYyhRANCAAQUH64urqPF06l0mvEjJqPU8PIYfPPkRgeVRIA9zD-g0Hxm65R2XF25TILy6MxTOKelaxhHil7-OEWzmq3gaduj',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFB-uLq6jxdOpdJrxIyaj1PDyGHzz5EYHlUSAPcw_oNB8ZuuUdlxduUyC8ujMUzinpWsYR4pe_jhFs5qt4Gnbow',
  },
  'admin@second-bank.test': {
    id: '6ixzLJ3lCZYiFbn-3WWcXw',
    userHandle: 'AAAAAAAAQACAAAAAAAABCQ',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgfnSWCPJYn9IR4glPGte2rmJQY-Ttp-70dWwkw0fgXNKhRANCAASGe071UtmU_X4GKBl9Svx4g5TjFfUFqs7vNLixrB9CEL0K-5SEJiQaHZZ78U_aSJz7ZMroBuierlnAHQzuu2gU',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhntO9VLZlP1-BigZfUr8eIOU4xX1BarO7zS4sawfQhC9CvuUhCYkGh2We_FP2kic-2TK6Abonq5ZwB0M7rtoFA',
  },
  'editor@bleqq.test': {
    id: 'kJMr_cyOaavja6riiD2TYg',
    userHandle: 'AAAAAAAAQACAAAAAAAABCg',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg2iMmka55U76NP_3sWuzBTv0SdbvCERSuznYxgUfwLyShRANCAASDGVoOcpJvqjMPUdqgzfxkVeeM5PPOfMKvZPU-PK6Ta7tzsjlT1WmuZcIT44KNPmnUhtquAzyKosDF6XYbH8WB',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgxlaDnKSb6ozD1HaoM38ZFXnjOTzznzCr2T1Pjyuk2u7c7I5U9VprmXCE-OCjT5p1IbargM8iqLAxel2Gx_FgQ',
  },
  'platform@bleqq.test': {
    id: 'UgJgCKWhb2hDQVUoH3sU7Q',
    userHandle: 'AAAAAAAAQACAAAAAAAABCw',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgwFqgo3UDzv12TzIMFRrjde2J172T-hOBD-7uYo-zMbahRANCAAQGAaWC1BN9a_ZWCaCJTOOKkdT0HGEpCf7yNKnmqvKuOtDnNXTdEH_ups7HxNXqzUilQLY2LDuty-e_dmVhy5_a',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBgGlgtQTfWv2VgmgiUzjipHU9BxhKQn-8jSp5qryrjrQ5zV03RB_7qbOx8TV6s1IpUC2Niw7rcvnv3ZlYcuf2g',
  },
  'reissue@example-bank.test': {
    id: 'PVfR3rFiqBKfLK3MSSSFFQ',
    userHandle: 'AAAAAAAAQACAAAAAAAABDA',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgStUqENR4fhKyntTv_MNTC_vy28Ughi8rvzaD8UpCGnChRANCAAT_gvBHAilSDsrejuDpUDB4Bzax3kg21uGVH1ykv3mvGFBxtoKwHBoCDexeSKzv4Jtj2Z5Hj3N4CA5gvi9jKBoq',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE_4LwRwIpUg7K3o7g6VAweAc2sd5INtbhlR9cpL95rxhQcbaCsBwaAg3sXkis7-CbY9meR49zeAgOYL4vYygaKg',
  },
  'editor2@bleqq.test': {
    id: 'suqmTkUo_TtcyQzOTs0MFg',
    userHandle: 'AAAAAAAAQACAAAAAAAABDQ',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg7NiZmIqngk7iNinf-X95Jzumu9zU92SgwtIRkGbO8UqhRANCAARp764kxYOUYxvqPp4MhYI7KwmBaiJZTywpzpFfp-53Iqfv_t-VRl-4a0g8ur7O_VmVQr8cgX_SEXpIX6HJY8LW',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEae-uJMWDlGMb6j6eDIWCOysJgWoiWU8sKc6RX6fudyKn7_7flUZfuGtIPLq-zv1ZlUK_HIF_0hF6SF-hyWPC1g',
  },
  'agent-keys@bleqq.test': {
    id: 'RUlGV1nowK17BmGcPQ7zbQ',
    userHandle: 'AAAAAAAAQACAAAAAAAABDg',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgwbTLS-9PzTOq23KMLT4eYl1zAntZX1i2ZGyI7dZzLBmhRANCAASW-s2MUCdzA-kz6bnvy0RTuVW56gZsbCh438MXPYjzumK-Ramycmpw5EKiEeRFJaUgiKhJIPZf3RNjhH0F8Jlq',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElvrNjFAncwPpM-m578tEU7lVueoGbGwoeN_DFz2I87pivkWpsnJqcORCohHkRSWlIIioSSD2X90TY4R9BfCZag',
  },
  'reader-sv@example-bank.test': {
    id: 'Z6-QX06Ma-mkrsHpz1QBQg',
    userHandle: 'AAAAAAAAQACAAAAAAAABDw',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgXjQWZqtyaBvdSauPw7EQXwcL7Pzux4BT7PXI5mTmUHyhRANCAAQRNjo2Sl8qxneaYYjbBpMLfsl01osVq0s7xkDho4fT-OAVRR32_m-8VtPUTBlJzD58ymyHr4oIOzOrB4JHDtSf',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEETY6NkpfKsZ3mmGI2waTC37JdNaLFatLO8ZA4aOH0_jgFUUd9v5vvFbT1EwZScw-fMpsh6-KCDszqweCRw7Unw',
  },
  'language@example-bank.test': {
    id: 'CsD6EpLYQKiDdv88Ld3F-g',
    userHandle: 'AAAAAAAAQACAAAAAAAABEA',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgfHckdrhZk-n7rS-Xsce_W7LQAMD6-KmHC3LZvo5aCOyhRANCAAS0YAk5zeOVgIE00-Bf19vA0NzPZ9ipMklLaQw4_hwSoVMIZkdlpH3tPJFLRHpy0hbLQdUlQyeMjRMGB4tBAaoq',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEtGAJOc3jlYCBNNPgX9fbwNDcz2fYqTJJS2kMOP4cEqFTCGZHZaR97TyRS0R6ctIWy0HVJUMnjI0TBgeLQQGqKg',
  },
  'approver@second-bank.test': {
    id: 'HoDpXeyObXArC7s8SrOWzA',
    userHandle: 'AAAAAAAAQACAAAAAAAABEQ',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgqp4keK1CVCmUqb6cuZmxD4PZsm4iHTiQkEIDgB8CBTmhRANCAAQItrG7COh7F-vyB9XMk6g-gn4Jp6BtV6O3663YP4y-LUtTEc-4zlyk0tFyDvnF9JlXLtLIOE8vHq82uz9Z-763',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECLaxuwjoexfr8gfVzJOoPoJ-CaegbVejt-ut2D-Mvi1LUxHPuM5cpNLRcg75xfSZVy7SyDhPLx6vNrs_Wfu-tw',
  },
  'head@example-bank.test': {
    id: 'S_2tFzNmN9LjPd0JSfIDoA',
    userHandle: 'AAAAAAAAQACAAAAAAAABEg',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgqa9Ivpb5XXlmirMlbzbohNontuLf7D4Fl3XDlS6BYPyhRANCAAQJbOyzHVQEODjoP3JAx13yUasZ49sf0Qmlkp5b8dpf3vYH1z8w4DJHhqyL2fgC23fTxDnkiXCdtzijJOfIAIFx',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECWzssx1UBDg46D9yQMdd8lGrGePbH9EJpZKeW_HaX972B9c_MOAyR4asi9n4Att308Q55Ilwnbc4oyTnyACBcQ',
  },
  'participant@example-bank.test': {
    id: 'YSbfx136u1ysh-X30YIsCw',
    userHandle: 'AAAAAAAAQACAAAAAAAABEw',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQggl93_cm70Of-f3PiQ7tZcJlycdiE5iqsqnFgHKDjMB-hRANCAARQ5l-aYbdBVwipc2r9AP_yvagV1kmxVTQKYemSlKoRLHDRTqKeVTjGUgszBcZ2dzkIZhVjoSfzTjbHoSaFD_-7',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUOZfmmG3QVcIqXNq_QD_8r2oFdZJsVU0CmHpkpSqESxw0U6inlU4xlILMwXGdnc5CGYVY6En8042x6EmhQ__uw',
  },
  'leaver@example-bank.test': {
    id: 'MYjUHyARtPXm6xDvkcTVDA',
    userHandle: 'AAAAAAAAQACAAAAAAAABFA',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgK9otz3TjvM-42Qg8iHlT-wVxbGqLI4K1aBWoiF5UhvmhRANCAAT_NLM9yQN_dznFqHFbFb_QFVo6UMc2De8-9-zEan5f3naKHh9YQwYt7qdSL4AFo2rZgOq1Azw84ewad9zYDCDs',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE_zSzPckDf3c5xahxWxW_0BVaOlDHNg3vPvfsxGp-X952ih4fWEMGLe6nUi-ABaNq2YDqtQM8POHsGnfc2Awg7A',
  },
  'teams@example-bank.test': {
    id: 'tolnS1DXNFLOwqizKBOdpQ',
    userHandle: 'AAAAAAAAQACAAAAAAAABFQ',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgJTiCjny-ySokK2QBdLq3-4DJKfQJb0gbHJjB7XcG1QShRANCAAQoUKhUdzhU4OEp7KOLIwILHB4-vFhTvySaas6wtngHzD--5VGfl4796uAlQR-zJz-a2BCd1ilfo2jJjCUun4of',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKFCoVHc4VODhKeyjiyMCCxwePrxYU78kmmrOsLZ4B8w_vuVRn5eO_ergJUEfsyc_mtgQndYpX6NoyYwlLp-KHw',
  },
  'away@example-bank.test': {
    id: 'a4zmQU5oIdyEmmeBXymO4A',
    userHandle: 'AAAAAAAAQACAAAAAAAABFg',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQganXfJFPbgWOw1FzWVUv8b34oPtAto9TLpMeqoC92UsChRANCAATgnhwXyb4b68mO5-OoRg90PgDvPUiDliPUFMhnxM3ksmWNvF3gsHolFBFOv1kfKqMTA-aISjr9qZbWUy3pVIZM',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4J4cF8m-G-vJjufjqEYPdD4A7z1Ig5Yj1BTIZ8TN5LJljbxd4LB6JRQRTr9ZHyqjEwPmiEo6_amW1lMt6VSGTA',
  },
  'owner-approver@example-bank.test': {
    id: 'HW_V4mJVn-S8s6XXc22GRQ',
    userHandle: 'AAAAAAAAQACAAAAAAAABFw',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgOb9zHEMjPQN-0SjMAEGc9dHDeh4ssgnc7C4XkVsjBPahRANCAATay-cdkLtIHvPhnYPv55hPFOmt1nQ9ARSYu_fPQQRFwfA65pX2_rGusV-0eTUNSSFeZ5EKzcFmdj0RYvzO6bqp',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2svnHZC7SB7z4Z2D7-eYTxTprdZ0PQEUmLv3z0EERcHwOuaV9v6xrrFftHk1DUkhXmeRCs3BZnY9EWL8zum6qQ',
  },
  'sv-member@example-bank.test': {
    id: 'bx6VGOjPc4-NrE_T0lYD9g',
    userHandle: 'AAAAAAAAQACAAAAAAAABGA',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgaYlcALahDb9vTtgmWOQQ8nn2F5V0hUVQb8Nvcnn7IRqhRANCAAQyynWPoPJHC0EvBKNItAEeKA70pYEyoYlyknHCDtsomtaqrB4s0lY_8Fc7jS36C3zFbhWzAMgDKGuoUw3WUoYh',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEMsp1j6DyRwtBLwSjSLQBHigO9KWBMqGJcpJxwg7bKJrWqqweLNJWP_BXO40t-gt8xW4VswDIAyhrqFMN1lKGIQ',
  },
  'security@example-bank.test': {
    id: 'aSLzP-GfONXmqmvNJM1Dpw',
    userHandle: 'AAAAAAAAQACAAAAAAAABGQ',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgg1kUBoO5_m0c7zOY4kr50wOr2FSyQrNHGxCPBHPbtrihRANCAASvryEB2X0sX6NPh4_KCL1e9ZdxMt3ZLocRd3LYmFnpKFIds0MFn9PLguJvYfzOGe9T0t39UxBNuPTpfR9QykB4',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEr68hAdl9LF-jT4ePygi9XvWXcTLd2S6HEXdy2JhZ6ShSHbNDBZ_Ty4Lib2H8zhnvU9Ld_VMQTbj06X0fUMpAeA',
  },
  'tokens@example-bank.test': {
    id: 'ziKQWgKAXwYcF5LifRQrFg',
    userHandle: 'AAAAAAAAQACAAAAAAAABGg',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg7QeWsKttEGH276GWyk2TsS48AcvIdOfsVCSlf8dSWfahRANCAAT_H2pOOGke_GVzt8GPZcW7a5rhl4Y8i8LhaFOoZKTsC6oysxA0RhqutFXHD9gjhlitIOp95aj-_BIKl37zgA1g',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE_x9qTjhpHvxlc7fBj2XFu2ua4ZeGPIvC4WhTqGSk7AuqMrMQNEYarrRVxw_YI4ZYrSDqfeWo_vwSCpd-84ANYA',
  },
  'library-only@example-bank.test': {
    id: 'TsqBifXIUEx-DjxvHwaawQ',
    userHandle: 'AAAAAAAAQACAAAAAAAABGw',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg9ix7y_dw-ke96P96I1Dr6YY7HzRPXDEEBeWaxq6QNQOhRANCAATcfwhwywXgm6irzESPP4i-mLtBilm9DCgaLxHCPd9eNeqsJvykJp0I8BT2OpQM6Td1gyKreHCLCsTyjMmL_DtA',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3H8IcMsF4Juoq8xEjz-Ivpi7QYpZvQwoGi8Rwj3fXjXqrCb8pCadCPAU9jqUDOk3dYMiq3hwiwrE8ozJi_w7QA',
  },
  'compliance_officer@second-bank.test': {
    id: 'K0xrK7A1QCcMtSusB8Yt2w',
    userHandle: 'AAAAAAAAQACAAAAAAAABHA',
    privateKey: 'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg7d5yrQMesPB4k5S6aJ2nmPg2VzE661vKG4wBp56GI16hRANCAAQEsdbpdWp1AGnebDyIhRofHTtzIJgALNjW7qNbAr2a1_YB0nB2P7RH_cPUH4FuzVGv7y5BlY9zRRI063bTJRM7',
    publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBLHW6XVqdQBp3mw8iIUaHx07cyCYACzY1u6jWwK9mtf2AdJwdj-0R_3D1B-Bbs1Rr-8uQZWPc0USNOt20yUTOw',
  },
};
