# Generated by Django 6.1.1 on 2026-09-20 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import append_only_trigger_operations, rls_operations

"""home 0001 (chunk 6, HOM-02, HOM-04): what one bank was told about a week, which cases
that telling named, and the calendar addresses its people subscribed with. All three are
tenant tables: `tenant_id` on every row, row-level security enabled and forced, and the one
`tenant_isolation` policy whose USING and WITH CHECK are the session's own tenant, so
cw_app reads and writes nothing of another bank's and cannot bypass it (NFR-01, ADR 0022).

Not `mixed=True`: none of the three ever holds a library row. A week that holds nothing for
one bank holds three reforms for another, because the footprint and the cases behind it are
that bank's own.

`briefing_item` also takes the append-only trigger, so "a later change to the feed does not
alter a sent briefing" is enforced by the database and not by anyone remembering it
(HOM-S3). The trigger function is shared 0001's, replaced in place by shared 0005; a
conscious fix states its intent with `SET LOCAL cw.maintenance` in a migration, and the
application role cannot switch it off.

Three departures from `schema.sql` §9, recorded in INPUT_DELTAS §9:

- `briefing_item` is keyed on a uuid `id` with `UNIQUE (briefing_id, case_id)` beside it,
  rather than the designed composite primary key: Django addresses a row by one column, and
  the unique constraint says exactly what the composite key said.
- `calendar_feed.filter` is a `text` column with choices rather than the designed
  `feed_filter` Postgres enum. Kinds are CharFields with choices everywhere in this schema,
  and the kinds-only guard fails on a Postgres enum type (playbook 15).
- `calendar_feed.token_hash` is `varchar(64)` rather than `text`: a SHA-256 in hex is
  exactly 64 characters, and a column that cannot hold more cannot hold anything else."""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_cases'),
        ('identity', '0003_mixed_tables_write_their_own_zone'),
        ('shared', '0006_outboxcursor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'briefing',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='BriefingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField()),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.briefing')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cases.changecase')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'briefing_item',
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('filter', models.CharField(choices=[('all', 'all'), ('regulatory', 'regulatory'), ('internal', 'internal')], default='all', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user')),
            ],
            options={
                'db_table': 'calendar_feed',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='briefing',
            constraint=models.UniqueConstraint(fields=('tenant', 'week_start'), name='briefing_one_per_week'),
        ),
        migrations.AddConstraint(
            model_name='briefingitem',
            constraint=models.UniqueConstraint(fields=('briefing', 'case'), name='briefing_item_one_per_case'),
        ),
        migrations.AddIndex(
            model_name='calendarfeed',
            index=models.Index(fields=['tenant', 'user'], name='calendar_feed_owner_idx'),
        ),
        *rls_operations("briefing"),
        *rls_operations("briefing_item"),
        *rls_operations("calendar_feed"),
        *append_only_trigger_operations("briefing_item"),
    ]
