# Generated by Django 6.1.1 on 2026-09-20 13:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import rls_operations

"""search 0001 (chunk 7, SRC-01, SRC-02, H7): the derived index the hybrid query reads.

One row per legal unit per language, built from an obligation version, a provision version
or a registered change. Derived data, not a library record and not a tenant record: what
keeps it faithful to the library is the one door in apps/search/indexing.py, not a
proposal, so the library fence's allowlist is untouched.

`owner_tenant_id` is nullable and stays NULL in R1: only shared records are indexed (D-10,
owner items 4 and 10). The column is here so the rule lives in the database rather than
only in Python, and so the row-level shape is final before ADR 0010 is superseded. It is
therefore a mixed table and takes `rls_operations(mixed=True, column="owner_tenant_id")`,
the split shape of hardening H15 that `agent_run` and `source` already carry: one FOR ALL
policy whose USING and WITH CHECK are the session's own zone, so a bank can write only its
own zone and the indexer, which runs with no tenant active, only the shared one, and
`library_rows_visible`, a FOR SELECT policy that adds the shared chunks to every bank's
reads. Permissive policies OR together per command, so reads are mixed and writes are not.
Not `library_fence=True`: every chunk is written with no tenant active, so the narrow write
rule holds from the first row.

`tsv` is generated and stored, per content language, in that language's own PostgreSQL
configuration (INPUT_DELTAS §3), which departs from `docs/inputs/schema.sql`: that file
labels `search_chunk` LIBRARY and checks `lang IN ('sv', 'en')`. R1 has five content
languages, and `lang` is a foreign key to the seeded `language` rows rather than free text,
so a chunk in a language nobody seeded cannot be written at all."""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0006_problem_report_writes_its_own_zone"),
        ("shared", "0005_append_only_hatch_allowlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("provision_version", "Provision version"),
                            ("obligation_version", "Obligation version"),
                            ("change", "Regulatory change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.UUIDField()),
                ("title", models.TextField()),
                ("body", models.TextField()),
                ("hierarchy_path", models.TextField(blank=True, default="")),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tsv",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                language="en",
                                then=django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector(
                                        "title",
                                        config=models.Value("english"),
                                        weight="A",
                                    ),
                                    "||",
                                    django.contrib.postgres.search.SearchVector(
                                        "body",
                                        config=models.Value("english"),
                                        weight="B",
                                    ),
                                    django.contrib.postgres.search.SearchConfig(
                                        models.Value("english")
                                    ),
                                ),
                            ),
                            models.When(
                                language="sv",
                                then=django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector(
                                        "title",
                                        config=models.Value("swedish"),
                                        weight="A",
                                    ),
                                    "||",
                                    django.contrib.postgres.search.SearchVector(
                                        "body",
                                        config=models.Value("swedish"),
                                        weight="B",
                                    ),
                                    django.contrib.postgres.search.SearchConfig(
                                        models.Value("swedish")
                                    ),
                                ),
                            ),
                            models.When(
                                language="da",
                                then=django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector(
                                        "title",
                                        config=models.Value("danish"),
                                        weight="A",
                                    ),
                                    "||",
                                    django.contrib.postgres.search.SearchVector(
                                        "body",
                                        config=models.Value("danish"),
                                        weight="B",
                                    ),
                                    django.contrib.postgres.search.SearchConfig(
                                        models.Value("danish")
                                    ),
                                ),
                            ),
                            models.When(
                                language="nb",
                                then=django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector(
                                        "title",
                                        config=models.Value("norwegian"),
                                        weight="A",
                                    ),
                                    "||",
                                    django.contrib.postgres.search.SearchVector(
                                        "body",
                                        config=models.Value("norwegian"),
                                        weight="B",
                                    ),
                                    django.contrib.postgres.search.SearchConfig(
                                        models.Value("norwegian")
                                    ),
                                ),
                            ),
                            models.When(
                                language="fi",
                                then=django.contrib.postgres.search.CombinedSearchVector(
                                    django.contrib.postgres.search.SearchVector(
                                        "title",
                                        config=models.Value("finnish"),
                                        weight="A",
                                    ),
                                    "||",
                                    django.contrib.postgres.search.SearchVector(
                                        "body",
                                        config=models.Value("finnish"),
                                        weight="B",
                                    ),
                                    django.contrib.postgres.search.SearchConfig(
                                        models.Value("finnish")
                                    ),
                                ),
                            ),
                            default=django.contrib.postgres.search.CombinedSearchVector(
                                django.contrib.postgres.search.SearchVector(
                                    "title", config=models.Value("english"), weight="A"
                                ),
                                "||",
                                django.contrib.postgres.search.SearchVector(
                                    "body", config=models.Value("english"), weight="B"
                                ),
                                django.contrib.postgres.search.SearchConfig(
                                    models.Value("english")
                                ),
                            ),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "embedding_version",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("embedded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        db_column="lang",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="library.language",
                        to_field="key",
                    ),
                ),
                (
                    "owner_tenant",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "search_chunk",
                "ordering": ["source_type", "source_id", "language_id"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["tsv"], name="search_chunk_tsv_idx"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="search_chunk_embedding_idx",
                        opclasses=["vector_cosine_ops"],
                    ),
                    models.Index(
                        fields=["valid_from", "valid_to"],
                        name="search_chunk_validity_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_type", "source_id", "language"),
                        name="search_chunk_source_unique",
                    )
                ],
            },
        ),
        *rls_operations("search_chunk", mixed=True, column="owner_tenant_id"),
    ]
