# Generated by Django 6.1.1 on 2026-09-19 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


"""tenants 0001 (chunk 1, ID-05, TEN-06): support_access, under forced RLS so the
tenant sees every time platform staff entered its data."""

from apps.shared.migration_helpers import rls_operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('shared', '0002_tenant_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('ticket_ref', models.CharField(blank=True, max_length=100)),
                ('access_level', models.CharField(choices=[('read', 'read'), ('write', 'write')], default='read', max_length=8)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.user')),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_accesses', to='identity.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'support_access',
                'ordering': ['started_at', 'id'],
            },
        ),
        *rls_operations("support_access"),
    ]
