# Generated by Django 6.1.1 on 2026-09-25 02:22

import django.db.models.deletion
import uuid
from django.db import migrations, models

"""tenants 0002 (chunk 8, TEN-02, REG-05; chunk 11, ID-07, ID-08): the bank's organisation
and its security policy, every table under forced RLS.

PostgreSQL checks a foreign key without row-level security, so a plain key would let one
bank's row point at another bank's. Every reference to a tenant row is therefore also a
composite `(tenant_id, …)` key: to `UNIQUE (tenant_id, id)` on the tables here and on
`link_kind`, and to `membership_tenant_user_unique` for a person, which makes a head or an
owner a member of the same bank. A legal entity's term must come from the `legal_entity`
dimension, which a trigger checks because a CHECK cannot read another table."""

from apps.shared.migration_helpers import rls_operations

TABLES = (
    "org_unit",
    "licence",
    "licence_service_term",
    "tenant_product",
    "tenant_product_term",
    "internal_item",
    "security_policy",
)

# Targets of a composite key: this migration's own, and link_kind's (taxonomy 0001), which
# gains the pair here because internal_item is its first tenant-checked reader.
TENANT_ID_UNIQUE = ("org_unit", "licence", "tenant_product", "internal_item", "link_kind")

# (table, column, target table, target column)
COMPOSITE_KEYS = (
    ("org_unit", "parent_id", "org_unit", "id"),
    ("org_unit", "head_user_id", "membership", "user_id"),
    ("licence", "org_unit_id", "org_unit", "id"),
    ("licence", "owner_user_id", "membership", "user_id"),
    ("licence_service_term", "licence_id", "licence", "id"),
    ("tenant_product", "org_unit_id", "org_unit", "id"),
    ("tenant_product", "owner_user_id", "membership", "user_id"),
    ("tenant_product_term", "product_id", "tenant_product", "id"),
    ("internal_item", "kind_id", "link_kind", "id"),
    ("internal_item", "org_unit_id", "org_unit", "id"),
    ("internal_item", "owner_user_id", "membership", "user_id"),
    ("security_policy", "updated_by_id", "membership", "user_id"),
)


def tenant_id_unique(table):
    name = f"{table}_tenant_id_id_unique"
    return migrations.RunSQL(
        sql=f'ALTER TABLE "{table}" ADD CONSTRAINT {name} UNIQUE (tenant_id, id)',
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


def composite_key(table, column, target, target_column):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


ENTITY_TERM_GUARD_SQL = """
CREATE FUNCTION cw_org_unit_entity_term_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.entity_term_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM taxonomy_term t JOIN term_dimension d ON d.id = t.dimension_id
        WHERE t.id = NEW.entity_term_id AND d.key = 'legal_entity'
    ) THEN
        RAISE EXCEPTION 'org_unit.entity_term must be a term of the legal_entity dimension'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER org_unit_entity_term_guard BEFORE INSERT OR UPDATE OF entity_term_id ON org_unit
    FOR EACH ROW EXECUTE FUNCTION cw_org_unit_entity_term_guard();
"""
ENTITY_TERM_GUARD_REVERSE_SQL = """
DROP TRIGGER IF EXISTS org_unit_entity_term_guard ON org_unit;
DROP FUNCTION IF EXISTS cw_org_unit_entity_term_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("library", "0009_problem_report_closure"),
        ("shared", "0008_library_write_guard"),
        ("taxonomy", "0008_set_based_footprint"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("group", "group"),
                            ("legal_entity", "legal_entity"),
                            ("business_area", "business_area"),
                            ("business_unit", "business_unit"),
                            ("function", "function"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("org_number", models.CharField(blank=True, max_length=40)),
                ("lei", models.CharField(blank=True, max_length=20)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "entity_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.taxonomyterm",
                    ),
                ),
                (
                    "head_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="tenants.orgunit",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "org_unit",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("granted_on", models.DateField(blank=True, null=True)),
                ("withdrawn_on", models.DateField(blank=True, null=True)),
                ("scope_note", models.TextField(blank=True)),
                ("issuer", models.CharField(blank=True, max_length=200)),
                ("number", models.CharField(blank=True, max_length=100)),
                ("scope_statement", models.TextField(blank=True)),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("next_audit_on", models.DateField(blank=True, null=True)),
                (
                    "authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="library.authority",
                    ),
                ),
                (
                    "licence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.taxonomyterm",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licences",
                        to="tenants.orgunit",
                    ),
                ),
            ],
            options={
                "db_table": "licence",
                "ordering": ["org_unit", "granted_on", "id"],
            },
        ),
        migrations.CreateModel(
            name="InternalItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("external_system", models.CharField(blank=True, max_length=100)),
                ("external_ref", models.CharField(blank=True, max_length=200)),
                ("last_reviewed_on", models.DateField(blank=True, null=True)),
                ("next_review_on", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.linkkind",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_items",
                        to="tenants.orgunit",
                    ),
                ),
            ],
            options={
                "db_table": "internal_item",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credential_policy",
                    models.CharField(
                        choices=[
                            ("any_passkey", "any_passkey"),
                            ("device_bound", "device_bound"),
                        ],
                        default="any_passkey",
                        max_length=16,
                    ),
                ),
                ("allowed_authenticators", models.JSONField(blank=True, default=list)),
                ("device_bound_from", models.DateField(blank=True, null=True)),
                (
                    "session_idle_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "session_absolute_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "security_policy",
                "ordering": ["tenant"],
            },
        ),
        migrations.CreateModel(
            name="TenantProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "planned"),
                            ("live", "live"),
                            ("retired", "retired"),
                        ],
                        default="live",
                        max_length=8,
                    ),
                ),
                ("launch_date", models.DateField(blank=True, null=True)),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="tenants.orgunit",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_product",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="TenantProductTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terms",
                        to="tenants.tenantproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.taxonomyterm",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_product_term",
                "ordering": ["product", "term"],
            },
        ),
        migrations.CreateModel(
            name="LicenceServiceTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_terms",
                        to="tenants.licence",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.taxonomyterm",
                    ),
                ),
            ],
            options={
                "db_table": "licence_service_term",
                "ordering": ["licence", "term"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("licence", "term"), name="licence_service_term_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="orgunit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("entity_term__isnull", True),
                    ("kind", "legal_entity"),
                    _connector="OR",
                ),
                name="org_unit_entity_term_on_legal_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgunit",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="org_unit_not_own_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="internalitem",
            constraint=models.UniqueConstraint(
                fields=("tenant", "kind", "name"), name="internal_item_kind_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="securitypolicy",
            constraint=models.UniqueConstraint(
                fields=("tenant",), name="security_policy_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="securitypolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("session_idle_minutes__isnull", True),
                    ("session_idle_minutes__gt", 0),
                    _connector="OR",
                ),
                name="security_policy_idle_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="securitypolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("session_absolute_hours__isnull", True),
                    ("session_absolute_hours__gt", 0),
                    _connector="OR",
                ),
                name="security_policy_absolute_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantproduct",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="tenant_product_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantproductterm",
            constraint=models.UniqueConstraint(
                fields=("product", "term"), name="tenant_product_term_unique"
            ),
        ),
        *[operation for table in TABLES for operation in rls_operations(table)],
        *[tenant_id_unique(table) for table in TENANT_ID_UNIQUE],
        *[composite_key(*key) for key in COMPOSITE_KEYS],
        migrations.RunSQL(sql=ENTITY_TERM_GUARD_SQL, reverse_sql=ENTITY_TERM_GUARD_REVERSE_SQL),
    ]
