# Generated by Django 6.1.1 on 2026-09-25 02:48

import django.db.models.deletion
import uuid
from django.db import migrations, models

"""tenants 0003 (chunk 8, TEN-03): a person in a team, and a team as the owner of a licence or
an internal item, never beside a person.

As in tenants 0002, PostgreSQL checks a foreign key without row-level security, so each
reference to a tenant row is also a composite `(tenant_id, …)` key: to `UNIQUE (tenant_id, id)`
on `team` (taxonomy 0009), and to `membership_tenant_user_unique` for the person, which makes
a team member a member of the same bank."""

from apps.shared.migration_helpers import rls_operations

# (table, column, target table, target column)
COMPOSITE_KEYS = (
    ("team_member", "team_id", "team", "id"),
    ("team_member", "user_id", "membership", "user_id"),
    ("licence", "owner_team_id", "team", "id"),
    ("internal_item", "owner_team_id", "team", "id"),
)


def composite_key(table, column, target, target_column):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("library", "0009_problem_report_closure"),
        ("shared", "0008_library_write_guard"),
        ("taxonomy", "0009_register_lists"),
        ("tenants", "0002_organisation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "team_member",
                "ordering": ["team", "user"],
            },
        ),
        migrations.AddField(
            model_name="internalitem",
            name="owner_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="taxonomy.team",
            ),
        ),
        migrations.AddField(
            model_name="licence",
            name="owner_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="taxonomy.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="internalitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("owner_user__isnull", True),
                    ("owner_team__isnull", True),
                    _connector="OR",
                ),
                name="internal_item_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="licence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("owner_user__isnull", True),
                    ("owner_team__isnull", True),
                    _connector="OR",
                ),
                name="licence_one_owner",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="taxonomy.team",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="shared.tenant",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="team_member_unique"
            ),
        ),
        *rls_operations("team_member"),
        *[composite_key(*key) for key in COMPOSITE_KEYS],
    ]
