# Generated by Django 6.1.1 on 2026-09-25 03:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

"""tenants 0004 (chunk 8, TEN-06, D-49, ADR 0042): a support access request, approved by the
bank, time-boxed.

The chunk 1 recovery rows keep their values: each is born `expired`, with its window already
closed and zero hours, and its `requested_at` is backfilled from `started_at` bank by bank,
because row-level security is forced on the schema owner as well.

Four eyes at the database: a CHECK keeps the approver from being the platform person, and
the approver and whoever declined or revoked are members of the same bank through a
composite key, as in tenants 0003. A guard trigger refuses every DELETE and any change to
who asked, for what, at which level and for how long; the decision columns move once, and
only the status may move after them. Its hatch is the schema owner's alone, as on the
append-only ledgers (shared 0005), so the retention purge and tenant exit can still delete.

One SELECT-only policy is added beside `tenant_isolation`: a platform person reads the rows
that name them, keyed on `app.platform_user_id`, so the console can list and check their own
grants before any bank is active (ADR 0042). It is inert until `identity/session_logic.py`
sets that setting, and `tests_rls.OTHER_POLICIES` pins it."""

from apps.shared.migration_helpers import MAINTENANCE_SETTING, MIGRATOR_ROLE

OWN_GRANTS_POLICY = "support_access_own_grants"
PLATFORM_USER_EXPRESSION = "NULLIF(current_setting('app.platform_user_id', true), '')::uuid"

BACKFILL_SQL = """
DO $$
DECLARE bank uuid;
BEGIN
    FOR bank IN SELECT id FROM tenant LOOP
        PERFORM set_config('app.tenant_id', bank::text, true);
        UPDATE support_access SET requested_at = started_at WHERE started_at IS NOT NULL;
    END LOOP;
    PERFORM set_config('app.tenant_id', '', true);
END $$;
"""

GUARD_SQL = f"""
CREATE FUNCTION cw_support_access_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF current_setting('{MAINTENANCE_SETTING}', true) = 'on' AND session_user = '{MIGRATOR_ROLE}' THEN
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'support_access is never deleted' USING ERRCODE = 'raise_exception';
    END IF;
    IF (NEW.id, NEW.tenant_id, NEW.platform_user_id, NEW.reason, NEW.ticket_ref, NEW.access_level,
        NEW.hours, NEW.requested_at, NEW.request_expires_at)
       IS DISTINCT FROM
       (OLD.id, OLD.tenant_id, OLD.platform_user_id, OLD.reason, OLD.ticket_ref, OLD.access_level,
        OLD.hours, OLD.requested_at, OLD.request_expires_at) THEN
        RAISE EXCEPTION 'support_access: who asked, for what, at which level and for how long never change'
            USING ERRCODE = 'raise_exception';
    END IF;
    IF (OLD.started_at IS NOT NULL
        AND (NEW.approved_by_id, NEW.approved_step_up_assertion_id, NEW.started_at, NEW.expires_at)
            IS DISTINCT FROM (OLD.approved_by_id, OLD.approved_step_up_assertion_id, OLD.started_at, OLD.expires_at))
       OR (OLD.ended_at IS NOT NULL
        AND (NEW.ended_at, NEW.ended_by_id) IS DISTINCT FROM (OLD.ended_at, OLD.ended_by_id)) THEN
        RAISE EXCEPTION 'support_access: a decision is made once and never rewritten'
            USING ERRCODE = 'raise_exception';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER support_access_guard BEFORE UPDATE OR DELETE ON support_access
    FOR EACH ROW EXECUTE FUNCTION cw_support_access_guard();
"""

GUARD_REVERSE_SQL = """
DROP TRIGGER IF EXISTS support_access_guard ON support_access;
DROP FUNCTION IF EXISTS cw_support_access_guard();
"""


def member_key(column):
    """The person is a member of the same bank: `membership_tenant_user_unique` (tenants 0003)."""
    name = f"support_access_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "support_access" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            'REFERENCES "membership" (tenant_id, user_id)'
        ),
        reverse_sql=f'ALTER TABLE "support_access" DROP CONSTRAINT IF EXISTS {name}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_login_event_key_created_and_withheld"),
        ("shared", "0009_tenant_workflow_policy"),
        ("tenants", "0003_team_member"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportaccess",
            options={"ordering": ["requested_at", "id"]},
        ),
        migrations.AddField(
            model_name="supportaccess",
            name="approved_step_up_assertion_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportaccess",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="supportaccess",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportaccess",
            name="hours",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supportaccess",
            name="request_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportaccess",
            name="requested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="supportaccess",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "requested"),
                    ("approved", "approved"),
                    ("declined", "declined"),
                    ("revoked", "revoked"),
                    ("expired", "expired"),
                ],
                default="expired",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="supportaccess",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="supportaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_by__isnull", True),
                    models.Q(("approved_by", models.F("platform_user")), _negated=True),
                    _connector="OR",
                ),
                name="support_access_approver_is_not_the_requester",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("access_level", "read"),
                    ("approved_by__isnull", True),
                    _connector="OR",
                ),
                name="support_access_only_a_read_is_approved",
            ),
        ),
        migrations.RunSQL(sql=BACKFILL_SQL, reverse_sql=migrations.RunSQL.noop),
        member_key("approved_by_id"),
        member_key("ended_by_id"),
        migrations.RunSQL(sql=GUARD_SQL, reverse_sql=GUARD_REVERSE_SQL),
        migrations.RunSQL(
            sql=(
                f'CREATE POLICY {OWN_GRANTS_POLICY} ON "support_access" FOR SELECT '
                f"USING (platform_user_id = {PLATFORM_USER_EXPRESSION})"
            ),
            reverse_sql=f'DROP POLICY IF EXISTS {OWN_GRANTS_POLICY} ON "support_access"',
        ),
    ]
