# Generated by Django 6.1.1 on 2026-09-25 03:25

"""A licence and a product carry the version a unit already has, so a change to either
sends `If-Match` (TEN-02, c8-ten-organisation). Numbered 0005 because the R2 plan hands 0004
to c8-ten-support-grants, built in the same wave: once that lands, this migration depends on
0004_support_grants instead of 0003, a one-line change at integration."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_support_grants"),
    ]

    operations = [
        migrations.AddField(
            model_name="licence",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="tenantproduct",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
