# Generated by Django 6.1.1 on 2026-10-05 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models

"""tenants 0006 (TEN-07, TEN-08, PUBLIC_REGISTERS.md 5.1): a lookup in the public registers
and a legal entity's register facts, both under forced row-level security.

As in tenants 0002, every reference to another tenant row is also a composite
`(tenant_id, …)` key, because PostgreSQL checks a foreign key without row-level security:
the person who started a lookup is a member of the same bank, and a register entry's unit is
one of the bank's own. A register entry belongs to a legal entity, which a trigger checks
because a CHECK cannot read another table. The authority is a library row, shared by every
bank, so its key is a plain one."""

from apps.shared.migration_helpers import rls_operations

# (table, column, target table, target column)
COMPOSITE_KEYS = (
    ("register_lookup", "requested_by_id", "membership", "user_id"),
    ("register_entry", "org_unit_id", "org_unit", "id"),
)


def composite_key(table, column, target, target_column):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) '
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


LEGAL_ENTITY_GUARD_SQL = """
CREATE FUNCTION cw_register_entry_legal_entity_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM org_unit u WHERE u.id = NEW.org_unit_id AND u.kind = 'legal_entity'
    ) THEN
        RAISE EXCEPTION 'register_entry.org_unit must be a legal entity'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER register_entry_legal_entity_guard BEFORE INSERT OR UPDATE OF org_unit_id ON register_entry
    FOR EACH ROW EXECUTE FUNCTION cw_register_entry_legal_entity_guard();
"""
LEGAL_ENTITY_GUARD_REVERSE_SQL = """
DROP TRIGGER IF EXISTS register_entry_legal_entity_guard ON register_entry;
DROP FUNCTION IF EXISTS cw_register_entry_legal_entity_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0010_login_event_access_token_refused"),
        ("library", "0012_private_child_rls"),
        ("shared", "0010_jurisdiction_proposal_door"),
        ("tenants", "0005_licence_product_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterLookup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=40)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "register_lookup",
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RegisterEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("facts", models.JSONField()),
                ("source_url", models.URLField(max_length=500)),
                ("read_at", models.DateTimeField()),
                ("changed_at", models.DateTimeField()),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="library.authority",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="register_entries",
                        to="tenants.orgunit",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "register_entry",
                "ordering": ["org_unit", "authority", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_unit", "authority"), name="register_entry_unique"
                    )
                ],
            },
        ),
        *[operation for table in ("register_lookup", "register_entry") for operation in rls_operations(table)],
        *[composite_key(*key) for key in COMPOSITE_KEYS],
        migrations.RunSQL(sql=LEGAL_ENTITY_GUARD_SQL, reverse_sql=LEGAL_ENTITY_GUARD_REVERSE_SQL),
    ]
