# Generated by Django 6.1.1 on 2026-09-19 03:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


"""taxonomy 0001 (chunk 2, VOC-01, VOC-02, VOC-07, FP-01, FP-02): the library vocabularies
and their labels, the taxonomy terms, the tenant vocabularies and their labels, taggings,
suggestions, the footprint, its change requests and its history. Generated, then the
RunSQL parts appended: forced RLS on every table with a tenant column, the append-only
trigger on footprint_history, and the SQL twin of apps/taxonomy/matching.in_footprint().

The function body is frozen here on purpose (playbook 4.5: a migration declares what its
operations need inline). apps/taxonomy/tests_matching.py pins it to the Python rule."""

from apps.shared.migration_helpers import append_only_trigger_operations, rls_operations

# footprint_term sits under forced RLS: the tenant argument narrows the visible rows
# further, never wider. A dimension counts only when it restricts and the footprint has at
# least one term in it; a term id that is no term carries no dimension and so restricts
# nothing; NOT EXISTS over an empty set is true, so a record with no terms matches.
IN_FOOTPRINT_FUNCTION = """
CREATE OR REPLACE FUNCTION taxonomy_in_footprint(p_tenant uuid, p_terms uuid[]) RETURNS boolean
LANGUAGE sql STABLE AS $$
    SELECT NOT EXISTS (
        SELECT 1
        FROM (
            SELECT t.dimension_id, bool_or(f.id IS NOT NULL) AS hit
            FROM unnest(p_terms) AS wanted(term_id)
            JOIN taxonomy_term t ON t.id = wanted.term_id
            JOIN term_dimension d ON d.id = t.dimension_id AND d.restricts_footprint AND d.active
            LEFT JOIN footprint_term f ON f.term_id = t.id AND f.tenant_id = p_tenant
            WHERE EXISTS (
                SELECT 1 FROM footprint_term f2
                JOIN taxonomy_term t2 ON t2.id = f2.term_id
                WHERE f2.tenant_id = p_tenant AND t2.dimension_id = t.dimension_id
            )
            GROUP BY t.dimension_id
        ) per_dimension
        WHERE NOT per_dimension.hit
    )
$$;
"""

TENANT_TABLES = (
    "tenant_tag", "tenant_tag_label", "tagging",
    "link_kind", "link_kind_label",
    "effort_size", "effort_size_label",
    "compliance_status", "compliance_status_label",
    "risk_rating", "risk_rating_label",
    "case_sub_status", "case_sub_status_label",
    "dismissal_reason", "dismissal_reason_label",
    "close_reason", "close_reason_label",
    "vocabulary_suggestion",
    "footprint_term", "footprint_change_request", "footprint_change_add", "footprint_change_remove",
    "footprint_history",
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('library', '0002_jurisdiction'),
        ('shared', '0002_tenant_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSubStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'case_sub_status',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CaseSubStatusLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.casesubstatus')),
            ],
            options={
                'db_table': 'case_sub_status_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='ChangeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'change_type',
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('key',), name='change_type_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='ChangeTypeLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.changetype')),
            ],
            options={
                'db_table': 'change_type_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='ClosureReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'close_reason',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ClosureReasonLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.closurereason')),
            ],
            options={
                'db_table': 'close_reason_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'compliance_status',
                'ordering': ['ordinal', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceStatusLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.compliancestatus')),
            ],
            options={
                'db_table': 'compliance_status_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='DismissalReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'dismissal_reason',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='DismissalReasonLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.dismissalreason')),
            ],
            options={
                'db_table': 'dismissal_reason_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'duty_type',
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('key',), name='duty_type_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='DutyTypeLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.dutytype')),
            ],
            options={
                'db_table': 'duty_type_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='EffortSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'effort_size',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='EffortSizeLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.effortsize')),
            ],
            options={
                'db_table': 'effort_size_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'flag',
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('key',), name='flag_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='FlagLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.flag')),
            ],
            options={
                'db_table': 'flag_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='FootprintChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('withdrawn', 'withdrawn')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'footprint_change_request',
                'ordering': ['requested_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FootprintChangeRemove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remove_links', to='taxonomy.footprintchangerequest')),
            ],
            options={
                'db_table': 'footprint_change_remove',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FootprintChangeAdd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_links', to='taxonomy.footprintchangerequest')),
            ],
            options={
                'db_table': 'footprint_change_add',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('binding_default', models.BooleanField(default=True)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'instrument_level',
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('key',), name='instrument_level_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentLevelLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.instrumentlevel')),
            ],
            options={
                'db_table': 'instrument_level_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='LibraryTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'library_tag',
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('key',), name='library_tag_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='LibraryTagLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.librarytag')),
            ],
            options={
                'db_table': 'library_tag_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='LinkKind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'link_kind',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='LinkKindLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.linkkind')),
            ],
            options={
                'db_table': 'link_kind_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionKind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='library.jurisdiction')),
            ],
            options={
                'db_table': 'provision_kind',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionKindLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.provisionkind')),
            ],
            options={
                'db_table': 'provision_kind_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'relation_type',
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('key',), name='relation_type_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='RelationTypeLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.relationtype')),
            ],
            options={
                'db_table': 'relation_type_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='RiskRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'risk_rating',
                'ordering': ['ordinal', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='RiskRatingLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.riskrating')),
            ],
            options={
                'db_table': 'risk_rating_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='SourceKind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'source_kind',
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('key',), name='source_kind_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='SourceKindLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.sourcekind')),
            ],
            options={
                'db_table': 'source_kind_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='taxonomy.taxonomyterm')),
            ],
            options={
                'db_table': 'taxonomy_term',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='FootprintTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='footprint_terms', to='taxonomy.taxonomyterm')),
            ],
            options={
                'db_table': 'footprint_term',
                'ordering': ['added_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FootprintHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('added', 'added'), ('removed', 'removed')], max_length=16)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('step_up_assertion_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.user')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='taxonomy.footprintchangerequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taxonomy.taxonomyterm')),
            ],
            options={
                'db_table': 'footprint_history',
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='footprintchangerequest',
            name='adds',
            field=models.ManyToManyField(related_name='+', through='taxonomy.FootprintChangeAdd', to='taxonomy.taxonomyterm'),
        ),
        migrations.AddField(
            model_name='footprintchangerequest',
            name='removes',
            field=models.ManyToManyField(related_name='+', through='taxonomy.FootprintChangeRemove', to='taxonomy.taxonomyterm'),
        ),
        migrations.AddField(
            model_name='footprintchangeremove',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taxonomy.taxonomyterm'),
        ),
        migrations.AddField(
            model_name='footprintchangeadd',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taxonomy.taxonomyterm'),
        ),
        migrations.CreateModel(
            name='TaxonomyTermLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.taxonomyterm')),
            ],
            options={
                'db_table': 'taxonomy_term_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='TenantTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'tenant_tag',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Tagging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(max_length=64)),
                ('subject_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taggings', to='taxonomy.tenanttag')),
            ],
            options={
                'db_table': 'tagging',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TenantTagLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.tenanttag')),
            ],
            options={
                'db_table': 'tenant_tag_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='TermDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('restricts_footprint', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'term_dimension',
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('key',), name='term_dimension_key_unique')],
            },
        ),
        migrations.AddField(
            model_name='taxonomyterm',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='taxonomy.termdimension'),
        ),
        migrations.CreateModel(
            name='TermDimensionLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.termdimension')),
            ],
            options={
                'db_table': 'term_dimension_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('sla_days', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'urgency',
                'ordering': ['ordinal', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('key',), name='urgency_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='UrgencyLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.urgency')),
            ],
            options={
                'db_table': 'urgency_label',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='VocabularySuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=40)),
                ('key', models.SlugField(max_length=80)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('usage_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined')], default='pending', max_length=16)),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'vocabulary_suggestion',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='casesubstatus',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='case_sub_status_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='casesubstatuslabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='case_sub_status_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='changetypelabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='change_type_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='closurereason',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='close_reason_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='closurereasonlabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='close_reason_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='compliancestatus',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='compliance_status_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='compliancestatuslabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='compliance_status_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='dismissalreason',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='dismissal_reason_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='dismissalreasonlabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='dismissal_reason_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='dutytypelabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='duty_type_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='effortsize',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='effort_size_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='effortsizelabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='effort_size_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='flaglabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='flag_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='instrumentlevellabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='instrument_level_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='librarytaglabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='library_tag_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='linkkind',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='link_kind_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='linkkindlabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='link_kind_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='provisionkind',
            constraint=models.UniqueConstraint(fields=('key',), name='provision_kind_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='provisionkindlabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='provision_kind_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='relationtypelabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='relation_type_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='riskrating',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='risk_rating_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='riskratinglabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='risk_rating_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='sourcekindlabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='source_kind_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='footprintterm',
            constraint=models.UniqueConstraint(fields=('tenant', 'term'), name='footprint_term_unique'),
        ),
        migrations.AddIndex(
            model_name='footprinthistory',
            index=models.Index(fields=['tenant', 'changed_at'], name='footprint_history_tenant_time'),
        ),
        migrations.AddConstraint(
            model_name='footprintchangeremove',
            constraint=models.UniqueConstraint(fields=('request', 'term'), name='footprint_change_remove_unique'),
        ),
        migrations.AddConstraint(
            model_name='footprintchangeadd',
            constraint=models.UniqueConstraint(fields=('request', 'term'), name='footprint_change_add_unique'),
        ),
        migrations.AddConstraint(
            model_name='taxonomytermlabel',
            constraint=models.UniqueConstraint(fields=('term', 'language'), name='taxonomy_term_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='tenanttag',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='tenant_tag_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='tagging',
            constraint=models.UniqueConstraint(fields=('tag', 'subject_type', 'subject_id'), name='tagging_unique'),
        ),
        migrations.AddConstraint(
            model_name='tenanttaglabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='tenant_tag_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='taxonomyterm',
            constraint=models.UniqueConstraint(fields=('dimension', 'key'), name='taxonomy_term_dimension_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='termdimensionlabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='term_dimension_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='urgencylabel',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'language'), name='urgency_label_unique'),
        ),
        # Tenant tables: RLS enabled and forced, tenant policy (playbook 14).
        *[operation for table in TENANT_TABLES for operation in rls_operations(table)],
        # The footprint history is a ledger (FP-02): append-only by trigger as well.
        *append_only_trigger_operations("footprint_history"),
        # The matching rule as a SQL function every list query can use (FP-01, FP-03).
        migrations.RunSQL(sql=IN_FOOTPRINT_FUNCTION, reverse_sql="DROP FUNCTION IF EXISTS taxonomy_in_footprint(uuid, uuid[])"),
        # Four eyes (FP-02, playbook 4.2): the requester never decides. Stated in SQL because
        # Django spells "not equal" as NOT (a = b AND a IS NOT NULL), and the four-eyes guard
        # reads the definition back from pg_constraint (apps/shared/tests_four_eyes.py).
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "footprint_change_request" ADD CONSTRAINT footprint_change_request_four_eyes '
                "CHECK (decided_by_id IS NULL OR decided_by_id <> requested_by_id)"
            ),
            reverse_sql='ALTER TABLE "footprint_change_request" DROP CONSTRAINT IF EXISTS footprint_change_request_four_eyes',
        ),
    ]
