# Generated by Django 6.1.1 on 2026-09-19 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


"""taxonomy 0002 (chunk 4, PRO-01, VOC-01): the rejection_reason library list and its
labels, replacing schema v0.3's `proposal.rejection_code` CHECK. Its seven system rows are
written by seed_reference; later changes go through proposals (VOC-07)."""


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('usage_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'rejection_reason',
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('key',), name='rejection_reason_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='RejectionReasonLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine', models.BooleanField(default=False)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomy.rejectionreason')),
            ],
            options={
                'db_table': 'rejection_reason_label',
                'ordering': ['language'],
                'constraints': [models.UniqueConstraint(fields=('vocabulary', 'language'), name='rejection_reason_label_unique')],
            },
        ),
    ]
