# Generated by Django 6.1.1 on 2026-09-19 09:29
"""taxonomy 0003 (FP-02, FP-S6): one waiting footprint change request per tenant, as a
partial unique index on (tenant_id) where status is pending. Two requests sent at the same
moment can no longer both wait; create_request answers 409 `request_pending`."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('shared', '0002_tenant_profile'),
        ('taxonomy', '0002_rejection_reason'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='footprintchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant',), name='footprint_change_request_one_pending'),
        ),
    ]
