# Generated by Django 6.1.1 on 2026-09-19 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import rls_operations

"""taxonomy 0004 (FP-04, D-30, INPUT_DELTAS §1): `watched_market`, the markets a tenant
watches without operating in them. One row per tenant per jurisdiction, in the tenant zone
under forced row-level security; the jurisdiction it names is a library row it keeps alive
(PROTECT). The logic, the routes and the panel come after it."""


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_api_key_agent'),
        ('library', '0004_append_only_versions'),
        ('shared', '0003_append_only_guard_ignores_the_app_role'),
        ('taxonomy', '0003_one_pending_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedMarket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.user')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='library.jurisdiction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.tenant')),
            ],
            options={
                'db_table': 'watched_market',
                'ordering': ['added_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'jurisdiction'), name='watched_market_unique')],
            },
        ),
        *rls_operations("watched_market"),
    ]
