# Generated by Django 6.1.1 on 2026-09-20 10:49

import django.db.models.deletion
from django.db import migrations, models


"""taxonomy 0005 (FP-04, D-28, ADR 0026): `taxonomy_term.jurisdiction`, the link a mirrored
term carries back to its jurisdiction row. Nullable, because every other term has none, and
unique, because a jurisdiction is mirrored by exactly one term. The reference seed fills it;
the rules that refuse a proposal or a tagging in a mirrored dimension read it."""


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_problem_report_context'),
        ('taxonomy', '0004_watched_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomyterm',
            name='jurisdiction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='library.jurisdiction'),
        ),
    ]
