# Generated by Django 6.1.1 on 2026-09-23 14:32

import django.db.models.deletion
from django.db import migrations, models


"""taxonomy 0007 (INV-05, PRO-02, VOC-07, D-62, D-79): machine-confirmed provenance on every
library list and on taxonomy terms, the same facts library 0007 gave an obligation version.

Each table gains `verified_origin` (the `origin_type` kind: `agent` or `user`, blank on a
seeded row), `verified_by_agent` (the confirming agent, when it was one) and
`applied_by_proposal` (the approved proposal that wrote the row's current wording). The
proposing agent is read through the proposal (`applied_by_proposal.proposed_by_agent`), as a
version's is, so both agents are named without a fourth column; the proposal table has no
migration that depends on this app, so the foreign key makes no cycle.
apps/proposals/apply.py sets all three on a create or a relabel and leaves them on a retire,
restore or merge, which write no wording.

The tables are listed here rather than read from the models, so the migration keeps meaning
what it meant when a list is later added or renamed (playbook 4.5)."""

TABLES = (
    "changetype",
    "dutytype",
    "flag",
    "instrumentlevel",
    "librarytag",
    "provisionkind",
    "rejectionreason",
    "relationtype",
    "sourcekind",
    "taxonomyterm",
    "termdimension",
    "urgency",
)


def _provenance(model_name: str) -> list[migrations.AddField]:
    return [
        migrations.AddField(
            model_name=model_name,
            name="applied_by_proposal",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="proposals.proposal"),
        ),
        migrations.AddField(
            model_name=model_name,
            name="verified_by_agent",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="agents.agent"),
        ),
        migrations.AddField(
            model_name=model_name,
            name="verified_origin",
            field=models.CharField(blank=True, choices=[("agent", "agent"), ("user", "user")], default="", max_length=16),
        ),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_agent_kind_review"),
        ("proposals", "0003_agent_reviewer"),
        ("taxonomy", "0006_opt_in_footprint"),
    ]

    operations = [operation for model_name in TABLES for operation in _provenance(model_name)]
