# Generated by Django 6.1.1 on 2026-09-25 02:48

import django.db.models.deletion
from django.db import migrations, models

"""taxonomy 0010 (chunk 8, TEN-02, D-21): the department a team belongs to. The key is also a
composite `(tenant_id, org_unit_id)` key to `UNIQUE (tenant_id, id)` on `org_unit`
(tenants 0002), because PostgreSQL checks a foreign key without row-level security and a
plain key would let a bank's team sit in another bank's unit."""


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0009_register_lists"),
        ("tenants", "0002_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="org_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="tenants.orgunit",
            ),
        ),
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "team" ADD CONSTRAINT team_org_unit_id_same_tenant FOREIGN KEY (tenant_id, org_unit_id) '
                'REFERENCES "org_unit" (tenant_id, id)'
            ),
            reverse_sql='ALTER TABLE "team" DROP CONSTRAINT IF EXISTS team_org_unit_id_same_tenant',
        ),
    ]
