# Generated by Django 6.1.1 on 2026-09-25 10:37

import apps.taxonomy.models
import django.db.models.deletion
import uuid
from django.db import migrations, models

"""taxonomy 0012 (d89-scope-items-model; OWN-01, FP-02, D-89, D-91, ADR 0059): a scope item,
the regulation a bank's own agent researches, and its rows on the regulatory scope request.

`scope_item` and `footprint_change_scope_item` are tenant tables under enabled and forced
row-level security. `footprint_history` names exactly one of a term or a scope item
(`footprint_history_term_or_scope_item`), so its term becomes nullable; every earlier row
names a term and passes. As in taxonomy 0010, PostgreSQL checks a foreign key without
row-level security, so each reference to a tenant row is also a composite `(tenant_id, …)`
key: to `UNIQUE (tenant_id, id)` on `scope_item` and on `footprint_change_request`. The
jurisdiction and the regime term are library rows and keep plain keys."""

from apps.shared.migration_helpers import rls_operations

# (table, column, target table)
COMPOSITE_KEYS = (
    ("footprint_change_scope_item", "request_id", "footprint_change_request"),
    ("footprint_change_scope_item", "scope_item_id", "scope_item"),
    ("footprint_history", "scope_item_id", "scope_item"),
)


def composite_key(table, column, target):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) REFERENCES "{target}" (tenant_id, id)',
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0007_credential_kinds"),
        ("library", "0010_recurring_duty"),
        ("shared", "0009_tenant_workflow_policy"),
        ("taxonomy", "0011_entry_scope_function"),
    ]

    operations = [
        migrations.CreateModel(
            name="FootprintChangeScopeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("added", "added"), ("removed", "removed")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "footprint_change_scope_item",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScopeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        validators=[
                            apps.taxonomy.models.validate_scope_item_description
                        ],
                    ),
                ),
                ("official_reference", models.CharField(blank=True, max_length=200)),
                (
                    "source_url",
                    models.URLField(
                        max_length=2000,
                        validators=[apps.taxonomy.models.validate_public_https_url],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "requested"),
                            ("in_scope", "in_scope"),
                            ("declined", "declined"),
                            ("removed", "removed"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "scope_item",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AlterField(
            model_name="footprinthistory",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="taxonomy.taxonomyterm",
            ),
        ),
        migrations.AddConstraint(
            model_name="footprintchangerequest",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"),
                name="footprint_change_request_tenant_id_unique",
            ),
        ),
        migrations.AddField(
            model_name="footprintchangescopeitem",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scope_item_links",
                to="taxonomy.footprintchangerequest",
            ),
        ),
        migrations.AddField(
            model_name="footprintchangescopeitem",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="shared.tenant",
            ),
        ),
        migrations.AddField(
            model_name="scopeitem",
            name="jurisdiction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="library.jurisdiction",
            ),
        ),
        migrations.AddField(
            model_name="scopeitem",
            name="regime_term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="taxonomy.taxonomyterm",
            ),
        ),
        migrations.AddField(
            model_name="scopeitem",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="shared.tenant",
            ),
        ),
        migrations.AddField(
            model_name="footprintchangescopeitem",
            name="scope_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_links",
                to="taxonomy.scopeitem",
            ),
        ),
        migrations.AddField(
            model_name="footprinthistory",
            name="scope_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history",
                to="taxonomy.scopeitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="footprinthistory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope_item__isnull", True), ("term__isnull", False)),
                    models.Q(("scope_item__isnull", False), ("term__isnull", True)),
                    _connector="OR",
                ),
                name="footprint_history_term_or_scope_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeitem",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="scope_item_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeitem",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="scope_item_tenant_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_url__startswith", "https://")),
                name="scope_item_source_https",
            ),
        ),
        migrations.AddConstraint(
            model_name="footprintchangescopeitem",
            constraint=models.UniqueConstraint(
                fields=("request", "scope_item"),
                name="footprint_change_scope_item_unique",
            ),
        ),
        *rls_operations("scope_item"),
        *rls_operations("footprint_change_scope_item"),
        *[composite_key(*key) for key in COMPOSITE_KEYS],
    ]
