# Generated by Django 6.1.1 on 2026-10-05 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models

"""taxonomy 0013 (public-registers; FP-05, D-121, ADR 0066): a company's own scope.

`entity_scope_exclusion` holds the licence-bound terms outside one legal entity's own scope,
and `footprint_change_entity_term` the company lines a regulatory scope request carries, so
the same request, second person and passkey decide them. `footprint_history` gains the
company a term row was for; every earlier row has none and is the bank's. Both new tables
are tenant tables under enabled and forced row-level security, and as in taxonomy 0012 each
reference to a tenant row is also a composite `(tenant_id, …)` key, because PostgreSQL
checks a foreign key without row-level security. Terms are library rows and keep plain keys."""

from apps.shared.migration_helpers import rls_operations

# (table, column, target table)
COMPOSITE_KEYS = (
    ("footprint_history", "org_unit_id", "org_unit"),
    ("entity_scope_exclusion", "org_unit_id", "org_unit"),
    ("entity_scope_exclusion", "request_id", "footprint_change_request"),
    ("footprint_change_entity_term", "org_unit_id", "org_unit"),
    ("footprint_change_entity_term", "request_id", "footprint_change_request"),
)


def composite_key(table, column, target):
    name = f"{table}_{column}_same_tenant"
    return migrations.RunSQL(
        sql=f'ALTER TABLE "{table}" ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) REFERENCES "{target}" (tenant_id, id)',
        reverse_sql=f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS {name}',
    )


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0010_login_event_access_token_refused"),
        ("shared", "0010_jurisdiction_proposal_door"),
        ("taxonomy", "0012_scope_items"),
        ("tenants", "0005_licence_product_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="footprinthistory",
            name="org_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenants.orgunit",
            ),
        ),
        migrations.CreateModel(
            name="EntityScopeExclusion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scope_exclusions",
                        to="tenants.orgunit",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.footprintchangerequest",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.taxonomyterm",
                    ),
                ),
            ],
            options={
                "db_table": "entity_scope_exclusion",
                "ordering": ["org_unit", "term", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_unit", "term"),
                        name="entity_scope_exclusion_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FootprintChangeEntityTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("added", "added"), ("removed", "removed")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.orgunit",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_links",
                        to="taxonomy.footprintchangerequest",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.taxonomyterm",
                    ),
                ),
            ],
            options={
                "db_table": "footprint_change_entity_term",
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request", "org_unit", "term"),
                        name="footprint_change_entity_term_unique",
                    )
                ],
            },
        ),
        *rls_operations("entity_scope_exclusion"),
        *rls_operations("footprint_change_entity_term"),
        *[composite_key(*key) for key in COMPOSITE_KEYS],
    ]
