# Generated by Django 6.1.1 on 2026-10-08 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0013_entity_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityscopeexclusion",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="taxonomy.footprintchangerequest",
            ),
        ),
    ]
