# Generated by Django 6.1.1 on 2026-09-19 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


"""shared 0002 (chunk 1, TEN-01): the tenant profile columns (status, default language,
ordered content languages) and forced RLS on the new tenant table. `step_up_assertion_id`
on audit_event already exists since 0001. Generated, then the RunSQL parts appended."""

from apps.shared.migration_helpers import rls_operations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='library.language'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=16),
        ),
        migrations.CreateModel(
            name='TenantContentLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='library.language')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_language_links', to='shared.tenant')),
            ],
            options={
                'db_table': 'tenant_content_language',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='content_languages',
            field=models.ManyToManyField(blank=True, related_name='+', through='shared.TenantContentLanguage', to='library.language'),
        ),
        migrations.AddConstraint(
            model_name='tenantcontentlanguage',
            constraint=models.UniqueConstraint(fields=('tenant', 'language'), name='tenant_content_language_unique'),
        ),
        # Tenant table: RLS enabled and forced, tenant policy (playbook 14).
        *rls_operations("tenant_content_language"),
    ]
