# Generated by Django 6.1.1 on 2026-09-20 07:58

import uuid
from django.db import migrations, models


"""shared 0004 (chunk 5, ruling 9): `outbox_cursor`, the one ordered cursor over
`outbox_event` (apps/shared/outbox.py). One row, created by the worker on its first pass.

No row-level security and no append-only trigger, deliberately: the table holds a position
and a clock and no tenant content, and the worker rewrites all three columns on every
pass. The rows it points at keep their own zone and their own trigger. cw_app reaches it
through the default privileges shared 0001 granted to cw_migrator's later tables."""


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0003_append_only_guard_ignores_the_app_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxCursor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("last_created", models.DateTimeField(blank=True, null=True)),
                ("last_id", models.UUIDField(blank=True, null=True)),
                ("retry_not_before", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "outbox_cursor",
                "ordering": ["name"],
            },
        ),
    ]
