"""shared 0009 (chunk 10, COL-02, TEN-01): the bank's workflow policy as six columns on
`tenant` instead of the designed `settings` blob (INPUT_DELTAS §7). Each column is added
with the platform default read from settings, which PostgreSQL writes into every tenant
that already exists; the check constraints hold the policy's bounds for every writer.
`tenant` already sits under forced row-level security (0002)."""

import apps.shared.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0009_problem_report_closure"),
        ("shared", "0008_library_write_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="digest_weekday",
            field=models.CharField(
                choices=[
                    ("monday", "monday"),
                    ("tuesday", "tuesday"),
                    ("wednesday", "wednesday"),
                    ("thursday", "thursday"),
                    ("friday", "friday"),
                    ("saturday", "saturday"),
                    ("sunday", "sunday"),
                ],
                default=apps.shared.models.default_digest_weekday,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="escalate_after_days",
            field=models.PositiveSmallIntegerField(
                default=apps.shared.models.default_escalate_after_days
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="escalate_to_role",
            field=models.CharField(
                default=apps.shared.models.default_escalate_to_role, max_length=80
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="reminder_days_before",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                default=apps.shared.models.default_reminder_days_before,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="review_reminder_days_before",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                default=apps.shared.models.default_review_reminder_days_before,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="triage_target_hours",
            field=models.PositiveSmallIntegerField(
                default=apps.shared.models.default_triage_target_hours
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reminder_days_before__contained_by",
                        [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            12,
                            13,
                            14,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                            26,
                            27,
                            28,
                            29,
                            30,
                            31,
                            32,
                            33,
                            34,
                            35,
                            36,
                            37,
                            38,
                            39,
                            40,
                            41,
                            42,
                            43,
                            44,
                            45,
                            46,
                            47,
                            48,
                            49,
                            50,
                            51,
                            52,
                            53,
                            54,
                            55,
                            56,
                            57,
                            58,
                            59,
                            60,
                            61,
                            62,
                            63,
                            64,
                            65,
                            66,
                            67,
                            68,
                            69,
                            70,
                            71,
                            72,
                            73,
                            74,
                            75,
                            76,
                            77,
                            78,
                            79,
                            80,
                            81,
                            82,
                            83,
                            84,
                            85,
                            86,
                            87,
                            88,
                            89,
                            90,
                        ],
                    ),
                    ("reminder_days_before__len__gte", 1),
                    ("reminder_days_before__len__lte", 5),
                ),
                name="tenant_reminder_days_before_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "review_reminder_days_before__contained_by",
                        [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            12,
                            13,
                            14,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                            26,
                            27,
                            28,
                            29,
                            30,
                            31,
                            32,
                            33,
                            34,
                            35,
                            36,
                            37,
                            38,
                            39,
                            40,
                            41,
                            42,
                            43,
                            44,
                            45,
                            46,
                            47,
                            48,
                            49,
                            50,
                            51,
                            52,
                            53,
                            54,
                            55,
                            56,
                            57,
                            58,
                            59,
                            60,
                            61,
                            62,
                            63,
                            64,
                            65,
                            66,
                            67,
                            68,
                            69,
                            70,
                            71,
                            72,
                            73,
                            74,
                            75,
                            76,
                            77,
                            78,
                            79,
                            80,
                            81,
                            82,
                            83,
                            84,
                            85,
                            86,
                            87,
                            88,
                            89,
                            90,
                        ],
                    ),
                    ("review_reminder_days_before__len__gte", 1),
                    ("review_reminder_days_before__len__lte", 5),
                ),
                name="tenant_review_reminder_days_before_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("escalate_after_days__gte", 1), ("escalate_after_days__lte", 90)
                ),
                name="tenant_escalate_after_days_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("triage_target_hours__gte", 1), ("triage_target_hours__lte", 720)
                ),
                name="tenant_triage_target_hours_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "digest_weekday__in",
                        [
                            "monday",
                            "tuesday",
                            "wednesday",
                            "thursday",
                            "friday",
                            "saturday",
                            "sunday",
                        ],
                    )
                ),
                name="tenant_digest_weekday_valid",
            ),
        ),
    ]
