# Generated by Django 6.1.1 on 2026-09-19 09:18

import django.db.models.deletion
from django.db import migrations, models

"""identity 0002 (chunk 5, ID-10): api_key.agent_id becomes a foreign key to the agent
table, so a key names the agent whose writes it signs (schema v0.3 api_key.agent_id)."""


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apikey",
            name="agent_id",
        ),
        migrations.AddField(
            model_name="apikey",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_keys",
                to="agents.agent",
            ),
        ),
    ]
