# Generated by Django 6.1.1 on 2026-09-21 05:33

from django.db import migrations, models

"""identity 0004 (ID-11, HOM-04, D-52, ADR 0045): the security log learns one more kind.

`feed_used` is written when a calendar client fetches a subscribed feed with its token.
The token in a calendar address is the only credential in the product that is not a
passkey, a session or an API key, so its use belongs in the same ledger as a key's; the
row records the subscription's owner and never the address, and the write is throttled the
way `key_used` is, because a calendar client polls every few minutes for years.

A choices change and nothing else: the column stays `varchar(32)` and no row moves.
"""


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_mixed_tables_write_their_own_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginevent',
            name='event',
            field=models.CharField(choices=[('code_sent', 'code_sent'), ('code_refused_enrolled', 'code_refused_enrolled'), ('code_failed', 'code_failed'), ('code_locked', 'code_locked'), ('enrolled', 'enrolled'), ('signin', 'signin'), ('signin_failed', 'signin_failed'), ('step_up', 'step_up'), ('step_up_failed', 'step_up_failed'), ('refresh_replay', 'refresh_replay'), ('session_revoked', 'session_revoked'), ('reenrolment_issued', 'reenrolment_issued'), ('key_used', 'key_used'), ('key_revoked', 'key_revoked'), ('feed_used', 'feed_used')], max_length=32),
        ),
    ]
