# Generated by Django 6.1.1 on 2026-09-23 06:06

from django.db import migrations, models

"""identity 0005 (ID-10, ID-11, AGT-01): the security log learns two more kinds.

`key_created` is written when a platform administrator mints a key bound to an agent, so
the one kind of key that reaches the shared watch feed is in the log from its first moment
and not only from its first use. `key_scopes_withheld` is written when a bank's key
presents a scope only a platform key may hold and works without it; the row names the
scopes and nothing else, and is throttled with `key_used`.

A choices change and nothing else: the column stays `varchar(32)` and no row moves.
"""


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_login_event_feed_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginevent',
            name='event',
            field=models.CharField(choices=[('code_sent', 'code_sent'), ('code_refused_enrolled', 'code_refused_enrolled'), ('code_failed', 'code_failed'), ('code_locked', 'code_locked'), ('enrolled', 'enrolled'), ('signin', 'signin'), ('signin_failed', 'signin_failed'), ('step_up', 'step_up'), ('step_up_failed', 'step_up_failed'), ('refresh_replay', 'refresh_replay'), ('session_revoked', 'session_revoked'), ('reenrolment_issued', 'reenrolment_issued'), ('key_used', 'key_used'), ('key_revoked', 'key_revoked'), ('key_created', 'key_created'), ('key_scopes_withheld', 'key_scopes_withheld'), ('feed_used', 'feed_used')], max_length=32),
        ),
    ]
