# Generated by Django 6.1.1 on 2026-09-25 02:59

import django.db.models.deletion
from django.db import migrations, models

"""identity 0007 (acc-foundation; ACC-03, D-77, ADR 0056): one `api_key` table for two
credential kinds. `kind` arrives with the default `service`, so every key minted before it
is a service key. A service key may be bound to an agent access entry (`agent_access`) and
a personal access token acts as a member (`acts_as_user`); CHECKs fence the token (a
tenant, a person and an expiry, never an agent's), keep an entry's key a bank's key, and
keep both to the read scopes. The entry and the person are also composite
`(tenant_id, …)` keys, because PostgreSQL checks a foreign key without row-level security
and `api_key` is a mixed table: neither may be another bank's. `login_event` gains the
method `personal_token` and the token and rate-limit events; both are choices only."""

SAME_TENANT_KEYS = (
    ("agent_access_id", "agent_access", "id"),
    ("acts_as_user_id", "membership", "user_id"),
)


def same_tenant(column, target, target_column):
    name = f"api_key_{column}_same_tenant"
    return migrations.RunSQL(
        sql=(
            f"ALTER TABLE api_key ADD CONSTRAINT {name} FOREIGN KEY (tenant_id, {column}) "
            f'REFERENCES "{target}" (tenant_id, {target_column})'
        ),
        reverse_sql=f"ALTER TABLE api_key DROP CONSTRAINT IF EXISTS {name}",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_agent_access"),
        ("identity", "0006_retire_applicability_request"),
        ("shared", "0008_library_write_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="acts_as_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.user",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="agent_access",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_keys",
                to="agents.agentaccess",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="kind",
            field=models.CharField(
                choices=[("service", "service"), ("personal", "personal")],
                default="service",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="loginevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("code_sent", "code_sent"),
                    ("code_refused_enrolled", "code_refused_enrolled"),
                    ("code_failed", "code_failed"),
                    ("code_locked", "code_locked"),
                    ("enrolled", "enrolled"),
                    ("signin", "signin"),
                    ("signin_failed", "signin_failed"),
                    ("step_up", "step_up"),
                    ("step_up_failed", "step_up_failed"),
                    ("refresh_replay", "refresh_replay"),
                    ("session_revoked", "session_revoked"),
                    ("reenrolment_issued", "reenrolment_issued"),
                    ("key_used", "key_used"),
                    ("key_revoked", "key_revoked"),
                    ("key_created", "key_created"),
                    ("key_scopes_withheld", "key_scopes_withheld"),
                    ("feed_used", "feed_used"),
                    ("token_created", "token_created"),
                    ("token_used", "token_used"),
                    ("token_revoked", "token_revoked"),
                    ("credential_rate_limited", "credential_rate_limited"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="loginevent",
            name="method",
            field=models.CharField(
                choices=[
                    ("email_code", "email_code"),
                    ("passkey", "passkey"),
                    ("api_key", "api_key"),
                    ("personal_token", "personal_token"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="apikey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("acts_as_user__isnull", True), ("kind", "service")),
                    models.Q(
                        ("acts_as_user__isnull", False),
                        ("agent__isnull", True),
                        ("expires_at__isnull", False),
                        ("kind", "personal"),
                        ("tenant__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="api_key_personal_token_fenced",
            ),
        ),
        migrations.AddConstraint(
            model_name="apikey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("agent_access__isnull", True),
                    models.Q(("agent__isnull", True), ("tenant__isnull", False)),
                    _connector="OR",
                ),
                name="api_key_entry_key_is_a_tenant_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="apikey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("agent_access__isnull", True), ("kind", "service")),
                    (
                        "scopes__contained_by",
                        ["library:read", "search:read", "tenant:read", "upcoming:read"],
                    ),
                    _connector="OR",
                ),
                name="api_key_agent_access_reads_only",
            ),
        ),
        *[same_tenant(*key) for key in SAME_TENANT_KEYS],
    ]
