# Generated by Django 6.1.1 on 2026-09-25 10:29

import django.db.models.deletion
from django.db import migrations, models

"""identity 0009 (c8-support-session-guard; TEN-06, D-49, ADR 0042): the support session.
`user_session` gains `support_access`, the grant a support session stands on, and the kind
`support`; a CHECK keeps them together, so a support session always names a bank and a
grant and no other session names a grant. The grant is also a composite
`(tenant_id, support_access_id)` key, because PostgreSQL checks a foreign key without
row-level security and `user_session` is a mixed table: a session in one bank can never
stand on another bank's grant. `support_access` gains `UNIQUE (tenant_id, id)` for it, the
shape tenants 0002 gives the organisation tables. No policy is added or changed anywhere."""

GRANT_UNIQUE = "support_access_tenant_id_id_unique"
SAME_TENANT_GRANT = "user_session_support_access_same_tenant"


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0007_credential_kinds"),
        ("shared", "0009_tenant_workflow_policy"),
        ("tenants", "0004_support_grants"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="support_access",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenants.supportaccess",
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="kind",
            field=models.CharField(
                choices=[
                    ("enrolment", "enrolment"),
                    ("full", "full"),
                    ("support", "support"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="usersession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "support"),
                        ("support_access__isnull", False),
                        ("tenant__isnull", False),
                    ),
                    models.Q(
                        models.Q(("kind", "support"), _negated=True),
                        ("support_access__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="user_session_support_stands_on_a_grant",
            ),
        ),
        migrations.RunSQL(
            sql=f"ALTER TABLE support_access ADD CONSTRAINT {GRANT_UNIQUE} UNIQUE (tenant_id, id)",
            reverse_sql=f"ALTER TABLE support_access DROP CONSTRAINT IF EXISTS {GRANT_UNIQUE}",
        ),
        migrations.RunSQL(
            sql=(
                f"ALTER TABLE user_session ADD CONSTRAINT {SAME_TENANT_GRANT} FOREIGN KEY (tenant_id, support_access_id) "
                "REFERENCES support_access (tenant_id, id)"
            ),
            reverse_sql=f"ALTER TABLE user_session DROP CONSTRAINT IF EXISTS {SAME_TENANT_GRANT}",
        ),
    ]
