# Generated by Django 6.1.1 on 2026-09-28 17:35

from django.db import migrations, models

"""identity 0010 (perf-tenant-in-token, ADR 0064): the security log's `event` gains
`access_token_refused`, written when a correctly signed access token names a bank that is not
its session's. Choices only; no column, policy or trigger changes."""


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0009_support_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("code_sent", "code_sent"),
                    ("code_refused_enrolled", "code_refused_enrolled"),
                    ("code_failed", "code_failed"),
                    ("code_locked", "code_locked"),
                    ("enrolled", "enrolled"),
                    ("signin", "signin"),
                    ("signin_failed", "signin_failed"),
                    ("step_up", "step_up"),
                    ("step_up_failed", "step_up_failed"),
                    ("refresh_replay", "refresh_replay"),
                    ("session_revoked", "session_revoked"),
                    ("reenrolment_issued", "reenrolment_issued"),
                    ("key_used", "key_used"),
                    ("key_revoked", "key_revoked"),
                    ("key_created", "key_created"),
                    ("key_scopes_withheld", "key_scopes_withheld"),
                    ("feed_used", "feed_used"),
                    ("token_created", "token_created"),
                    ("token_used", "token_used"),
                    ("token_revoked", "token_revoked"),
                    ("credential_rate_limited", "credential_rate_limited"),
                    ("access_token_refused", "access_token_refused"),
                ],
                max_length=32,
            ),
        ),
    ]
