# Generated by Django 6.1.1 on 2026-09-20 08:00

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.db import migrations, models

from apps.shared.migration_helpers import rls_operations

"""watch 0001 (chunk 5, WAT-01..WAT-04, WAT-07, AGT-01): the source registry, the coverage
log, one regulatory change per reform with its timeline, its source pages, its flags and
scope terms, and its obligation links. All seven are library tables with no tenant_id: a
bank's triage, its "So what?" and its decision live on change_case.

`source` alone carries WAT-06's owner_tenant_id, unused in R1 and left NULL, so the
row-level shape is final before R3's tenant-private sources (INPUT_DELTAS §5). It is
therefore a mixed table and takes `rls_operations(mixed=True, column="owner_tenant_id")`,
the split shape of hardening H15: one FOR ALL policy whose USING and WITH CHECK are the
session's own zone, so a bank can write only its own private sources and a session with no
tenant only the shared ones, and `library_rows_visible`, a FOR SELECT policy that adds the
shared rows to every bank's reads. Permissive policies OR together per command, so reads
are mixed and writes are not. Not `library_fence=True`: the seeds and builders that write a
source do it with no tenant active (apps/watch/write.py), so the narrow write rule holds
from the first row, which is what instrument and obligation cannot say yet (H16)."""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("identity", "0002_api_key_agent"),
        ("library", "0005_problem_report_context"),
        ("shared", "0003_append_only_guard_ignores_the_app_role"),
        ("taxonomy", "0004_watched_market"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulatoryChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stable_key", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("authority_label", models.CharField(max_length=200)),
                ("published_on", models.DateField(blank=True, null=True)),
                (
                    "published_precision",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("month", "month"),
                            ("quarter", "quarter"),
                            ("year", "year"),
                        ],
                        default="day",
                        max_length=8,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("so_what_draft", models.TextField(blank=True)),
                ("key_date", models.DateField(blank=True, null=True)),
                (
                    "key_date_precision",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("month", "month"),
                            ("quarter", "quarter"),
                            ("year", "year"),
                        ],
                        default="day",
                        max_length=8,
                    ),
                ),
                ("key_date_label", models.CharField(blank=True, max_length=200)),
                ("recurrence_rule", models.CharField(blank=True, max_length=500)),
                ("source_label", models.CharField(max_length=500)),
                ("source_url", models.URLField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("superseded", "superseded"),
                            ("withdrawn", "withdrawn"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("agent", "agent"), ("user", "user")], max_length=16
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=200)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="agents.agentrun",
                    ),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="library.authority",
                    ),
                ),
                (
                    "change_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.changetype",
                    ),
                ),
                (
                    "suggested_urgency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.urgency",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersedes",
                        to="watch.regulatorychange",
                    ),
                ),
            ],
            options={
                "db_table": "regulatory_change",
                "ordering": [
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F("key_date"), descending=True, nulls_last=True
                    ),
                    "-first_seen_at",
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("suggested", models.BooleanField(default=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.flag",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.taxonomyterm",
                    ),
                ),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_links",
                        to="watch.regulatorychange",
                    ),
                ),
            ],
            options={
                "db_table": "change_term",
                "ordering": ["flag__sort_order", "term__sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChangeObligation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("agent", "agent"), ("user", "user")], max_length=16
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.user",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_links",
                        to="library.obligation",
                    ),
                ),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obligation_links",
                        to="watch.regulatorychange",
                    ),
                ),
            ],
            options={
                "db_table": "change_obligation",
                "ordering": [
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F("confidence"), descending=True, nulls_last=True
                    ),
                    "obligation__stable_key",
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "date_precision",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("month", "month"),
                            ("quarter", "quarter"),
                            ("year", "year"),
                        ],
                        default="day",
                        max_length=8,
                    ),
                ),
                ("occurred", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("source_url", models.URLField(blank=True, max_length=2000)),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="watch.regulatorychange",
                    ),
                ),
            ],
            options={
                "db_table": "change_event",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChangeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=128)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_duplicate", models.BooleanField(default=False)),
                (
                    "risk_flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="watch.regulatorychange",
                    ),
                ),
            ],
            options={
                "db_table": "change_document",
                "ordering": ["-is_primary", "url"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("url", models.URLField(blank=True, max_length=2000)),
                (
                    "check_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                        ],
                        default="weekly",
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="library.authority",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.sourcekind",
                    ),
                ),
                (
                    "owner_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shared.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "source",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SourceCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "ok"), ("failed", "failed")], max_length=16
                    ),
                ),
                ("items_found", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("sweep", "sweep"), ("recheck", "recheck")],
                        default="sweep",
                        max_length=16,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("instrument", "instrument"),
                            ("provision", "provision"),
                            ("obligation", "obligation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("subject_id", models.UUIDField(blank=True, null=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_checks",
                        to="agents.agentrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checks",
                        to="watch.source",
                    ),
                ),
            ],
            options={
                "db_table": "source_check",
                "ordering": ["-checked_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="regulatorychange",
            index=models.Index(
                condition=models.Q(("status", "active")),
                fields=["key_date"],
                name="regulatory_change_key_date_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychange",
            constraint=models.CheckConstraint(
                condition=models.Q(("superseded_by", models.F("id")), _negated=True),
                name="regulatory_change_not_self_superseded",
            ),
        ),
        migrations.AddConstraint(
            model_name="changeterm",
            constraint=models.UniqueConstraint(
                fields=("change", "term"), name="change_term_term_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="changeterm",
            constraint=models.UniqueConstraint(
                fields=("change", "flag"), name="change_term_flag_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="changeterm",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("flag__isnull", False), ("term__isnull", True)),
                    models.Q(("flag__isnull", True), ("term__isnull", False)),
                    _connector="OR",
                ),
                name="change_term_one_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="changeterm",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence__isnull", True),
                    models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                    _connector="OR",
                ),
                name="change_term_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="changeterm",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confirmed_at__isnull", True),
                        ("confirmed_by__isnull", True),
                        ("suggested", True),
                    ),
                    models.Q(
                        ("confirmed_at__isnull", False),
                        ("confirmed_by__isnull", False),
                        ("suggested", False),
                    ),
                    _connector="OR",
                ),
                name="change_term_confirmation_names_a_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="changeobligation",
            constraint=models.UniqueConstraint(
                fields=("change", "obligation"), name="change_obligation_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="changeobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence__isnull", True),
                    models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                    _connector="OR",
                ),
                name="change_obligation_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="changeobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confirmed_at__isnull", True), ("confirmed_by__isnull", True)
                    ),
                    models.Q(
                        ("confirmed_at__isnull", False), ("confirmed_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="change_obligation_confirmation_names_a_person",
            ),
        ),
        migrations.AddIndex(
            model_name="changeevent",
            index=models.Index(
                fields=["change", "sort_order"], name="change_event_change_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="changedocument",
            constraint=models.UniqueConstraint(
                fields=("change", "url"), name="change_document_url_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcecheck",
            index=models.Index(
                fields=["source", "-checked_at"], name="source_check_latest_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecheck",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "recheck"),
                        models.Q(("subject_type", ""), _negated=True),
                        ("subject_id__isnull", False),
                    ),
                    models.Q(
                        models.Q(("kind", "recheck"), _negated=True),
                        ("subject_type", ""),
                        ("subject_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="source_check_recheck_names_a_subject",
            ),
        ),
        *rls_operations("source", mixed=True, column="owner_tenant_id"),
    ]
