# Generated by Django 6.1.1 on 2026-09-23 14:39

import django.db.models.deletion
from django.db import migrations, models

"""watch 0002 (WAT-03, WAT-04, D-74): a curated fact may be confirmed by an agent of
another definition as well as by a person, and says who suggested it and who confirmed it.

`change_term`, `change_obligation` and the change's type each gain the suggesting agent
and key (copied from the run or the key that filed the fact) and the confirming key and
agent. The change's type gains the four columns a flag already had (`suggested`,
`confidence`, `confirmed_by`, `confirmed_at`), so a type is settled like a term or a link.

The confirmation constraints are widened from "names a person" to "names a person, or an
agent-bound key and its agent, never both", and a second constraint refuses a confirming
key or agent equal to the suggesting one, so two keys of one agent cannot confirm each
other and a key bound to no agent cannot pass on a null.

Existing rows need no data step: every type is still a suggestion (nothing ever confirmed
one), and every confirmation stored so far named a person, which the widened constraint
still accepts."""


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_kind_review'),
        ('identity', '0005_login_event_key_created_and_withheld'),
        ('library', '0008_standard_level_regime_required'),
        ('taxonomy', '0006_opt_in_footprint'),
        ('watch', '0001_watch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='changeobligation',
            name='change_obligation_confirmation_names_a_person',
        ),
        migrations.RemoveConstraint(
            model_name='changeterm',
            name='change_term_confirmation_names_a_person',
        ),
        migrations.AddField(
            model_name='changeobligation',
            name='confirmed_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='changeobligation',
            name='confirmed_by_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.apikey'),
        ),
        migrations.AddField(
            model_name='changeobligation',
            name='suggested_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='changeobligation',
            name='suggested_by_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.apikey'),
        ),
        migrations.AddField(
            model_name='changeterm',
            name='confirmed_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='changeterm',
            name='confirmed_by_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.apikey'),
        ),
        migrations.AddField(
            model_name='changeterm',
            name='suggested_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='changeterm',
            name='suggested_by_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.apikey'),
        ),
        migrations.AddField(
            model_name='regulatorychange',
            name='change_type_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='regulatorychange',
            name='change_type_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regulatorychange',
            name='change_type_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.user'),
        ),
        migrations.AddField(
            model_name='regulatorychange',
            name='change_type_confirmed_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='regulatorychange',
            name='change_type_confirmed_by_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.apikey'),
        ),
        migrations.AddField(
            model_name='regulatorychange',
            name='change_type_suggested',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regulatorychange',
            name='change_type_suggested_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='regulatorychange',
            name='change_type_suggested_by_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.apikey'),
        ),
        migrations.AddConstraint(
            model_name='changeobligation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('confirmed_by_api_key__isnull', True), ('confirmed_by_agent__isnull', True)), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('confirmed_by_api_key__isnull', True), ('confirmed_by_agent__isnull', True)), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', True), ('confirmed_by_api_key__isnull', False), ('confirmed_by_agent__isnull', False)), _connector='OR'), name='change_obligation_confirmation_names_a_person_or_an_agent'),
        ),
        migrations.AddConstraint(
            model_name='changeobligation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_by_agent__isnull', True), ('suggested_by_agent__isnull', True), models.Q(('confirmed_by_agent', models.F('suggested_by_agent')), _negated=True), _connector='OR'), models.Q(('confirmed_by_api_key__isnull', True), ('suggested_by_api_key__isnull', True), models.Q(('confirmed_by_api_key', models.F('suggested_by_api_key')), _negated=True), _connector='OR')), name='change_obligation_confirmer_is_not_the_suggester'),
        ),
        migrations.AddConstraint(
            model_name='changeterm',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('suggested', True), ('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('confirmed_by_api_key__isnull', True), ('confirmed_by_agent__isnull', True)), models.Q(('suggested', False), models.Q(models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('confirmed_by_api_key__isnull', True), ('confirmed_by_agent__isnull', True)), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', True), ('confirmed_by_api_key__isnull', False), ('confirmed_by_agent__isnull', False)), _connector='OR')), _connector='OR'), name='change_term_confirmation_names_a_person_or_an_agent'),
        ),
        migrations.AddConstraint(
            model_name='changeterm',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_by_agent__isnull', True), ('suggested_by_agent__isnull', True), models.Q(('confirmed_by_agent', models.F('suggested_by_agent')), _negated=True), _connector='OR'), models.Q(('confirmed_by_api_key__isnull', True), ('suggested_by_api_key__isnull', True), models.Q(('confirmed_by_api_key', models.F('suggested_by_api_key')), _negated=True), _connector='OR')), name='change_term_confirmer_is_not_the_suggester'),
        ),
        migrations.AddConstraint(
            model_name='regulatorychange',
            constraint=models.CheckConstraint(condition=models.Q(('change_type_confidence__isnull', True), models.Q(('change_type_confidence__gte', 0), ('change_type_confidence__lte', 1)), _connector='OR'), name='regulatory_change_type_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='regulatorychange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('change_type_suggested', True), ('change_type_confirmed_at__isnull', True), ('change_type_confirmed_by__isnull', True), ('change_type_confirmed_by_api_key__isnull', True), ('change_type_confirmed_by_agent__isnull', True)), models.Q(('change_type_suggested', False), models.Q(models.Q(('change_type_confirmed_at__isnull', False), ('change_type_confirmed_by__isnull', False), ('change_type_confirmed_by_api_key__isnull', True), ('change_type_confirmed_by_agent__isnull', True)), models.Q(('change_type_confirmed_at__isnull', False), ('change_type_confirmed_by__isnull', True), ('change_type_confirmed_by_api_key__isnull', False), ('change_type_confirmed_by_agent__isnull', False)), _connector='OR')), _connector='OR'), name='regulatory_change_type_confirmation_names_a_person_or_an_agent'),
        ),
        migrations.AddConstraint(
            model_name='regulatorychange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('change_type_confirmed_by_agent__isnull', True), ('change_type_suggested_by_agent__isnull', True), models.Q(('change_type_confirmed_by_agent', models.F('change_type_suggested_by_agent')), _negated=True), _connector='OR'), models.Q(('change_type_confirmed_by_api_key__isnull', True), ('change_type_suggested_by_api_key__isnull', True), models.Q(('change_type_confirmed_by_api_key', models.F('change_type_suggested_by_api_key')), _negated=True), _connector='OR')), name='regulatory_change_type_confirmer_is_not_the_suggester'),
        ),
    ]
